version: "2"

run:
  skip-dirs:
    - vendor

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
