// Code generated by "stringer -type=AuthType"; DO NOT EDIT.

package pgwire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthTypeOk-0]
	_ = x[AuthTypeCleartextPassword-3]
	_ = x[AuthTypeMD5Password-5]
	_ = x[AuthTypeGSS-7]
	_ = x[AuthTypeGSSContinue-8]
	_ = x[AuthTypeSASL-10]
	_ = x[AuthTypeSASLContinue-11]
	_ = x[AuthTypeSASLFinal-12]
}

const (
	_AuthType_name_0 = "AuthTypeOk"
	_AuthType_name_1 = "AuthTypeCleartextPassword"
	_AuthType_name_2 = "AuthTypeMD5Password"
	_AuthType_name_3 = "AuthTypeGSSAuthTypeGSSContinue"
	_AuthType_name_4 = "AuthTypeSASLAuthTypeSASLContinueAuthTypeSASLFinal"
)

var (
	_AuthType_index_3 = [...]uint8{0, 11, 30}
	_AuthType_index_4 = [...]uint8{0, 12, 32, 49}
)

func (i AuthType) String() string {
	switch {
	case i == 0:
		return _AuthType_name_0
	case i == 3:
		return _AuthType_name_1
	case i == 5:
		return _AuthType_name_2
	case 7 <= i && i <= 8:
		i -= 7
		return _AuthType_name_3[_AuthType_index_3[i]:_AuthType_index_3[i+1]]
	case 10 <= i && i <= 12:
		i -= 10
		return _AuthType_name_4[_AuthType_index_4[i]:_AuthType_index_4[i+1]]
	default:
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
