// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// BackendAsync is implemented by all Backend Async message wrapper types.
type BackendAsync interface {
	Backend()
	Async()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ BackendAsync = BackendAsyncNoticeResponse{}
	_ BackendAsync = BackendAsyncNotificationResponse{}
	_ BackendAsync = BackendAsyncParameterStatus{}
)

// Warning message.
type BackendAsyncNoticeResponse FromBackend[*pgproto3.NoticeResponse]

func (BackendAsyncNoticeResponse) Backend() {}
func (BackendAsyncNoticeResponse) Async()   {}

// LISTEN/NOTIFY notification.
type BackendAsyncNotificationResponse FromBackend[*pgproto3.NotificationResponse]

func (BackendAsyncNotificationResponse) Backend() {}
func (BackendAsyncNotificationResponse) Async()   {}

// Informs client that runtime parameter value changed.
type BackendAsyncParameterStatus FromBackend[*pgproto3.ParameterStatus]

func (BackendAsyncParameterStatus) Backend() {}
func (BackendAsyncParameterStatus) Async()   {}

// ToBackendAsync converts a pgproto3.BackendMessage to a BackendAsync if it matches one of the known types.
func ToBackendAsync(msg pgproto3.BackendMessage) (BackendAsync, bool) {
	switch m := msg.(type) {
	case *pgproto3.NoticeResponse:
		return BackendAsyncNoticeResponse{m}, true
	case *pgproto3.NotificationResponse:
		return BackendAsyncNotificationResponse{m}, true
	case *pgproto3.ParameterStatus:
		return BackendAsyncParameterStatus{m}, true
	}
	return nil, false
}
