// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// BackendResponse is implemented by all Backend Response message wrapper types.
type BackendResponse interface {
	Backend()
	Response()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ BackendResponse = BackendResponseReadyForQuery{}
	_ BackendResponse = BackendResponseCommandComplete{}
	_ BackendResponse = BackendResponseDataRow{}
	_ BackendResponse = BackendResponseEmptyQueryResponse{}
	_ BackendResponse = BackendResponseErrorResponse{}
	_ BackendResponse = BackendResponseFunctionCallResponse{}
)

// Start-up completed.
// Simple Query mode: ready for next query.
// Extended Query mode: response to Sync; backend no longer ignoring messages, ready for next command.
type BackendResponseReadyForQuery FromBackend[*pgproto3.ReadyForQuery]

func (BackendResponseReadyForQuery) Backend()  {}
func (BackendResponseReadyForQuery) Response() {}

// SQL command completed normally.
type BackendResponseCommandComplete FromBackend[*pgproto3.CommandComplete]

func (BackendResponseCommandComplete) Backend()  {}
func (BackendResponseCommandComplete) Response() {}

// Query results (both query modes)
type BackendResponseDataRow FromBackend[*pgproto3.DataRow]

func (BackendResponseDataRow) Backend()  {}
func (BackendResponseDataRow) Response() {}

// Response to empty query.
type BackendResponseEmptyQueryResponse FromBackend[*pgproto3.EmptyQueryResponse]

func (BackendResponseEmptyQueryResponse) Backend()  {}
func (BackendResponseEmptyQueryResponse) Response() {}

// Error response.
type BackendResponseErrorResponse FromBackend[*pgproto3.ErrorResponse]

func (BackendResponseErrorResponse) Backend()  {}
func (BackendResponseErrorResponse) Response() {}

// Response to function call.
type BackendResponseFunctionCallResponse FromBackend[*pgproto3.FunctionCallResponse]

func (BackendResponseFunctionCallResponse) Backend()  {}
func (BackendResponseFunctionCallResponse) Response() {}

// ToBackendResponse converts a pgproto3.BackendMessage to a BackendResponse if it matches one of the known types.
func ToBackendResponse(msg pgproto3.BackendMessage) (BackendResponse, bool) {
	switch m := msg.(type) {
	case *pgproto3.ReadyForQuery:
		return BackendResponseReadyForQuery{m}, true
	case *pgproto3.CommandComplete:
		return BackendResponseCommandComplete{m}, true
	case *pgproto3.DataRow:
		return BackendResponseDataRow{m}, true
	case *pgproto3.EmptyQueryResponse:
		return BackendResponseEmptyQueryResponse{m}, true
	case *pgproto3.ErrorResponse:
		return BackendResponseErrorResponse{m}, true
	case *pgproto3.FunctionCallResponse:
		return BackendResponseFunctionCallResponse{m}, true
	}
	return nil, false
}
