// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// BackendExtendedQuery is implemented by all Backend ExtendedQuery message wrapper types.
type BackendExtendedQuery interface {
	Backend()
	ExtendedQuery()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ BackendExtendedQuery = BackendExtendedQueryParseComplete{}
	_ BackendExtendedQuery = BackendExtendedQueryBindComplete{}
	_ BackendExtendedQuery = BackendExtendedQueryParameterDescription{}
	_ BackendExtendedQuery = BackendExtendedQueryRowDescription{}
	_ BackendExtendedQuery = BackendExtendedQueryNoData{}
	_ BackendExtendedQuery = BackendExtendedQueryPortalSuspended{}
	_ BackendExtendedQuery = BackendExtendedQueryCloseComplete{}
)

// Response to Parse.
type BackendExtendedQueryParseComplete FromBackend[*pgproto3.ParseComplete]

func (BackendExtendedQueryParseComplete) Backend()       {}
func (BackendExtendedQueryParseComplete) ExtendedQuery() {}

// Response to Bind.
type BackendExtendedQueryBindComplete FromBackend[*pgproto3.BindComplete]

func (BackendExtendedQueryBindComplete) Backend()       {}
func (BackendExtendedQueryBindComplete) ExtendedQuery() {}

// Response to Describe of prepared statemnt
type BackendExtendedQueryParameterDescription FromBackend[*pgproto3.ParameterDescription]

func (BackendExtendedQueryParameterDescription) Backend()       {}
func (BackendExtendedQueryParameterDescription) ExtendedQuery() {}

// Response to Describe of portal or statement that returns data.
type BackendExtendedQueryRowDescription FromBackend[*pgproto3.RowDescription]

func (BackendExtendedQueryRowDescription) Backend()       {}
func (BackendExtendedQueryRowDescription) ExtendedQuery() {}

// Response to Describe of portal or statement that doesn't return data.
type BackendExtendedQueryNoData FromBackend[*pgproto3.NoData]

func (BackendExtendedQueryNoData) Backend()       {}
func (BackendExtendedQueryNoData) ExtendedQuery() {}

// Response to Execute if there are additional rows / the execute did not
// complete during the Execute call, the client should call Execute again.
type BackendExtendedQueryPortalSuspended FromBackend[*pgproto3.PortalSuspended]

func (BackendExtendedQueryPortalSuspended) Backend()       {}
func (BackendExtendedQueryPortalSuspended) ExtendedQuery() {}

// Response to Close of prepared statement or portal.
type BackendExtendedQueryCloseComplete FromBackend[*pgproto3.CloseComplete]

func (BackendExtendedQueryCloseComplete) Backend()       {}
func (BackendExtendedQueryCloseComplete) ExtendedQuery() {}

// ToBackendExtendedQuery converts a pgproto3.BackendMessage to a BackendExtendedQuery if it matches one of the known types.
func ToBackendExtendedQuery(msg pgproto3.BackendMessage) (BackendExtendedQuery, bool) {
	switch m := msg.(type) {
	case *pgproto3.ParseComplete:
		return BackendExtendedQueryParseComplete{m}, true
	case *pgproto3.BindComplete:
		return BackendExtendedQueryBindComplete{m}, true
	case *pgproto3.ParameterDescription:
		return BackendExtendedQueryParameterDescription{m}, true
	case *pgproto3.RowDescription:
		return BackendExtendedQueryRowDescription{m}, true
	case *pgproto3.NoData:
		return BackendExtendedQueryNoData{m}, true
	case *pgproto3.PortalSuspended:
		return BackendExtendedQueryPortalSuspended{m}, true
	case *pgproto3.CloseComplete:
		return BackendExtendedQueryCloseComplete{m}, true
	}
	return nil, false
}
