// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ClientTerminateConn is implemented by all Client TerminateConn message wrapper types.
type ClientTerminateConn interface {
	TerminateConn()
	PgwireMessage() pgproto3.Message
	Client() pgproto3.FrontendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ClientTerminateConn = ClientTerminateConnTerminate{}
)

// ClientTerminateConnTerminate wraps *pgproto3.Terminate from the client.
type ClientTerminateConnTerminate FromClient[*pgproto3.Terminate]

func (ClientTerminateConnTerminate) TerminateConn()                     {}
func (t ClientTerminateConnTerminate) PgwireMessage() pgproto3.Message  { return t.T }
func (t ClientTerminateConnTerminate) Client() pgproto3.FrontendMessage { return t.T }

// ToClientTerminateConn converts a pgproto3.FrontendMessage to a ClientTerminateConn if it matches one of the known types.
func ToClientTerminateConn(msg pgproto3.FrontendMessage) (ClientTerminateConn, bool) {
	switch m := msg.(type) {
	case *pgproto3.Terminate:
		return ClientTerminateConnTerminate{m}, true
	}
	return nil, false
}
