// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ClientCopy is implemented by all Client Copy message wrapper types.
type ClientCopy interface {
	Copy()
	PgwireMessage() pgproto3.Message
	Client() pgproto3.FrontendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ClientCopy = ClientCopyCopyData{}
	_ ClientCopy = ClientCopyCopyDone{}
	_ ClientCopy = ClientCopyCopyFail{}
)

// ClientCopyCopyData wraps *pgproto3.CopyData from the client.
type ClientCopyCopyData FromClient[*pgproto3.CopyData]

func (ClientCopyCopyData) Copy()                              {}
func (t ClientCopyCopyData) PgwireMessage() pgproto3.Message  { return t.T }
func (t ClientCopyCopyData) Client() pgproto3.FrontendMessage { return t.T }

// ClientCopyCopyDone wraps *pgproto3.CopyDone from the client.
type ClientCopyCopyDone FromClient[*pgproto3.CopyDone]

func (ClientCopyCopyDone) Copy()                              {}
func (t ClientCopyCopyDone) PgwireMessage() pgproto3.Message  { return t.T }
func (t ClientCopyCopyDone) Client() pgproto3.FrontendMessage { return t.T }

// ClientCopyCopyFail wraps *pgproto3.CopyFail from the client.
type ClientCopyCopyFail FromClient[*pgproto3.CopyFail]

func (ClientCopyCopyFail) Copy()                              {}
func (t ClientCopyCopyFail) PgwireMessage() pgproto3.Message  { return t.T }
func (t ClientCopyCopyFail) Client() pgproto3.FrontendMessage { return t.T }

// ToClientCopy converts a pgproto3.FrontendMessage to a ClientCopy if it matches one of the known types.
func ToClientCopy(msg pgproto3.FrontendMessage) (ClientCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyData:
		return ClientCopyCopyData{m}, true
	case *pgproto3.CopyDone:
		return ClientCopyCopyDone{m}, true
	case *pgproto3.CopyFail:
		return ClientCopyCopyFail{m}, true
	}
	return nil, false
}
