// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ClientStartup is implemented by all Client Startup message wrapper types.
type ClientStartup interface {
	Client()
	Startup()
	PgwireMessage()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ClientStartup = ClientStartupGSSEncRequest{}
	_ ClientStartup = ClientStartupGSSResponse{}
	_ ClientStartup = ClientStartupPasswordMessage{}
	_ ClientStartup = ClientStartupSASLInitialResponse{}
	_ ClientStartup = ClientStartupSASLResponse{}
	_ ClientStartup = ClientStartupSSLRequest{}
	_ ClientStartup = ClientStartupStartupMessage{}
)

// ClientStartupGSSEncRequest wraps *pgproto3.GSSEncRequest from the client.
type ClientStartupGSSEncRequest FromClient[*pgproto3.GSSEncRequest]

func (ClientStartupGSSEncRequest) Client()        {}
func (ClientStartupGSSEncRequest) Startup()       {}
func (ClientStartupGSSEncRequest) PgwireMessage() {}

// ClientStartupGSSResponse wraps *pgproto3.GSSResponse from the client.
type ClientStartupGSSResponse FromClient[*pgproto3.GSSResponse]

func (ClientStartupGSSResponse) Client()        {}
func (ClientStartupGSSResponse) Startup()       {}
func (ClientStartupGSSResponse) PgwireMessage() {}

// ClientStartupPasswordMessage wraps *pgproto3.PasswordMessage from the client.
type ClientStartupPasswordMessage FromClient[*pgproto3.PasswordMessage]

func (ClientStartupPasswordMessage) Client()        {}
func (ClientStartupPasswordMessage) Startup()       {}
func (ClientStartupPasswordMessage) PgwireMessage() {}

// ClientStartupSASLInitialResponse wraps *pgproto3.SASLInitialResponse from the client.
type ClientStartupSASLInitialResponse FromClient[*pgproto3.SASLInitialResponse]

func (ClientStartupSASLInitialResponse) Client()        {}
func (ClientStartupSASLInitialResponse) Startup()       {}
func (ClientStartupSASLInitialResponse) PgwireMessage() {}

// ClientStartupSASLResponse wraps *pgproto3.SASLResponse from the client.
type ClientStartupSASLResponse FromClient[*pgproto3.SASLResponse]

func (ClientStartupSASLResponse) Client()        {}
func (ClientStartupSASLResponse) Startup()       {}
func (ClientStartupSASLResponse) PgwireMessage() {}

// ClientStartupSSLRequest wraps *pgproto3.SSLRequest from the client.
type ClientStartupSSLRequest FromClient[*pgproto3.SSLRequest]

func (ClientStartupSSLRequest) Client()        {}
func (ClientStartupSSLRequest) Startup()       {}
func (ClientStartupSSLRequest) PgwireMessage() {}

// ClientStartupStartupMessage wraps *pgproto3.StartupMessage from the client.
type ClientStartupStartupMessage FromClient[*pgproto3.StartupMessage]

func (ClientStartupStartupMessage) Client()        {}
func (ClientStartupStartupMessage) Startup()       {}
func (ClientStartupStartupMessage) PgwireMessage() {}

// ToClientStartup converts a pgproto3.FrontendMessage to a ClientStartup if it matches one of the known types.
func ToClientStartup(msg pgproto3.FrontendMessage) (ClientStartup, bool) {
	switch m := msg.(type) {
	case *pgproto3.GSSEncRequest:
		return ClientStartupGSSEncRequest{m}, true
	case *pgproto3.GSSResponse:
		return ClientStartupGSSResponse{m}, true
	case *pgproto3.PasswordMessage:
		return ClientStartupPasswordMessage{m}, true
	case *pgproto3.SASLInitialResponse:
		return ClientStartupSASLInitialResponse{m}, true
	case *pgproto3.SASLResponse:
		return ClientStartupSASLResponse{m}, true
	case *pgproto3.SSLRequest:
		return ClientStartupSSLRequest{m}, true
	case *pgproto3.StartupMessage:
		return ClientStartupStartupMessage{m}, true
	}
	return nil, false
}
