// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"fmt"
	"io"

	"github.com/jackc/pgx/v5/pgproto3"
)

// ClientCancel is implemented by all Client Cancel message wrapper types.
type ClientCancel interface {
	Cancel()
	PgwireMessage() pgproto3.Message
	Client() pgproto3.FrontendMessage
	Raw() RawBody
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ClientCancel = ClientCancelCancelRequest{}
)

// ClientCancelCancelRequest wraps *pgproto3.CancelRequest from the client.
type ClientCancelCancelRequest LazyClient[*pgproto3.CancelRequest]

func (ClientCancelCancelRequest) Cancel() {}
func (t ClientCancelCancelRequest) PgwireMessage() pgproto3.Message {
	return (*LazyClient[*pgproto3.CancelRequest])(&t).Parse()
}
func (t ClientCancelCancelRequest) Client() pgproto3.FrontendMessage {
	return (*LazyClient[*pgproto3.CancelRequest])(&t).Parse()
}
func (m ClientCancelCancelRequest) Raw() RawBody { return LazyClient[*pgproto3.CancelRequest](m).Raw() }
func (m *ClientCancelCancelRequest) Parse() *pgproto3.CancelRequest {
	return (*LazyClient[*pgproto3.CancelRequest])(m).Parse()
}
func (m ClientCancelCancelRequest) IsParsed() bool {
	return LazyClient[*pgproto3.CancelRequest](m).IsParsed()
}
func (m ClientCancelCancelRequest) Body() []byte {
	return LazyClient[*pgproto3.CancelRequest](m).Body()
}
func (m *ClientCancelCancelRequest) WriteTo(w io.Writer) (int64, error) {
	return (*LazyClient[*pgproto3.CancelRequest])(m).WriteTo(w)
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ClientCancelCancelRequest) Retain() ClientCancelCancelRequest {
	src, parsed, isParsed := (*LazyClient[*pgproto3.CancelRequest])(&m).retainFields()
	return ClientCancelCancelRequest{source: src, parsed: parsed, isParsed: isParsed}
}

// ToClientCancel converts a pgproto3.FrontendMessage to a ClientCancel if it matches one of the known types.
func ToClientCancel(msg pgproto3.FrontendMessage) (ClientCancel, bool) {
	switch m := msg.(type) {
	case *pgproto3.CancelRequest:
		return ClientCancelCancelRequest(NewLazyClientFromParsed(m)), true
	}
	return nil, false
}

// ClientCancelHandlers provides type-safe handlers for each ClientCancel variant.
type ClientCancelHandlers[T any] struct {
	CancelRequest func(msg ClientCancelCancelRequest) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ClientCancelHandlers[T]) HandleDefault(msg ClientCancel, defaultHandler func(msg ClientCancel) (T, error)) (r T, err error) {
	switch msg := msg.(type) {
	case ClientCancelCancelRequest:
		if h.CancelRequest != nil {
			return h.CancelRequest(msg)
		} else {
			return defaultHandler(msg)
		}
	}
	err = fmt.Errorf("unknown client cancel message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ClientCancelHandlers[T]) Handle(msg ClientCancel) (T, error) {
	return h.HandleDefault(msg, func(msg ClientCancel) (T, error) {
		panic(fmt.Sprintf("no handler defined for client cancel message: %T", msg))
	})
}
