// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ClientCancel is implemented by all Client Cancel message wrapper types.
type ClientCancel interface {
	Cancel()
	PgwireMessage() pgproto3.Message
	Client() pgproto3.FrontendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ClientCancel = ClientCancelCancelRequest{}
)

// ClientCancelCancelRequest wraps *pgproto3.CancelRequest from the client.
type ClientCancelCancelRequest FromClient[*pgproto3.CancelRequest]

func (ClientCancelCancelRequest) Cancel()                            {}
func (t ClientCancelCancelRequest) PgwireMessage() pgproto3.Message  { return t.T }
func (t ClientCancelCancelRequest) Client() pgproto3.FrontendMessage { return t.T }

// ToClientCancel converts a pgproto3.FrontendMessage to a ClientCancel if it matches one of the known types.
func ToClientCancel(msg pgproto3.FrontendMessage) (ClientCancel, bool) {
	switch m := msg.(type) {
	case *pgproto3.CancelRequest:
		return ClientCancelCancelRequest{m}, true
	}
	return nil, false
}
