// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// FrontendTerminateConn is implemented by all Frontend TerminateConn message wrapper types.
type FrontendTerminateConn interface {
	Frontend()
	TerminateConn()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ FrontendTerminateConn = FrontendTerminateConnTerminate{}
)

// FrontendTerminateConnTerminate wraps *pgproto3.Terminate from the frontend.
type FrontendTerminateConnTerminate FromFrontend[*pgproto3.Terminate]

func (FrontendTerminateConnTerminate) Frontend()      {}
func (FrontendTerminateConnTerminate) TerminateConn() {}

// ToFrontendTerminateConn converts a pgproto3.FrontendMessage to a FrontendTerminateConn if it matches one of the known types.
func ToFrontendTerminateConn(msg pgproto3.FrontendMessage) (FrontendTerminateConn, bool) {
	switch m := msg.(type) {
	case *pgproto3.Terminate:
		return FrontendTerminateConnTerminate{m}, true
	}
	return nil, false
}
