// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// FrontendSimpleQuery is implemented by all Frontend SimpleQuery message wrapper types.
type FrontendSimpleQuery interface {
	Frontend()
	SimpleQuery()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ FrontendSimpleQuery = FrontendSimpleQueryQuery{}
	_ FrontendSimpleQuery = FrontendSimpleQueryFunctionCall{}
)

// Simple query.
// Destroys unnamed prepared statement & portal.
type FrontendSimpleQueryQuery FromFrontend[*pgproto3.Query]

func (FrontendSimpleQueryQuery) Frontend()    {}
func (FrontendSimpleQueryQuery) SimpleQuery() {}

// Call a function; seems to work like a simple query? Or maybe it works with both modes?
type FrontendSimpleQueryFunctionCall FromFrontend[*pgproto3.FunctionCall]

func (FrontendSimpleQueryFunctionCall) Frontend()    {}
func (FrontendSimpleQueryFunctionCall) SimpleQuery() {}

// ToFrontendSimpleQuery converts a pgproto3.FrontendMessage to a FrontendSimpleQuery if it matches one of the known types.
func ToFrontendSimpleQuery(msg pgproto3.FrontendMessage) (FrontendSimpleQuery, bool) {
	switch m := msg.(type) {
	case *pgproto3.Query:
		return FrontendSimpleQueryQuery{m}, true
	case *pgproto3.FunctionCall:
		return FrontendSimpleQueryFunctionCall{m}, true
	}
	return nil, false
}
