// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// FrontendCopy is implemented by all Frontend Copy message wrapper types.
type FrontendCopy interface {
	Frontend()
	Copy()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ FrontendCopy = FrontendCopyCopyData{}
	_ FrontendCopy = FrontendCopyCopyDone{}
	_ FrontendCopy = FrontendCopyCopyFail{}
)

// FrontendCopyCopyData wraps *pgproto3.CopyData from the frontend.
type FrontendCopyCopyData FromFrontend[*pgproto3.CopyData]

func (FrontendCopyCopyData) Frontend() {}
func (FrontendCopyCopyData) Copy()     {}

// FrontendCopyCopyDone wraps *pgproto3.CopyDone from the frontend.
type FrontendCopyCopyDone FromFrontend[*pgproto3.CopyDone]

func (FrontendCopyCopyDone) Frontend() {}
func (FrontendCopyCopyDone) Copy()     {}

// FrontendCopyCopyFail wraps *pgproto3.CopyFail from the frontend.
type FrontendCopyCopyFail FromFrontend[*pgproto3.CopyFail]

func (FrontendCopyCopyFail) Frontend() {}
func (FrontendCopyCopyFail) Copy()     {}

// ToFrontendCopy converts a pgproto3.FrontendMessage to a FrontendCopy if it matches one of the known types.
func ToFrontendCopy(msg pgproto3.FrontendMessage) (FrontendCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyData:
		return FrontendCopyCopyData{m}, true
	case *pgproto3.CopyDone:
		return FrontendCopyCopyDone{m}, true
	case *pgproto3.CopyFail:
		return FrontendCopyCopyFail{m}, true
	}
	return nil, false
}
