//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/justjake/pglink/pkg/pgwire"
)

// Templates for code generation. Edit these to change generated output.
const fileTemplate = `// Code generated by generate_msg.go; DO NOT EDIT.
//go:generate go run generate_msg.go

package pgwire

import (
	"fmt"
	"io"

	"github.com/jackc/pgx/v5/pgproto3"
)

{{range .ClientMsgs}}{{template "typedMsg" .}}{{end}}
{{range .ServerMsgs}}{{template "typedMsg" .}}{{end}}
{{template "unknownMsg" .}}
{{template "typedFunc" .}}
`

const typedMsgTemplate = `{{define "typedMsg"}}
// {{.TypeName}} is a {{.Sender}}{{.KindDesc}} message.
{{- if .IsRequest}}
// Responses: {{.ResponseList}}.
{{- end}}
{{- if .IsResponse}}
// Response to {{.RespondsToList}}.
{{- end}}
{{- if .IsStartup}}
// Startup messages only appear before the first [ReadyForQuery] response.
{{- end}}
type {{.TypeName}} Msg

func (m {{.TypeName}}) String() string { return fmt.Sprintf("{{.TypeName}}(%v)", Msg(m)) }
func (m {{.TypeName}}) ExpectedType() MsgType { return {{.ConstName}} }
func (m {{.TypeName}}) CopyTyped() {{.TypeName}} { return {{.TypeName}}(m.Msg().Copy()) }
func (m {{.TypeName}}) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}

{{- if eq .Sender "client"}}
func (m {{.TypeName}}) ExpectedFrom() Sender { return SenderClient }
func (m {{.TypeName}}) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m {{.TypeName}}) CopyClient() ClientMsg { return m.CopyTyped() }
{{- else}}
func (m {{.TypeName}}) ExpectedFrom() Sender { return SenderServer }
func (m {{.TypeName}}) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m {{.TypeName}}) CopyServer() ServerMsg { return m.CopyTyped() }
{{- end}}

func (m {{.TypeName}}) From() Sender { return Msg(m).Sender }
func (m {{.TypeName}}) Msg() Msg { return Msg(m) }
func (m {{.TypeName}}) Copy() TypedMsg { return m.CopyTyped() }

{{- if .HasParse}}
func (m {{.TypeName}}) Parse() (out pgproto3.{{.ProtoTypeName}}, err error) {
	return DecodeMsg[pgproto3.{{.ProtoTypeName}}](m.Msg())
}
func (m {{.TypeName}}) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}
{{- else}}
func (m {{.TypeName}}) ParseAny() (pgproto3.Message, error) {
	return nil, fmt.Errorf("{{.TypeName}} has no single pgproto3 equivalent")
}
{{- end}}

{{range $.Methods}}func (m {{$.TypeName}}) {{.Name}}({{.Params}}) {{.Returns}} { {{if .Returns}}return {{end}}Msg(m).{{.Name}}({{.CallArgs}}) }
{{end}}
{{- if eq .Sender "client"}}
var _ ClientMsg = {{.TypeName}}{}
{{- else}}
var _ ServerMsg = {{.TypeName}}{}
{{- end}}
{{end}}`

const unknownMsgTemplate = `{{define "unknownMsg"}}
// UnknownMsg wraps a message with an unrecognized type byte.
type UnknownMsg Msg

func (m UnknownMsg) String() string { return fmt.Sprintf("UnknownMsg(%v)", Msg(m)) }
func (m UnknownMsg) ExpectedType() MsgType { return 0 }
func (m UnknownMsg) CopyTyped() UnknownMsg { return UnknownMsg(m.Msg().Copy()) }
func (m UnknownMsg) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	return ErrMsgGoTypeMismatch
}

func (m UnknownMsg) From() Sender { return Msg(m).Sender }
func (m UnknownMsg) Msg() Msg { return Msg(m) }
func (m UnknownMsg) Copy() TypedMsg { return m.CopyTyped() }
func (m UnknownMsg) ParseAny() (pgproto3.Message, error) {
	return nil, fmt.Errorf("UnknownMsg cannot be parsed")
}

{{range .Methods}}func (m UnknownMsg) {{.Name}}({{.Params}}) {{.Returns}} { {{if .Returns}}return {{end}}Msg(m).{{.Name}}({{.CallArgs}}) }
{{end}}
var _ TypedMsg = UnknownMsg{}
{{end}}`

const typedFuncTemplate = `{{define "typedFunc"}}
// Typed converts a Msg to its specific TypedMsg wrapper based on Sender and MessageType.
// Returns the concrete type (e.g., Bind, Query, DataRow) based on the wire type byte.
// Returns UnknownMsg if the type byte is not recognized for the sender.
//
// The switch is ordered by MsgParsePriority for hot-path optimization:
// most frequent message types are checked first, and unambiguous types
// (unique to client or server) return immediately without checking Sender.
func Typed(m Msg) TypedMsg {
	switch m.MessageType() {
{{- range .SwitchCases}}
	case {{.ConstName}}: {{if .Comment}}// {{.Comment}}{{end}}
{{- if .IsAmbiguous}}
		if m.Sender == SenderClient {
			return {{.ClientTypeName}}(m)
		}
		return {{.ServerTypeName}}(m)
{{- else}}
		return {{.TypeName}}(m)
{{- end}}
{{- end}}
	}
	return UnknownMsg(m)
}
{{end}}`

func main() {
	dir := "."
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	// Parse source files
	fset := token.NewFileSet()

	// Parse raw.go for RawMessageSource interface (need method signatures for delegation)
	rawFile, err := parser.ParseFile(fset, filepath.Join(dir, "raw.go"), nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse raw.go: %v", err)
	}

	methods := extractInterfaceMethods(fset, rawFile, "RawMessageSource")
	if len(methods) == 0 {
		log.Fatal("no methods found in RawMessageSource interface")
	}

	// Parse msg_type.go for const names (we need to map type bytes to const names like "MsgClientBind")
	msgTypeFile, err := parser.ParseFile(fset, filepath.Join(dir, "msg_type.go"), nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse msg_type.go: %v", err)
	}

	// Extract const name mappings: type byte -> const name
	clientConsts := extractMsgConsts(fset, msgTypeFile, "MsgClient")
	serverConsts := extractMsgConsts(fset, msgTypeFile, "MsgServer")
	startupConsts := extractStartupConsts(fset, msgTypeFile)

	// Build message entries from pgwire lookups + const names
	clientMsgs := buildMsgEntries(&pgwire.ClientMsgName, clientConsts, startupConsts)
	serverMsgs := buildMsgEntries(&pgwire.ServerMsgName, serverConsts, startupConsts)

	if len(clientMsgs) == 0 {
		log.Fatal("no entries found in ClientMsgName")
	}
	if len(serverMsgs) == 0 {
		log.Fatal("no entries found in ServerMsgName")
	}

	// Handle duplicate names (e.g., CopyData, CopyDone appear in both client and server)
	// Duplicates get prefixed: ClientCopyData, ServerCopyData
	clientMsgs, serverMsgs = resolveDuplicateNames(clientMsgs, serverMsgs)

	// Build metadata for doc comments using pgwire lookups directly
	meta := buildMsgMetadata(clientMsgs, serverMsgs)

	// Generate the code
	output := generateCode(methods, clientMsgs, serverMsgs, meta, pgwire.MsgParsePriority)

	// Write output
	outPath := filepath.Join(dir, "typed_msg_generated.go")
	if err := os.WriteFile(outPath, output, 0644); err != nil {
		log.Fatalf("failed to write %s: %v", outPath, err)
	}

	fmt.Printf("Generated %s with %d client, %d server types\n",
		outPath, len(clientMsgs), len(serverMsgs))
}

// methodInfo holds information about an interface method
type methodInfo struct {
	name    string
	params  string // e.g., "buf []byte"
	returns string // e.g., "([]byte, error)"
}

// msgEntry holds information about a message type entry
type msgEntry struct {
	msgType   pgwire.MsgType // e.g., pgwire.MsgClientBind
	name      string         // e.g., "Bind"
	constName string         // e.g., "MsgClientBind"
}

// msgMetadata holds doc comment info for a message type
type msgMetadata struct {
	isRequest  bool             // has entries in MsgResponse
	isResponse bool             // appears as a response in MsgResponse
	responses  []pgwire.MsgType // response message types (if request)
	respondsTo []pgwire.MsgType // request types this responds to
	// Note: isStartup is computed in generateTypedMsg, not stored here,
	// because ambiguous types like 'S' need sender-specific handling.
}

func extractInterfaceMethods(fset *token.FileSet, file *ast.File, interfaceName string) []methodInfo {
	var methods []methodInfo

	ast.Inspect(file, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok || typeSpec.Name.Name != interfaceName {
			return true
		}

		iface, ok := typeSpec.Type.(*ast.InterfaceType)
		if !ok {
			return true
		}

		for _, method := range iface.Methods.List {
			if len(method.Names) == 0 {
				continue // embedded interface
			}

			funcType, ok := method.Type.(*ast.FuncType)
			if !ok {
				continue
			}

			mi := methodInfo{
				name: method.Names[0].Name,
			}

			// Extract params
			if funcType.Params != nil && len(funcType.Params.List) > 0 {
				var params []string
				for _, p := range funcType.Params.List {
					var buf bytes.Buffer
					printer.Fprint(&buf, fset, p.Type)
					typeStr := buf.String()
					for _, name := range p.Names {
						params = append(params, name.Name+" "+typeStr)
					}
					if len(p.Names) == 0 {
						params = append(params, typeStr)
					}
				}
				mi.params = strings.Join(params, ", ")
			}

			// Extract returns
			if funcType.Results != nil && len(funcType.Results.List) > 0 {
				var returns []string
				for _, r := range funcType.Results.List {
					var buf bytes.Buffer
					printer.Fprint(&buf, fset, r.Type)
					returns = append(returns, buf.String())
				}
				if len(returns) == 1 {
					mi.returns = returns[0]
				} else {
					mi.returns = "(" + strings.Join(returns, ", ") + ")"
				}
			}

			methods = append(methods, mi)
		}

		return false
	})

	return methods
}

// extractMsgConsts extracts const declarations like MsgClientBind, MsgServerAuth
// Returns a map from type byte (e.g., "'B'") to const name (e.g., "MsgClientBind")
func extractMsgConsts(fset *token.FileSet, file *ast.File, prefix string) map[string]string {
	consts := make(map[string]string)

	ast.Inspect(file, func(n ast.Node) bool {
		genDecl, ok := n.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			return true
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) == 0 {
				continue
			}

			name := valueSpec.Names[0].Name
			if !strings.HasPrefix(name, prefix) {
				continue
			}

			if len(valueSpec.Values) == 0 {
				continue
			}

			// Get the value (type byte)
			var valBuf bytes.Buffer
			printer.Fprint(&valBuf, fset, valueSpec.Values[0])
			valStr := valBuf.String()

			consts[valStr] = name
		}

		return true
	})

	return consts
}

// extractStartupConsts extracts startup message consts (MsgStartup, MsgSSLRequest, etc.)
func extractStartupConsts(fset *token.FileSet, file *ast.File) map[string]string {
	consts := make(map[string]string)

	ast.Inspect(file, func(n ast.Node) bool {
		genDecl, ok := n.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			return true
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) == 0 {
				continue
			}

			name := valueSpec.Names[0].Name
			// Look for MsgStartup, MsgSSLRequest, MsgCancelRequest, MsgGSSENCRequest
			if !strings.HasPrefix(name, "Msg") || strings.HasPrefix(name, "MsgClient") || strings.HasPrefix(name, "MsgServer") {
				continue
			}

			if len(valueSpec.Values) == 0 {
				continue
			}

			// Get the value (type byte like 0x00, 0x01, etc.)
			var valBuf bytes.Buffer
			printer.Fprint(&valBuf, fset, valueSpec.Values[0])
			valStr := valBuf.String()

			consts[valStr] = name
		}

		return true
	})

	return consts
}

// buildMsgEntries builds msgEntry list from a pgwire.MsgLookup and const name maps.
// senderConsts maps type byte (as printed string like "'B'") to const name.
func buildMsgEntries(lookup *pgwire.MsgLookup[string], senderConsts, startupConsts map[string]string) []msgEntry {
	var entries []msgEntry

	for i := 0; i < 256; i++ {
		msgType := pgwire.MsgType(i)
		name := lookup.Get(msgType)
		if name == "" {
			continue
		}

		// Find const name - try formatting the byte different ways
		var constName string
		if msgType < 32 {
			// Startup messages use hex format: 0x00, 0x01, etc.
			key := fmt.Sprintf("0x%02x", byte(msgType))
			constName = startupConsts[key]
		} else {
			// Regular messages use char format: 'B', 'Q', etc.
			key := fmt.Sprintf("'%c'", byte(msgType))
			constName = senderConsts[key]
			if constName == "" {
				constName = startupConsts[key]
			}
		}

		if constName == "" {
			log.Printf("warning: no const found for MsgType %d (%q) with name %q", msgType, string([]byte{byte(msgType)}), name)
			continue
		}

		entries = append(entries, msgEntry{
			msgType:   msgType,
			name:      name,
			constName: constName,
		})
	}

	// Sort by name for consistent output
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	return entries
}

// resolveDuplicateNames handles message names that appear in both client and server.
// For duplicates (like CopyData, CopyDone), prefix with "Client" or "Server".
// Returns: all client msgs, all server msgs (no separate bidirectional list).
func resolveDuplicateNames(clientMsgs, serverMsgs []msgEntry) (clientAll, serverAll []msgEntry) {
	// Build maps by name
	clientByName := make(map[string]msgEntry)
	for _, e := range clientMsgs {
		clientByName[e.name] = e
	}

	// Find duplicates
	duplicateNames := make(map[string]bool)
	for _, e := range serverMsgs {
		if _, ok := clientByName[e.name]; ok {
			duplicateNames[e.name] = true
		}
	}

	// Build lists, prefixing duplicates
	for _, e := range clientMsgs {
		if duplicateNames[e.name] {
			e.name = "Client" + e.name // e.g., "ClientCopyData"
		}
		clientAll = append(clientAll, e)
	}
	for _, e := range serverMsgs {
		if duplicateNames[e.name] {
			e.name = "Server" + e.name // e.g., "ServerCopyData"
		}
		serverAll = append(serverAll, e)
	}

	return clientAll, serverAll
}

// buildMsgMetadata builds documentation metadata for all messages using pgwire lookups directly.
// The map is keyed by message NAME (not type) because ambiguous types like 'S' have different
// meanings for client (Sync) vs server (ParameterStatus).
func buildMsgMetadata(clientMsgs, serverMsgs []msgEntry) map[string]*msgMetadata {
	meta := make(map[string]*msgMetadata)

	// Build lookup from msgType to entry name, separated by sender.
	// Client types are requests, server types are responses.
	clientByType := make(map[pgwire.MsgType]string)
	serverByType := make(map[pgwire.MsgType]string)

	for _, e := range clientMsgs {
		meta[e.name] = &msgMetadata{}
		clientByType[e.msgType] = e.name
	}
	for _, e := range serverMsgs {
		meta[e.name] = &msgMetadata{}
		serverByType[e.msgType] = e.name
	}

	// Helper to check if slice contains a type
	containsType := func(slice []pgwire.MsgType, t pgwire.MsgType) bool {
		for _, v := range slice {
			if v == t {
				return true
			}
		}
		return false
	}

	// Process request/response relationships.
	// Requests are CLIENT messages in MsgResponse/MsgTerminalResponse.
	// Responses are SERVER messages listed as values in those maps.
	processResponses := func(reqType pgwire.MsgType, respTypes pgwire.MsgTypeSet) {
		// Only client messages can be requests
		reqName, isClientReq := clientByType[reqType]
		if isClientReq {
			m := meta[reqName]
			m.isRequest = true
			for _, respType := range respTypes {
				if !containsType(m.responses, respType) {
					m.responses = append(m.responses, respType)
				}
			}
		}
		// Only server messages can be responses
		for _, respType := range respTypes {
			respName, isServerResp := serverByType[respType]
			if isServerResp {
				m := meta[respName]
				m.isResponse = true
				if !containsType(m.respondsTo, reqType) {
					m.respondsTo = append(m.respondsTo, reqType)
				}
			}
		}
	}

	// Mark requests from MsgTerminalResponse (has all request types with their terminal responses)
	for i := 0; i < 256; i++ {
		msgType := pgwire.MsgType(i)
		responses := pgwire.MsgTerminalResponse.Get(msgType)
		if len(responses) > 0 {
			processResponses(msgType, responses)
		}
	}

	// Mark requests from MsgResponse (may have additional non-terminal responses)
	for i := 0; i < 256; i++ {
		msgType := pgwire.MsgType(i)
		responses := pgwire.MsgResponse.Get(msgType)
		if len(responses) > 0 {
			processResponses(msgType, responses)
		}
	}

	// Note: isStartup is computed in generateTypedMsg based on sender context,
	// not stored in metadata, because ambiguous types like 'S' need sender-specific handling.

	return meta
}

// msgTypeToTypeName maps a MsgType to its generated type name.
// Searches server messages first (responses are server messages).
func msgTypeToTypeName(msgType pgwire.MsgType, clientMsgs, serverMsgs []msgEntry) string {
	for _, e := range serverMsgs {
		if e.msgType == msgType {
			return e.name
		}
	}
	for _, e := range clientMsgs {
		if e.msgType == msgType {
			return e.name
		}
	}
	// Fallback
	return pgwire.MsgName.Get(msgType)
}

// Template data structures

// methodData holds information for template rendering of a method
type methodData struct {
	Name     string
	Params   string
	Returns  string
	CallArgs string
}

// msgData holds all data needed to render a typed message
type msgData struct {
	TypeName       string
	ConstName      string
	Sender         string // "client" or "server"
	KindDesc       string // " request", " response", " startup", or ""
	IsRequest      bool
	IsResponse     bool
	IsStartup      bool
	ResponseList   string // e.g., "[DataRow], [CommandComplete]"
	RespondsToList string // e.g., "[Query], [Execute]"
	HasParse       bool
	ProtoTypeName  string
	Methods        []methodData
}

// switchCaseData holds data for a single case in the Typed() switch
type switchCaseData struct {
	ConstName      string
	Comment        string
	IsAmbiguous    bool
	TypeName       string // for non-ambiguous
	ClientTypeName string // for ambiguous
	ServerTypeName string // for ambiguous
}

// templateData holds all data for the file template
type templateData struct {
	ClientMsgs  []msgData
	ServerMsgs  []msgData
	Methods     []methodData
	SwitchCases []switchCaseData
}

func generateCode(methods []methodInfo, clientMsgs, serverMsgs []msgEntry, meta map[string]*msgMetadata, priority []pgwire.MsgType) []byte {
	// Convert methods to template data
	methodsData := make([]methodData, len(methods))
	for i, m := range methods {
		methodsData[i] = methodData{
			Name:     m.name,
			Params:   m.params,
			Returns:  m.returns,
			CallArgs: buildCallArgs(m.params),
		}
	}

	// Build message data for templates
	clientData := buildMsgDataList(clientMsgs, "client", meta, methodsData, clientMsgs, serverMsgs)
	serverData := buildMsgDataList(serverMsgs, "server", meta, methodsData, clientMsgs, serverMsgs)

	// Build switch cases for Typed() function
	switchCases := buildSwitchCases(clientMsgs, serverMsgs, priority)

	data := templateData{
		ClientMsgs:  clientData,
		ServerMsgs:  serverData,
		Methods:     methodsData,
		SwitchCases: switchCases,
	}

	// Parse and execute templates
	tmpl := template.Must(template.New("file").Parse(fileTemplate))
	template.Must(tmpl.Parse(typedMsgTemplate))
	template.Must(tmpl.Parse(unknownMsgTemplate))
	template.Must(tmpl.Parse(typedFuncTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		log.Fatalf("template execution failed: %v", err)
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("warning: generated code has formatting issues: %v", err)
		log.Printf("unformatted output:\n%s", buf.String())
		return buf.Bytes()
	}
	return formatted
}

func buildCallArgs(params string) string {
	if params == "" {
		return ""
	}
	var callArgs []string
	parts := strings.Split(params, ", ")
	for _, p := range parts {
		nameParts := strings.Split(strings.TrimSpace(p), " ")
		if len(nameParts) > 0 {
			callArgs = append(callArgs, nameParts[0])
		}
	}
	return strings.Join(callArgs, ", ")
}

func buildMsgDataList(entries []msgEntry, sender string, meta map[string]*msgMetadata, methods []methodData, clientMsgs, serverMsgs []msgEntry) []msgData {
	var result []msgData
	for _, entry := range entries {
		result = append(result, buildMsgData(entry, sender, meta, methods, clientMsgs, serverMsgs))
	}
	return result
}

func buildMsgData(entry msgEntry, sender string, meta map[string]*msgMetadata, methods []methodData, clientMsgs, serverMsgs []msgEntry) msgData {
	m := meta[entry.name]

	// Compute isStartup based on sender context
	isStartup := false
	if pgwire.MsgIsStartup.Get(entry.msgType) {
		isClientStartup := entry.msgType < 0x20 || entry.msgType == 'p'
		isServerStartup := entry.msgType >= 0x20 && entry.msgType != 'p'
		if (sender == "client" && isClientStartup) || (sender == "server" && isServerStartup) {
			isStartup = true
		}
	}

	// Build kind description
	var kindDesc string
	if m.isRequest {
		kindDesc = " request"
	} else if m.isResponse {
		kindDesc = " response"
	} else if isStartup {
		kindDesc = " startup"
	}

	// Build response list
	var responseList string
	if m.isRequest && len(m.responses) > 0 {
		var respNames []string
		for _, r := range m.responses {
			name := msgTypeToTypeName(r, clientMsgs, serverMsgs)
			respNames = append(respNames, "["+name+"]")
		}
		responseList = strings.Join(respNames, ", ")
	}

	// Build responds-to list
	var respondsToList string
	if m.isResponse && len(m.respondsTo) > 0 {
		var reqNames []string
		seen := make(map[string]bool)
		for _, r := range m.respondsTo {
			name := msgTypeToTypeName(r, clientMsgs, serverMsgs)
			if !seen[name] {
				reqNames = append(reqNames, "["+name+"]")
				seen[name] = true
			}
		}
		respondsToList = strings.Join(reqNames, ", ")
	}

	// Determine proto type name and whether Parse is enabled
	protoTypeName := entry.name
	if strings.HasPrefix(protoTypeName, "Client") {
		protoTypeName = strings.TrimPrefix(protoTypeName, "Client")
	} else if strings.HasPrefix(protoTypeName, "Server") {
		protoTypeName = strings.TrimPrefix(protoTypeName, "Server")
	}
	hasParse := !pgwire.TypedMsgDisablePgproto3[protoTypeName]

	return msgData{
		TypeName:       entry.name,
		ConstName:      entry.constName,
		Sender:         sender,
		KindDesc:       kindDesc,
		IsRequest:      m.isRequest,
		IsResponse:     m.isResponse,
		IsStartup:      isStartup,
		ResponseList:   responseList,
		RespondsToList: respondsToList,
		HasParse:       hasParse,
		ProtoTypeName:  protoTypeName,
		Methods:        methods,
	}
}

func buildSwitchCases(clientMsgs, serverMsgs []msgEntry, priority []pgwire.MsgType) []switchCaseData {
	// Build lookup maps by MsgType
	clientByType := make(map[pgwire.MsgType]msgEntry)
	for _, e := range clientMsgs {
		clientByType[e.msgType] = e
	}
	serverByType := make(map[pgwire.MsgType]msgEntry)
	for _, e := range serverMsgs {
		serverByType[e.msgType] = e
	}

	// Collect all message types to process, in priority order
	var orderedTypes []pgwire.MsgType
	seenTypes := make(map[pgwire.MsgType]bool)

	// Add priority types first
	for _, mt := range priority {
		if seenTypes[mt] {
			continue
		}
		_, inClient := clientByType[mt]
		_, inServer := serverByType[mt]
		if inClient || inServer {
			orderedTypes = append(orderedTypes, mt)
			seenTypes[mt] = true
		}
	}

	// Add remaining client types
	for _, e := range clientMsgs {
		if !seenTypes[e.msgType] {
			orderedTypes = append(orderedTypes, e.msgType)
			seenTypes[e.msgType] = true
		}
	}

	// Add remaining server types
	for _, e := range serverMsgs {
		if !seenTypes[e.msgType] {
			orderedTypes = append(orderedTypes, e.msgType)
			seenTypes[e.msgType] = true
		}
	}

	// Build switch cases
	var cases []switchCaseData
	handledTypes := make(map[pgwire.MsgType]bool)

	for _, mt := range orderedTypes {
		if handledTypes[mt] {
			continue
		}

		clientEntry, hasClient := clientByType[mt]
		serverEntry, hasServer := serverByType[mt]

		if hasClient && hasServer {
			// Ambiguous
			cases = append(cases, switchCaseData{
				ConstName:      clientEntry.constName,
				Comment:        clientEntry.name + " (client) / " + serverEntry.name + " (server)",
				IsAmbiguous:    true,
				ClientTypeName: clientEntry.name,
				ServerTypeName: serverEntry.name,
			})
			handledTypes[mt] = true
		} else if hasClient {
			cases = append(cases, switchCaseData{
				ConstName: clientEntry.constName,
				TypeName:  clientEntry.name,
			})
			handledTypes[mt] = true
		} else if hasServer {
			cases = append(cases, switchCaseData{
				ConstName: serverEntry.constName,
				TypeName:  serverEntry.name,
			})
			handledTypes[mt] = true
		}
	}

	return cases
}
