// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerStartup is implemented by all Server Startup message wrapper types.
type ServerStartup interface {
	Server()
	Startup()
	MsgType() MsgType
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerStartup = (*ServerStartupAuthenticationCleartextPassword)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationGSS)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationGSSContinue)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationMD5Password)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationOk)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationSASL)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationSASLContinue)(nil)
	_ ServerStartup = (*ServerStartupAuthenticationSASLFinal)(nil)
	_ ServerStartup = (*ServerStartupBackendKeyData)(nil)
)

// ServerStartupAuthenticationCleartextPassword wraps *pgproto3.AuthenticationCleartextPassword from the server.
type ServerStartupAuthenticationCleartextPassword FromServer[*pgproto3.AuthenticationCleartextPassword]

func (*ServerStartupAuthenticationCleartextPassword) Server()  {}
func (*ServerStartupAuthenticationCleartextPassword) Startup() {}
func (t *ServerStartupAuthenticationCleartextPassword) MsgType() MsgType {
	return t.source.MessageType()
}
func (m *ServerStartupAuthenticationCleartextPassword) Parse() *pgproto3.AuthenticationCleartextPassword {
	return (*FromServer[*pgproto3.AuthenticationCleartextPassword])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationCleartextPassword) Retain() ServerStartupAuthenticationCleartextPassword {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationCleartextPassword])(&m).retainFields()
	return ServerStartupAuthenticationCleartextPassword{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationGSS wraps *pgproto3.AuthenticationGSS from the server.
type ServerStartupAuthenticationGSS FromServer[*pgproto3.AuthenticationGSS]

func (*ServerStartupAuthenticationGSS) Server()            {}
func (*ServerStartupAuthenticationGSS) Startup()           {}
func (t *ServerStartupAuthenticationGSS) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationGSS) Parse() *pgproto3.AuthenticationGSS {
	return (*FromServer[*pgproto3.AuthenticationGSS])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationGSS) Retain() ServerStartupAuthenticationGSS {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationGSS])(&m).retainFields()
	return ServerStartupAuthenticationGSS{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationGSSContinue wraps *pgproto3.AuthenticationGSSContinue from the server.
type ServerStartupAuthenticationGSSContinue FromServer[*pgproto3.AuthenticationGSSContinue]

func (*ServerStartupAuthenticationGSSContinue) Server()            {}
func (*ServerStartupAuthenticationGSSContinue) Startup()           {}
func (t *ServerStartupAuthenticationGSSContinue) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationGSSContinue) Parse() *pgproto3.AuthenticationGSSContinue {
	return (*FromServer[*pgproto3.AuthenticationGSSContinue])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationGSSContinue) Retain() ServerStartupAuthenticationGSSContinue {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationGSSContinue])(&m).retainFields()
	return ServerStartupAuthenticationGSSContinue{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationMD5Password wraps *pgproto3.AuthenticationMD5Password from the server.
type ServerStartupAuthenticationMD5Password FromServer[*pgproto3.AuthenticationMD5Password]

func (*ServerStartupAuthenticationMD5Password) Server()            {}
func (*ServerStartupAuthenticationMD5Password) Startup()           {}
func (t *ServerStartupAuthenticationMD5Password) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationMD5Password) Parse() *pgproto3.AuthenticationMD5Password {
	return (*FromServer[*pgproto3.AuthenticationMD5Password])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationMD5Password) Retain() ServerStartupAuthenticationMD5Password {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationMD5Password])(&m).retainFields()
	return ServerStartupAuthenticationMD5Password{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationOk wraps *pgproto3.AuthenticationOk from the server.
type ServerStartupAuthenticationOk FromServer[*pgproto3.AuthenticationOk]

func (*ServerStartupAuthenticationOk) Server()            {}
func (*ServerStartupAuthenticationOk) Startup()           {}
func (t *ServerStartupAuthenticationOk) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationOk) Parse() *pgproto3.AuthenticationOk {
	return (*FromServer[*pgproto3.AuthenticationOk])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationOk) Retain() ServerStartupAuthenticationOk {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationOk])(&m).retainFields()
	return ServerStartupAuthenticationOk{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationSASL wraps *pgproto3.AuthenticationSASL from the server.
type ServerStartupAuthenticationSASL FromServer[*pgproto3.AuthenticationSASL]

func (*ServerStartupAuthenticationSASL) Server()            {}
func (*ServerStartupAuthenticationSASL) Startup()           {}
func (t *ServerStartupAuthenticationSASL) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationSASL) Parse() *pgproto3.AuthenticationSASL {
	return (*FromServer[*pgproto3.AuthenticationSASL])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationSASL) Retain() ServerStartupAuthenticationSASL {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASL])(&m).retainFields()
	return ServerStartupAuthenticationSASL{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationSASLContinue wraps *pgproto3.AuthenticationSASLContinue from the server.
type ServerStartupAuthenticationSASLContinue FromServer[*pgproto3.AuthenticationSASLContinue]

func (*ServerStartupAuthenticationSASLContinue) Server()            {}
func (*ServerStartupAuthenticationSASLContinue) Startup()           {}
func (t *ServerStartupAuthenticationSASLContinue) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationSASLContinue) Parse() *pgproto3.AuthenticationSASLContinue {
	return (*FromServer[*pgproto3.AuthenticationSASLContinue])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationSASLContinue) Retain() ServerStartupAuthenticationSASLContinue {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASLContinue])(&m).retainFields()
	return ServerStartupAuthenticationSASLContinue{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerStartupAuthenticationSASLFinal wraps *pgproto3.AuthenticationSASLFinal from the server.
type ServerStartupAuthenticationSASLFinal FromServer[*pgproto3.AuthenticationSASLFinal]

func (*ServerStartupAuthenticationSASLFinal) Server()            {}
func (*ServerStartupAuthenticationSASLFinal) Startup()           {}
func (t *ServerStartupAuthenticationSASLFinal) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupAuthenticationSASLFinal) Parse() *pgproto3.AuthenticationSASLFinal {
	return (*FromServer[*pgproto3.AuthenticationSASLFinal])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupAuthenticationSASLFinal) Retain() ServerStartupAuthenticationSASLFinal {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASLFinal])(&m).retainFields()
	return ServerStartupAuthenticationSASLFinal{source: src, parsed: parsed, isParsed: isParsed}
}

// Secret key data for cancel requests.
// This should be already captured when we establish the connection.
type ServerStartupBackendKeyData FromServer[*pgproto3.BackendKeyData]

func (*ServerStartupBackendKeyData) Server()            {}
func (*ServerStartupBackendKeyData) Startup()           {}
func (t *ServerStartupBackendKeyData) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerStartupBackendKeyData) Parse() *pgproto3.BackendKeyData {
	return (*FromServer[*pgproto3.BackendKeyData])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerStartupBackendKeyData) Retain() ServerStartupBackendKeyData {
	src, parsed, isParsed := (*FromServer[*pgproto3.BackendKeyData])(&m).retainFields()
	return ServerStartupBackendKeyData{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerStartup converts a pgproto3.BackendMessage to a ServerStartup if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerStartup(msg pgproto3.BackendMessage) (ServerStartup, bool) {
	switch m := msg.(type) {
	case *pgproto3.AuthenticationCleartextPassword:
		return (*ServerStartupAuthenticationCleartextPassword)(ServerParsed(m)), true
	case *pgproto3.AuthenticationGSS:
		return (*ServerStartupAuthenticationGSS)(ServerParsed(m)), true
	case *pgproto3.AuthenticationGSSContinue:
		return (*ServerStartupAuthenticationGSSContinue)(ServerParsed(m)), true
	case *pgproto3.AuthenticationMD5Password:
		return (*ServerStartupAuthenticationMD5Password)(ServerParsed(m)), true
	case *pgproto3.AuthenticationOk:
		return (*ServerStartupAuthenticationOk)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASL:
		return (*ServerStartupAuthenticationSASL)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASLContinue:
		return (*ServerStartupAuthenticationSASLContinue)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASLFinal:
		return (*ServerStartupAuthenticationSASLFinal)(ServerParsed(m)), true
	case *pgproto3.BackendKeyData:
		return (*ServerStartupBackendKeyData)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerStartupHandlers provides type-safe handlers for each ServerStartup variant.
type ServerStartupHandlers[T any] struct {
	Default                         func(msg ServerStartup) (T, error)
	AuthenticationCleartextPassword func(msg *ServerStartupAuthenticationCleartextPassword) (T, error)
	AuthenticationGSS               func(msg *ServerStartupAuthenticationGSS) (T, error)
	AuthenticationGSSContinue       func(msg *ServerStartupAuthenticationGSSContinue) (T, error)
	AuthenticationMD5Password       func(msg *ServerStartupAuthenticationMD5Password) (T, error)
	AuthenticationOk                func(msg *ServerStartupAuthenticationOk) (T, error)
	AuthenticationSASL              func(msg *ServerStartupAuthenticationSASL) (T, error)
	AuthenticationSASLContinue      func(msg *ServerStartupAuthenticationSASLContinue) (T, error)
	AuthenticationSASLFinal         func(msg *ServerStartupAuthenticationSASLFinal) (T, error)
	BackendKeyData                  func(msg *ServerStartupBackendKeyData) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerStartupHandlers[T]) HandleDefault(msg ServerStartup, defaultHandler func(msg ServerStartup) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerStartup) (T, error) {
			panic(fmt.Sprintf("no handler defined for server startup message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerStartupAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(msg)
		}
		return defaultHandler(msg)
	case *ServerStartupBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server startup message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerStartupHandlers[T]) Handle(msg ServerStartup) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerStartupHandlersCtx provides type-safe handlers with context and an argument for each ServerStartup variant.
type ServerStartupHandlersCtx[Arg, Result any] struct {
	Default                         func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error)
	AuthenticationCleartextPassword func(ctx context.Context, msg *ServerStartupAuthenticationCleartextPassword, arg Arg) (Result, error)
	AuthenticationGSS               func(ctx context.Context, msg *ServerStartupAuthenticationGSS, arg Arg) (Result, error)
	AuthenticationGSSContinue       func(ctx context.Context, msg *ServerStartupAuthenticationGSSContinue, arg Arg) (Result, error)
	AuthenticationMD5Password       func(ctx context.Context, msg *ServerStartupAuthenticationMD5Password, arg Arg) (Result, error)
	AuthenticationOk                func(ctx context.Context, msg *ServerStartupAuthenticationOk, arg Arg) (Result, error)
	AuthenticationSASL              func(ctx context.Context, msg *ServerStartupAuthenticationSASL, arg Arg) (Result, error)
	AuthenticationSASLContinue      func(ctx context.Context, msg *ServerStartupAuthenticationSASLContinue, arg Arg) (Result, error)
	AuthenticationSASLFinal         func(ctx context.Context, msg *ServerStartupAuthenticationSASLFinal, arg Arg) (Result, error)
	BackendKeyData                  func(ctx context.Context, msg *ServerStartupBackendKeyData, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerStartupHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerStartup, arg Arg, defaultHandler func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server startup message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerStartupAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server startup message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerStartupHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerStartup, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerExtendedQuery is implemented by all Server ExtendedQuery message wrapper types.
type ServerExtendedQuery interface {
	Server()
	ExtendedQuery()
	MsgType() MsgType
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerExtendedQuery = (*ServerExtendedQueryParseComplete)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryBindComplete)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryParameterDescription)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryRowDescription)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryNoData)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryPortalSuspended)(nil)
	_ ServerExtendedQuery = (*ServerExtendedQueryCloseComplete)(nil)
)

// Response to Parse.
type ServerExtendedQueryParseComplete FromServer[*pgproto3.ParseComplete]

func (*ServerExtendedQueryParseComplete) Server()            {}
func (*ServerExtendedQueryParseComplete) ExtendedQuery()     {}
func (t *ServerExtendedQueryParseComplete) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryParseComplete) Parse() *pgproto3.ParseComplete {
	return (*FromServer[*pgproto3.ParseComplete])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryParseComplete) Retain() ServerExtendedQueryParseComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParseComplete])(&m).retainFields()
	return ServerExtendedQueryParseComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Bind.
type ServerExtendedQueryBindComplete FromServer[*pgproto3.BindComplete]

func (*ServerExtendedQueryBindComplete) Server()            {}
func (*ServerExtendedQueryBindComplete) ExtendedQuery()     {}
func (t *ServerExtendedQueryBindComplete) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryBindComplete) Parse() *pgproto3.BindComplete {
	return (*FromServer[*pgproto3.BindComplete])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryBindComplete) Retain() ServerExtendedQueryBindComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.BindComplete])(&m).retainFields()
	return ServerExtendedQueryBindComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of prepared statement.
type ServerExtendedQueryParameterDescription FromServer[*pgproto3.ParameterDescription]

func (*ServerExtendedQueryParameterDescription) Server()            {}
func (*ServerExtendedQueryParameterDescription) ExtendedQuery()     {}
func (t *ServerExtendedQueryParameterDescription) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryParameterDescription) Parse() *pgproto3.ParameterDescription {
	return (*FromServer[*pgproto3.ParameterDescription])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryParameterDescription) Retain() ServerExtendedQueryParameterDescription {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParameterDescription])(&m).retainFields()
	return ServerExtendedQueryParameterDescription{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of portal or statement that returns data.
type ServerExtendedQueryRowDescription FromServer[*pgproto3.RowDescription]

func (*ServerExtendedQueryRowDescription) Server()            {}
func (*ServerExtendedQueryRowDescription) ExtendedQuery()     {}
func (t *ServerExtendedQueryRowDescription) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryRowDescription) Parse() *pgproto3.RowDescription {
	return (*FromServer[*pgproto3.RowDescription])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryRowDescription) Retain() ServerExtendedQueryRowDescription {
	src, parsed, isParsed := (*FromServer[*pgproto3.RowDescription])(&m).retainFields()
	return ServerExtendedQueryRowDescription{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of portal or statement that doesn't return data.
type ServerExtendedQueryNoData FromServer[*pgproto3.NoData]

func (*ServerExtendedQueryNoData) Server()            {}
func (*ServerExtendedQueryNoData) ExtendedQuery()     {}
func (t *ServerExtendedQueryNoData) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryNoData) Parse() *pgproto3.NoData {
	return (*FromServer[*pgproto3.NoData])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryNoData) Retain() ServerExtendedQueryNoData {
	src, parsed, isParsed := (*FromServer[*pgproto3.NoData])(&m).retainFields()
	return ServerExtendedQueryNoData{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Execute if there are additional rows / the execute did not
// complete during the Execute call, the client should call Execute again.
type ServerExtendedQueryPortalSuspended FromServer[*pgproto3.PortalSuspended]

func (*ServerExtendedQueryPortalSuspended) Server()            {}
func (*ServerExtendedQueryPortalSuspended) ExtendedQuery()     {}
func (t *ServerExtendedQueryPortalSuspended) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryPortalSuspended) Parse() *pgproto3.PortalSuspended {
	return (*FromServer[*pgproto3.PortalSuspended])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryPortalSuspended) Retain() ServerExtendedQueryPortalSuspended {
	src, parsed, isParsed := (*FromServer[*pgproto3.PortalSuspended])(&m).retainFields()
	return ServerExtendedQueryPortalSuspended{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Close of prepared statement or portal.
type ServerExtendedQueryCloseComplete FromServer[*pgproto3.CloseComplete]

func (*ServerExtendedQueryCloseComplete) Server()            {}
func (*ServerExtendedQueryCloseComplete) ExtendedQuery()     {}
func (t *ServerExtendedQueryCloseComplete) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerExtendedQueryCloseComplete) Parse() *pgproto3.CloseComplete {
	return (*FromServer[*pgproto3.CloseComplete])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerExtendedQueryCloseComplete) Retain() ServerExtendedQueryCloseComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.CloseComplete])(&m).retainFields()
	return ServerExtendedQueryCloseComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerExtendedQuery converts a pgproto3.BackendMessage to a ServerExtendedQuery if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerExtendedQuery(msg pgproto3.BackendMessage) (ServerExtendedQuery, bool) {
	switch m := msg.(type) {
	case *pgproto3.ParseComplete:
		return (*ServerExtendedQueryParseComplete)(ServerParsed(m)), true
	case *pgproto3.BindComplete:
		return (*ServerExtendedQueryBindComplete)(ServerParsed(m)), true
	case *pgproto3.ParameterDescription:
		return (*ServerExtendedQueryParameterDescription)(ServerParsed(m)), true
	case *pgproto3.RowDescription:
		return (*ServerExtendedQueryRowDescription)(ServerParsed(m)), true
	case *pgproto3.NoData:
		return (*ServerExtendedQueryNoData)(ServerParsed(m)), true
	case *pgproto3.PortalSuspended:
		return (*ServerExtendedQueryPortalSuspended)(ServerParsed(m)), true
	case *pgproto3.CloseComplete:
		return (*ServerExtendedQueryCloseComplete)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerExtendedQueryHandlers provides type-safe handlers for each ServerExtendedQuery variant.
type ServerExtendedQueryHandlers[T any] struct {
	Default              func(msg ServerExtendedQuery) (T, error)
	ParseComplete        func(msg *ServerExtendedQueryParseComplete) (T, error)
	BindComplete         func(msg *ServerExtendedQueryBindComplete) (T, error)
	ParameterDescription func(msg *ServerExtendedQueryParameterDescription) (T, error)
	RowDescription       func(msg *ServerExtendedQueryRowDescription) (T, error)
	NoData               func(msg *ServerExtendedQueryNoData) (T, error)
	PortalSuspended      func(msg *ServerExtendedQueryPortalSuspended) (T, error)
	CloseComplete        func(msg *ServerExtendedQueryCloseComplete) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerExtendedQueryHandlers[T]) HandleDefault(msg ServerExtendedQuery, defaultHandler func(msg ServerExtendedQuery) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerExtendedQuery) (T, error) {
			panic(fmt.Sprintf("no handler defined for server extendedquery message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerExtendedQueryParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryNoData:
		if h.NoData != nil {
			return h.NoData(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(msg)
		}
		return defaultHandler(msg)
	case *ServerExtendedQueryCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server extendedquery message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerExtendedQueryHandlers[T]) Handle(msg ServerExtendedQuery) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerExtendedQueryHandlersCtx provides type-safe handlers with context and an argument for each ServerExtendedQuery variant.
type ServerExtendedQueryHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error)
	ParseComplete        func(ctx context.Context, msg *ServerExtendedQueryParseComplete, arg Arg) (Result, error)
	BindComplete         func(ctx context.Context, msg *ServerExtendedQueryBindComplete, arg Arg) (Result, error)
	ParameterDescription func(ctx context.Context, msg *ServerExtendedQueryParameterDescription, arg Arg) (Result, error)
	RowDescription       func(ctx context.Context, msg *ServerExtendedQueryRowDescription, arg Arg) (Result, error)
	NoData               func(ctx context.Context, msg *ServerExtendedQueryNoData, arg Arg) (Result, error)
	PortalSuspended      func(ctx context.Context, msg *ServerExtendedQueryPortalSuspended, arg Arg) (Result, error)
	CloseComplete        func(ctx context.Context, msg *ServerExtendedQueryCloseComplete, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerExtendedQueryHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerExtendedQuery, arg Arg, defaultHandler func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server extendedquery message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerExtendedQueryParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryNoData:
		if h.NoData != nil {
			return h.NoData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server extendedquery message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerExtendedQueryHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerCopy is implemented by all Server Copy message wrapper types.
type ServerCopy interface {
	Server()
	Copy()
	MsgType() MsgType
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerCopy = (*ServerCopyCopyInResponse)(nil)
	_ ServerCopy = (*ServerCopyCopyOutResponse)(nil)
	_ ServerCopy = (*ServerCopyCopyBothResponse)(nil)
	_ ServerCopy = (*ServerCopyCopyData)(nil)
	_ ServerCopy = (*ServerCopyCopyDone)(nil)
)

// Response to COPY FROM STDIN.
// Backend ready to copy data from client to server.
// Starts CopyIn mode.
type ServerCopyCopyInResponse FromServer[*pgproto3.CopyInResponse]

func (*ServerCopyCopyInResponse) Server()            {}
func (*ServerCopyCopyInResponse) Copy()              {}
func (t *ServerCopyCopyInResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerCopyCopyInResponse) Parse() *pgproto3.CopyInResponse {
	return (*FromServer[*pgproto3.CopyInResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyCopyInResponse) Retain() ServerCopyCopyInResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyInResponse])(&m).retainFields()
	return ServerCopyCopyInResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to COPY TO STDOUT.
// Backend ready to copy data from server to client.
// Starts CopyOut mode.
type ServerCopyCopyOutResponse FromServer[*pgproto3.CopyOutResponse]

func (*ServerCopyCopyOutResponse) Server()            {}
func (*ServerCopyCopyOutResponse) Copy()              {}
func (t *ServerCopyCopyOutResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerCopyCopyOutResponse) Parse() *pgproto3.CopyOutResponse {
	return (*FromServer[*pgproto3.CopyOutResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyCopyOutResponse) Retain() ServerCopyCopyOutResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyOutResponse])(&m).retainFields()
	return ServerCopyCopyOutResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Replication.
type ServerCopyCopyBothResponse FromServer[*pgproto3.CopyBothResponse]

func (*ServerCopyCopyBothResponse) Server()            {}
func (*ServerCopyCopyBothResponse) Copy()              {}
func (t *ServerCopyCopyBothResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerCopyCopyBothResponse) Parse() *pgproto3.CopyBothResponse {
	return (*FromServer[*pgproto3.CopyBothResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyCopyBothResponse) Retain() ServerCopyCopyBothResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyBothResponse])(&m).retainFields()
	return ServerCopyCopyBothResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Copy Mode: data row.
type ServerCopyCopyData FromServer[*pgproto3.CopyData]

func (*ServerCopyCopyData) Server()            {}
func (*ServerCopyCopyData) Copy()              {}
func (t *ServerCopyCopyData) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerCopyCopyData) Parse() *pgproto3.CopyData {
	return (*FromServer[*pgproto3.CopyData])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyCopyData) Retain() ServerCopyCopyData {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyData])(&m).retainFields()
	return ServerCopyCopyData{source: src, parsed: parsed, isParsed: isParsed}
}

// Copy Mode: copy completed.
type ServerCopyCopyDone FromServer[*pgproto3.CopyDone]

func (*ServerCopyCopyDone) Server()            {}
func (*ServerCopyCopyDone) Copy()              {}
func (t *ServerCopyCopyDone) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerCopyCopyDone) Parse() *pgproto3.CopyDone {
	return (*FromServer[*pgproto3.CopyDone])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyCopyDone) Retain() ServerCopyCopyDone {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyDone])(&m).retainFields()
	return ServerCopyCopyDone{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerCopy converts a pgproto3.BackendMessage to a ServerCopy if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerCopy(msg pgproto3.BackendMessage) (ServerCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyInResponse:
		return (*ServerCopyCopyInResponse)(ServerParsed(m)), true
	case *pgproto3.CopyOutResponse:
		return (*ServerCopyCopyOutResponse)(ServerParsed(m)), true
	case *pgproto3.CopyBothResponse:
		return (*ServerCopyCopyBothResponse)(ServerParsed(m)), true
	case *pgproto3.CopyData:
		return (*ServerCopyCopyData)(ServerParsed(m)), true
	case *pgproto3.CopyDone:
		return (*ServerCopyCopyDone)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerCopyHandlers provides type-safe handlers for each ServerCopy variant.
type ServerCopyHandlers[T any] struct {
	Default          func(msg ServerCopy) (T, error)
	CopyInResponse   func(msg *ServerCopyCopyInResponse) (T, error)
	CopyOutResponse  func(msg *ServerCopyCopyOutResponse) (T, error)
	CopyBothResponse func(msg *ServerCopyCopyBothResponse) (T, error)
	CopyData         func(msg *ServerCopyCopyData) (T, error)
	CopyDone         func(msg *ServerCopyCopyDone) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerCopyHandlers[T]) HandleDefault(msg ServerCopy, defaultHandler func(msg ServerCopy) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerCopy) (T, error) {
			panic(fmt.Sprintf("no handler defined for server copy message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerCopyCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyCopyData:
		if h.CopyData != nil {
			return h.CopyData(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server copy message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerCopyHandlers[T]) Handle(msg ServerCopy) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerCopyHandlersCtx provides type-safe handlers with context and an argument for each ServerCopy variant.
type ServerCopyHandlersCtx[Arg, Result any] struct {
	Default          func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error)
	CopyInResponse   func(ctx context.Context, msg *ServerCopyCopyInResponse, arg Arg) (Result, error)
	CopyOutResponse  func(ctx context.Context, msg *ServerCopyCopyOutResponse, arg Arg) (Result, error)
	CopyBothResponse func(ctx context.Context, msg *ServerCopyCopyBothResponse, arg Arg) (Result, error)
	CopyData         func(ctx context.Context, msg *ServerCopyCopyData, arg Arg) (Result, error)
	CopyDone         func(ctx context.Context, msg *ServerCopyCopyDone, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerCopyHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerCopy, arg Arg, defaultHandler func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server copy message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerCopyCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyData:
		if h.CopyData != nil {
			return h.CopyData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server copy message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerCopyHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerCopy, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerResponse is implemented by all Server Response message wrapper types.
type ServerResponse interface {
	Server()
	Response()
	MsgType() MsgType
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerResponse = (*ServerResponseReadyForQuery)(nil)
	_ ServerResponse = (*ServerResponseCommandComplete)(nil)
	_ ServerResponse = (*ServerResponseDataRow)(nil)
	_ ServerResponse = (*ServerResponseEmptyQueryResponse)(nil)
	_ ServerResponse = (*ServerResponseErrorResponse)(nil)
	_ ServerResponse = (*ServerResponseFunctionCallResponse)(nil)
)

// Start-up completed.
// Simple Query mode: ready for next query.
// Extended Query mode: response to Sync; backend no longer ignoring messages, ready for next command.
type ServerResponseReadyForQuery FromServer[*pgproto3.ReadyForQuery]

func (*ServerResponseReadyForQuery) Server()            {}
func (*ServerResponseReadyForQuery) Response()          {}
func (t *ServerResponseReadyForQuery) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseReadyForQuery) Parse() *pgproto3.ReadyForQuery {
	return (*FromServer[*pgproto3.ReadyForQuery])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseReadyForQuery) Retain() ServerResponseReadyForQuery {
	src, parsed, isParsed := (*FromServer[*pgproto3.ReadyForQuery])(&m).retainFields()
	return ServerResponseReadyForQuery{source: src, parsed: parsed, isParsed: isParsed}
}

// SQL command completed normally.
type ServerResponseCommandComplete FromServer[*pgproto3.CommandComplete]

func (*ServerResponseCommandComplete) Server()            {}
func (*ServerResponseCommandComplete) Response()          {}
func (t *ServerResponseCommandComplete) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseCommandComplete) Parse() *pgproto3.CommandComplete {
	return (*FromServer[*pgproto3.CommandComplete])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseCommandComplete) Retain() ServerResponseCommandComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.CommandComplete])(&m).retainFields()
	return ServerResponseCommandComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Query results (both query modes)
type ServerResponseDataRow FromServer[*pgproto3.DataRow]

func (*ServerResponseDataRow) Server()            {}
func (*ServerResponseDataRow) Response()          {}
func (t *ServerResponseDataRow) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseDataRow) Parse() *pgproto3.DataRow {
	return (*FromServer[*pgproto3.DataRow])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseDataRow) Retain() ServerResponseDataRow {
	src, parsed, isParsed := (*FromServer[*pgproto3.DataRow])(&m).retainFields()
	return ServerResponseDataRow{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to empty query.
type ServerResponseEmptyQueryResponse FromServer[*pgproto3.EmptyQueryResponse]

func (*ServerResponseEmptyQueryResponse) Server()            {}
func (*ServerResponseEmptyQueryResponse) Response()          {}
func (t *ServerResponseEmptyQueryResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseEmptyQueryResponse) Parse() *pgproto3.EmptyQueryResponse {
	return (*FromServer[*pgproto3.EmptyQueryResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseEmptyQueryResponse) Retain() ServerResponseEmptyQueryResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.EmptyQueryResponse])(&m).retainFields()
	return ServerResponseEmptyQueryResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Error response.
type ServerResponseErrorResponse FromServer[*pgproto3.ErrorResponse]

func (*ServerResponseErrorResponse) Server()            {}
func (*ServerResponseErrorResponse) Response()          {}
func (t *ServerResponseErrorResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseErrorResponse) Parse() *pgproto3.ErrorResponse {
	return (*FromServer[*pgproto3.ErrorResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseErrorResponse) Retain() ServerResponseErrorResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.ErrorResponse])(&m).retainFields()
	return ServerResponseErrorResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to function call.
type ServerResponseFunctionCallResponse FromServer[*pgproto3.FunctionCallResponse]

func (*ServerResponseFunctionCallResponse) Server()            {}
func (*ServerResponseFunctionCallResponse) Response()          {}
func (t *ServerResponseFunctionCallResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerResponseFunctionCallResponse) Parse() *pgproto3.FunctionCallResponse {
	return (*FromServer[*pgproto3.FunctionCallResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerResponseFunctionCallResponse) Retain() ServerResponseFunctionCallResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.FunctionCallResponse])(&m).retainFields()
	return ServerResponseFunctionCallResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerResponse converts a pgproto3.BackendMessage to a ServerResponse if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerResponse(msg pgproto3.BackendMessage) (ServerResponse, bool) {
	switch m := msg.(type) {
	case *pgproto3.ReadyForQuery:
		return (*ServerResponseReadyForQuery)(ServerParsed(m)), true
	case *pgproto3.CommandComplete:
		return (*ServerResponseCommandComplete)(ServerParsed(m)), true
	case *pgproto3.DataRow:
		return (*ServerResponseDataRow)(ServerParsed(m)), true
	case *pgproto3.EmptyQueryResponse:
		return (*ServerResponseEmptyQueryResponse)(ServerParsed(m)), true
	case *pgproto3.ErrorResponse:
		return (*ServerResponseErrorResponse)(ServerParsed(m)), true
	case *pgproto3.FunctionCallResponse:
		return (*ServerResponseFunctionCallResponse)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerResponseHandlers provides type-safe handlers for each ServerResponse variant.
type ServerResponseHandlers[T any] struct {
	Default              func(msg ServerResponse) (T, error)
	ReadyForQuery        func(msg *ServerResponseReadyForQuery) (T, error)
	CommandComplete      func(msg *ServerResponseCommandComplete) (T, error)
	DataRow              func(msg *ServerResponseDataRow) (T, error)
	EmptyQueryResponse   func(msg *ServerResponseEmptyQueryResponse) (T, error)
	ErrorResponse        func(msg *ServerResponseErrorResponse) (T, error)
	FunctionCallResponse func(msg *ServerResponseFunctionCallResponse) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerResponseHandlers[T]) HandleDefault(msg ServerResponse, defaultHandler func(msg ServerResponse) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerResponse) (T, error) {
			panic(fmt.Sprintf("no handler defined for server response message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerResponseReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(msg)
		}
		return defaultHandler(msg)
	case *ServerResponseCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerResponseDataRow:
		if h.DataRow != nil {
			return h.DataRow(msg)
		}
		return defaultHandler(msg)
	case *ServerResponseEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerResponseErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerResponseFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server response message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerResponseHandlers[T]) Handle(msg ServerResponse) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerResponseHandlersCtx provides type-safe handlers with context and an argument for each ServerResponse variant.
type ServerResponseHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error)
	ReadyForQuery        func(ctx context.Context, msg *ServerResponseReadyForQuery, arg Arg) (Result, error)
	CommandComplete      func(ctx context.Context, msg *ServerResponseCommandComplete, arg Arg) (Result, error)
	DataRow              func(ctx context.Context, msg *ServerResponseDataRow, arg Arg) (Result, error)
	EmptyQueryResponse   func(ctx context.Context, msg *ServerResponseEmptyQueryResponse, arg Arg) (Result, error)
	ErrorResponse        func(ctx context.Context, msg *ServerResponseErrorResponse, arg Arg) (Result, error)
	FunctionCallResponse func(ctx context.Context, msg *ServerResponseFunctionCallResponse, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerResponseHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerResponse, arg Arg, defaultHandler func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server response message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerResponseReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseDataRow:
		if h.DataRow != nil {
			return h.DataRow(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server response message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerResponseHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerResponse, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerAsync is implemented by all Server Async message wrapper types.
type ServerAsync interface {
	Server()
	Async()
	MsgType() MsgType
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerAsync = (*ServerAsyncNoticeResponse)(nil)
	_ ServerAsync = (*ServerAsyncNotificationResponse)(nil)
	_ ServerAsync = (*ServerAsyncParameterStatus)(nil)
)

// Warning message.
type ServerAsyncNoticeResponse FromServer[*pgproto3.NoticeResponse]

func (*ServerAsyncNoticeResponse) Server()            {}
func (*ServerAsyncNoticeResponse) Async()             {}
func (t *ServerAsyncNoticeResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerAsyncNoticeResponse) Parse() *pgproto3.NoticeResponse {
	return (*FromServer[*pgproto3.NoticeResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAsyncNoticeResponse) Retain() ServerAsyncNoticeResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.NoticeResponse])(&m).retainFields()
	return ServerAsyncNoticeResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// LISTEN/NOTIFY notification.
type ServerAsyncNotificationResponse FromServer[*pgproto3.NotificationResponse]

func (*ServerAsyncNotificationResponse) Server()            {}
func (*ServerAsyncNotificationResponse) Async()             {}
func (t *ServerAsyncNotificationResponse) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerAsyncNotificationResponse) Parse() *pgproto3.NotificationResponse {
	return (*FromServer[*pgproto3.NotificationResponse])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAsyncNotificationResponse) Retain() ServerAsyncNotificationResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.NotificationResponse])(&m).retainFields()
	return ServerAsyncNotificationResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Informs client that runtime parameter value changed.
type ServerAsyncParameterStatus FromServer[*pgproto3.ParameterStatus]

func (*ServerAsyncParameterStatus) Server()            {}
func (*ServerAsyncParameterStatus) Async()             {}
func (t *ServerAsyncParameterStatus) MsgType() MsgType { return t.source.MessageType() }
func (m *ServerAsyncParameterStatus) Parse() *pgproto3.ParameterStatus {
	return (*FromServer[*pgproto3.ParameterStatus])(m).Parse()
}

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAsyncParameterStatus) Retain() ServerAsyncParameterStatus {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParameterStatus])(&m).retainFields()
	return ServerAsyncParameterStatus{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerAsync converts a pgproto3.BackendMessage to a ServerAsync if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerAsync(msg pgproto3.BackendMessage) (ServerAsync, bool) {
	switch m := msg.(type) {
	case *pgproto3.NoticeResponse:
		return (*ServerAsyncNoticeResponse)(ServerParsed(m)), true
	case *pgproto3.NotificationResponse:
		return (*ServerAsyncNotificationResponse)(ServerParsed(m)), true
	case *pgproto3.ParameterStatus:
		return (*ServerAsyncParameterStatus)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerAsyncHandlers provides type-safe handlers for each ServerAsync variant.
type ServerAsyncHandlers[T any] struct {
	Default              func(msg ServerAsync) (T, error)
	NoticeResponse       func(msg *ServerAsyncNoticeResponse) (T, error)
	NotificationResponse func(msg *ServerAsyncNotificationResponse) (T, error)
	ParameterStatus      func(msg *ServerAsyncParameterStatus) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerAsyncHandlers[T]) HandleDefault(msg ServerAsync, defaultHandler func(msg ServerAsync) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerAsync) (T, error) {
			panic(fmt.Sprintf("no handler defined for server async message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerAsyncNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerAsyncNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerAsyncParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server async message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerAsyncHandlers[T]) Handle(msg ServerAsync) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerAsyncHandlersCtx provides type-safe handlers with context and an argument for each ServerAsync variant.
type ServerAsyncHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error)
	NoticeResponse       func(ctx context.Context, msg *ServerAsyncNoticeResponse, arg Arg) (Result, error)
	NotificationResponse func(ctx context.Context, msg *ServerAsyncNotificationResponse, arg Arg) (Result, error)
	ParameterStatus      func(ctx context.Context, msg *ServerAsyncParameterStatus, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerAsyncHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerAsync, arg Arg, defaultHandler func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server async message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerAsyncNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAsyncNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAsyncParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server async message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerAsyncHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerAsync, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerHandlers provides type-safe dispatch for all Server variants.
type ServerHandlers[Arg, Result any] struct {
	Default func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error)
	// Startup
	Startup                         *ServerStartupHandlersCtx[Arg, Result]
	AuthenticationCleartextPassword func(ctx context.Context, msg *ServerStartupAuthenticationCleartextPassword, arg Arg) (Result, error)
	AuthenticationGSS               func(ctx context.Context, msg *ServerStartupAuthenticationGSS, arg Arg) (Result, error)
	AuthenticationGSSContinue       func(ctx context.Context, msg *ServerStartupAuthenticationGSSContinue, arg Arg) (Result, error)
	AuthenticationMD5Password       func(ctx context.Context, msg *ServerStartupAuthenticationMD5Password, arg Arg) (Result, error)
	AuthenticationOk                func(ctx context.Context, msg *ServerStartupAuthenticationOk, arg Arg) (Result, error)
	AuthenticationSASL              func(ctx context.Context, msg *ServerStartupAuthenticationSASL, arg Arg) (Result, error)
	AuthenticationSASLContinue      func(ctx context.Context, msg *ServerStartupAuthenticationSASLContinue, arg Arg) (Result, error)
	AuthenticationSASLFinal         func(ctx context.Context, msg *ServerStartupAuthenticationSASLFinal, arg Arg) (Result, error)
	BackendKeyData                  func(ctx context.Context, msg *ServerStartupBackendKeyData, arg Arg) (Result, error)

	// ExtendedQuery
	ExtendedQuery        *ServerExtendedQueryHandlersCtx[Arg, Result]
	ParseComplete        func(ctx context.Context, msg *ServerExtendedQueryParseComplete, arg Arg) (Result, error)
	BindComplete         func(ctx context.Context, msg *ServerExtendedQueryBindComplete, arg Arg) (Result, error)
	ParameterDescription func(ctx context.Context, msg *ServerExtendedQueryParameterDescription, arg Arg) (Result, error)
	RowDescription       func(ctx context.Context, msg *ServerExtendedQueryRowDescription, arg Arg) (Result, error)
	NoData               func(ctx context.Context, msg *ServerExtendedQueryNoData, arg Arg) (Result, error)
	PortalSuspended      func(ctx context.Context, msg *ServerExtendedQueryPortalSuspended, arg Arg) (Result, error)
	CloseComplete        func(ctx context.Context, msg *ServerExtendedQueryCloseComplete, arg Arg) (Result, error)

	// Copy
	Copy             *ServerCopyHandlersCtx[Arg, Result]
	CopyInResponse   func(ctx context.Context, msg *ServerCopyCopyInResponse, arg Arg) (Result, error)
	CopyOutResponse  func(ctx context.Context, msg *ServerCopyCopyOutResponse, arg Arg) (Result, error)
	CopyBothResponse func(ctx context.Context, msg *ServerCopyCopyBothResponse, arg Arg) (Result, error)
	CopyData         func(ctx context.Context, msg *ServerCopyCopyData, arg Arg) (Result, error)
	CopyDone         func(ctx context.Context, msg *ServerCopyCopyDone, arg Arg) (Result, error)

	// Response
	Response             *ServerResponseHandlersCtx[Arg, Result]
	ReadyForQuery        func(ctx context.Context, msg *ServerResponseReadyForQuery, arg Arg) (Result, error)
	CommandComplete      func(ctx context.Context, msg *ServerResponseCommandComplete, arg Arg) (Result, error)
	DataRow              func(ctx context.Context, msg *ServerResponseDataRow, arg Arg) (Result, error)
	EmptyQueryResponse   func(ctx context.Context, msg *ServerResponseEmptyQueryResponse, arg Arg) (Result, error)
	ErrorResponse        func(ctx context.Context, msg *ServerResponseErrorResponse, arg Arg) (Result, error)
	FunctionCallResponse func(ctx context.Context, msg *ServerResponseFunctionCallResponse, arg Arg) (Result, error)

	// Async
	Async                *ServerAsyncHandlersCtx[Arg, Result]
	NoticeResponse       func(ctx context.Context, msg *ServerAsyncNoticeResponse, arg Arg) (Result, error)
	NotificationResponse func(ctx context.Context, msg *ServerAsyncNotificationResponse, arg Arg) (Result, error)
	ParameterStatus      func(ctx context.Context, msg *ServerAsyncParameterStatus, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerHandlers[Arg, Result]) HandleDefault(ctx context.Context, msg ServerMessage, arg Arg, defaultHandler func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerStartupAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationCleartextPassword != nil {
			return h.Startup.AuthenticationCleartextPassword(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationGSS != nil {
			return h.Startup.AuthenticationGSS(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationGSSContinue != nil {
			return h.Startup.AuthenticationGSSContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationMD5Password != nil {
			return h.Startup.AuthenticationMD5Password(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationOk != nil {
			return h.Startup.AuthenticationOk(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASL != nil {
			return h.Startup.AuthenticationSASL(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASLContinue != nil {
			return h.Startup.AuthenticationSASLContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASLFinal != nil {
			return h.Startup.AuthenticationSASLFinal(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerStartupBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.BackendKeyData != nil {
			return h.Startup.BackendKeyData(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.ParseComplete != nil {
			return h.ExtendedQuery.ParseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.BindComplete != nil {
			return h.ExtendedQuery.BindComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.ParameterDescription != nil {
			return h.ExtendedQuery.ParameterDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.RowDescription != nil {
			return h.ExtendedQuery.RowDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryNoData:
		if h.NoData != nil {
			return h.NoData(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.NoData != nil {
			return h.ExtendedQuery.NoData(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.PortalSuspended != nil {
			return h.ExtendedQuery.PortalSuspended(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerExtendedQueryCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.CloseComplete != nil {
			return h.ExtendedQuery.CloseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyInResponse != nil {
			return h.Copy.CopyInResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyOutResponse != nil {
			return h.Copy.CopyOutResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyBothResponse != nil {
			return h.Copy.CopyBothResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyData:
		if h.CopyData != nil {
			return h.CopyData(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyData != nil {
			return h.Copy.CopyData(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyDone != nil {
			return h.Copy.CopyDone(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(ctx, msg, arg)
		} else if h.Response != nil && h.Response.ReadyForQuery != nil {
			return h.Response.ReadyForQuery(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(ctx, msg, arg)
		} else if h.Response != nil && h.Response.CommandComplete != nil {
			return h.Response.CommandComplete(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseDataRow:
		if h.DataRow != nil {
			return h.DataRow(ctx, msg, arg)
		} else if h.Response != nil && h.Response.DataRow != nil {
			return h.Response.DataRow(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.EmptyQueryResponse != nil {
			return h.Response.EmptyQueryResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.ErrorResponse != nil {
			return h.Response.ErrorResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerResponseFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.FunctionCallResponse != nil {
			return h.Response.FunctionCallResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAsyncNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.NoticeResponse != nil {
			return h.Async.NoticeResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAsyncNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.NotificationResponse != nil {
			return h.Async.NotificationResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAsyncParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(ctx, msg, arg)
		} else if h.Async != nil && h.Async.ParameterStatus != nil {
			return h.Async.ParameterStatus(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerHandlers[Arg, Result]) Handle(ctx context.Context, msg ServerMessage, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}
