// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerStartup is implemented by all Server Startup message wrapper types.
type ServerStartup interface {
	Server()
	Startup()
	PgwireMessage()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerStartup = ServerStartupAuthenticationCleartextPassword{}
	_ ServerStartup = ServerStartupAuthenticationGSS{}
	_ ServerStartup = ServerStartupAuthenticationGSSContinue{}
	_ ServerStartup = ServerStartupAuthenticationMD5Password{}
	_ ServerStartup = ServerStartupAuthenticationOk{}
	_ ServerStartup = ServerStartupAuthenticationSASL{}
	_ ServerStartup = ServerStartupAuthenticationSASLContinue{}
	_ ServerStartup = ServerStartupAuthenticationSASLFinal{}
	_ ServerStartup = ServerStartupBackendKeyData{}
)

// ServerStartupAuthenticationCleartextPassword wraps *pgproto3.AuthenticationCleartextPassword from the server.
type ServerStartupAuthenticationCleartextPassword FromServer[*pgproto3.AuthenticationCleartextPassword]

func (ServerStartupAuthenticationCleartextPassword) Server()        {}
func (ServerStartupAuthenticationCleartextPassword) Startup()       {}
func (ServerStartupAuthenticationCleartextPassword) PgwireMessage() {}

// ServerStartupAuthenticationGSS wraps *pgproto3.AuthenticationGSS from the server.
type ServerStartupAuthenticationGSS FromServer[*pgproto3.AuthenticationGSS]

func (ServerStartupAuthenticationGSS) Server()        {}
func (ServerStartupAuthenticationGSS) Startup()       {}
func (ServerStartupAuthenticationGSS) PgwireMessage() {}

// ServerStartupAuthenticationGSSContinue wraps *pgproto3.AuthenticationGSSContinue from the server.
type ServerStartupAuthenticationGSSContinue FromServer[*pgproto3.AuthenticationGSSContinue]

func (ServerStartupAuthenticationGSSContinue) Server()        {}
func (ServerStartupAuthenticationGSSContinue) Startup()       {}
func (ServerStartupAuthenticationGSSContinue) PgwireMessage() {}

// ServerStartupAuthenticationMD5Password wraps *pgproto3.AuthenticationMD5Password from the server.
type ServerStartupAuthenticationMD5Password FromServer[*pgproto3.AuthenticationMD5Password]

func (ServerStartupAuthenticationMD5Password) Server()        {}
func (ServerStartupAuthenticationMD5Password) Startup()       {}
func (ServerStartupAuthenticationMD5Password) PgwireMessage() {}

// ServerStartupAuthenticationOk wraps *pgproto3.AuthenticationOk from the server.
type ServerStartupAuthenticationOk FromServer[*pgproto3.AuthenticationOk]

func (ServerStartupAuthenticationOk) Server()        {}
func (ServerStartupAuthenticationOk) Startup()       {}
func (ServerStartupAuthenticationOk) PgwireMessage() {}

// ServerStartupAuthenticationSASL wraps *pgproto3.AuthenticationSASL from the server.
type ServerStartupAuthenticationSASL FromServer[*pgproto3.AuthenticationSASL]

func (ServerStartupAuthenticationSASL) Server()        {}
func (ServerStartupAuthenticationSASL) Startup()       {}
func (ServerStartupAuthenticationSASL) PgwireMessage() {}

// ServerStartupAuthenticationSASLContinue wraps *pgproto3.AuthenticationSASLContinue from the server.
type ServerStartupAuthenticationSASLContinue FromServer[*pgproto3.AuthenticationSASLContinue]

func (ServerStartupAuthenticationSASLContinue) Server()        {}
func (ServerStartupAuthenticationSASLContinue) Startup()       {}
func (ServerStartupAuthenticationSASLContinue) PgwireMessage() {}

// ServerStartupAuthenticationSASLFinal wraps *pgproto3.AuthenticationSASLFinal from the server.
type ServerStartupAuthenticationSASLFinal FromServer[*pgproto3.AuthenticationSASLFinal]

func (ServerStartupAuthenticationSASLFinal) Server()        {}
func (ServerStartupAuthenticationSASLFinal) Startup()       {}
func (ServerStartupAuthenticationSASLFinal) PgwireMessage() {}

// Secret key data for cancel requests.
// This should be already captured when we establish the connection.
type ServerStartupBackendKeyData FromServer[*pgproto3.BackendKeyData]

func (ServerStartupBackendKeyData) Server()        {}
func (ServerStartupBackendKeyData) Startup()       {}
func (ServerStartupBackendKeyData) PgwireMessage() {}

// ToServerStartup converts a pgproto3.BackendMessage to a ServerStartup if it matches one of the known types.
func ToServerStartup(msg pgproto3.BackendMessage) (ServerStartup, bool) {
	switch m := msg.(type) {
	case *pgproto3.AuthenticationCleartextPassword:
		return ServerStartupAuthenticationCleartextPassword{m}, true
	case *pgproto3.AuthenticationGSS:
		return ServerStartupAuthenticationGSS{m}, true
	case *pgproto3.AuthenticationGSSContinue:
		return ServerStartupAuthenticationGSSContinue{m}, true
	case *pgproto3.AuthenticationMD5Password:
		return ServerStartupAuthenticationMD5Password{m}, true
	case *pgproto3.AuthenticationOk:
		return ServerStartupAuthenticationOk{m}, true
	case *pgproto3.AuthenticationSASL:
		return ServerStartupAuthenticationSASL{m}, true
	case *pgproto3.AuthenticationSASLContinue:
		return ServerStartupAuthenticationSASLContinue{m}, true
	case *pgproto3.AuthenticationSASLFinal:
		return ServerStartupAuthenticationSASLFinal{m}, true
	case *pgproto3.BackendKeyData:
		return ServerStartupBackendKeyData{m}, true
	}
	return nil, false
}
