// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerAsync is implemented by all Server Async message wrapper types.
type ServerAsync interface {
	Server()
	Async()
	PgwireMessage()
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerAsync = ServerAsyncNoticeResponse{}
	_ ServerAsync = ServerAsyncNotificationResponse{}
	_ ServerAsync = ServerAsyncParameterStatus{}
)

// Warning message.
type ServerAsyncNoticeResponse FromServer[*pgproto3.NoticeResponse]

func (ServerAsyncNoticeResponse) Server()        {}
func (ServerAsyncNoticeResponse) Async()         {}
func (ServerAsyncNoticeResponse) PgwireMessage() {}

// LISTEN/NOTIFY notification.
type ServerAsyncNotificationResponse FromServer[*pgproto3.NotificationResponse]

func (ServerAsyncNotificationResponse) Server()        {}
func (ServerAsyncNotificationResponse) Async()         {}
func (ServerAsyncNotificationResponse) PgwireMessage() {}

// Informs client that runtime parameter value changed.
type ServerAsyncParameterStatus FromServer[*pgproto3.ParameterStatus]

func (ServerAsyncParameterStatus) Server()        {}
func (ServerAsyncParameterStatus) Async()         {}
func (ServerAsyncParameterStatus) PgwireMessage() {}

// ToServerAsync converts a pgproto3.BackendMessage to a ServerAsync if it matches one of the known types.
func ToServerAsync(msg pgproto3.BackendMessage) (ServerAsync, bool) {
	switch m := msg.(type) {
	case *pgproto3.NoticeResponse:
		return ServerAsyncNoticeResponse{m}, true
	case *pgproto3.NotificationResponse:
		return ServerAsyncNotificationResponse{m}, true
	case *pgproto3.ParameterStatus:
		return ServerAsyncParameterStatus{m}, true
	}
	return nil, false
}
