// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerStartup is implemented by all Server Startup message wrapper types.
type ServerStartup interface {
	Server()
	Startup()
	MsgType() MsgType
	ParseBackend() pgproto3.BackendMessage
	Source() RawMessageSource
	IsParsed() bool
	ParseAny() pgproto3.Message
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerStartup = (*ServerAuthenticationCleartextPassword)(nil)
	_ ServerStartup = (*ServerAuthenticationGSS)(nil)
	_ ServerStartup = (*ServerAuthenticationGSSContinue)(nil)
	_ ServerStartup = (*ServerAuthenticationMD5Password)(nil)
	_ ServerStartup = (*ServerAuthenticationOk)(nil)
	_ ServerStartup = (*ServerAuthenticationSASL)(nil)
	_ ServerStartup = (*ServerAuthenticationSASLContinue)(nil)
	_ ServerStartup = (*ServerAuthenticationSASLFinal)(nil)
	_ ServerStartup = (*ServerBackendKeyData)(nil)
)

// ServerAuthenticationCleartextPassword wraps *pgproto3.AuthenticationCleartextPassword from the server.
type ServerAuthenticationCleartextPassword FromServer[*pgproto3.AuthenticationCleartextPassword]

func (*ServerAuthenticationCleartextPassword) Server()  {}
func (*ServerAuthenticationCleartextPassword) Startup() {}
func (m *ServerAuthenticationCleartextPassword) Parse() *pgproto3.AuthenticationCleartextPassword {
	return (*FromServer[*pgproto3.AuthenticationCleartextPassword])(m).Parse()
}
func (m *ServerAuthenticationCleartextPassword) ParseBackend() pgproto3.BackendMessage {
	return m.Parse()
}
func (m *ServerAuthenticationCleartextPassword) Source() RawMessageSource   { return m.source }
func (m *ServerAuthenticationCleartextPassword) IsParsed() bool             { return m.isParsed }
func (m *ServerAuthenticationCleartextPassword) ParseAny() pgproto3.Message { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationCleartextPassword) Retain() ServerAuthenticationCleartextPassword {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationCleartextPassword])(&m).retainFields()
	return ServerAuthenticationCleartextPassword{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationGSS wraps *pgproto3.AuthenticationGSS from the server.
type ServerAuthenticationGSS FromServer[*pgproto3.AuthenticationGSS]

func (*ServerAuthenticationGSS) Server()  {}
func (*ServerAuthenticationGSS) Startup() {}
func (m *ServerAuthenticationGSS) Parse() *pgproto3.AuthenticationGSS {
	return (*FromServer[*pgproto3.AuthenticationGSS])(m).Parse()
}
func (m *ServerAuthenticationGSS) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationGSS) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationGSS) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationGSS) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationGSS) Retain() ServerAuthenticationGSS {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationGSS])(&m).retainFields()
	return ServerAuthenticationGSS{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationGSSContinue wraps *pgproto3.AuthenticationGSSContinue from the server.
type ServerAuthenticationGSSContinue FromServer[*pgproto3.AuthenticationGSSContinue]

func (*ServerAuthenticationGSSContinue) Server()  {}
func (*ServerAuthenticationGSSContinue) Startup() {}
func (m *ServerAuthenticationGSSContinue) Parse() *pgproto3.AuthenticationGSSContinue {
	return (*FromServer[*pgproto3.AuthenticationGSSContinue])(m).Parse()
}
func (m *ServerAuthenticationGSSContinue) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationGSSContinue) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationGSSContinue) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationGSSContinue) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationGSSContinue) Retain() ServerAuthenticationGSSContinue {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationGSSContinue])(&m).retainFields()
	return ServerAuthenticationGSSContinue{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationMD5Password wraps *pgproto3.AuthenticationMD5Password from the server.
type ServerAuthenticationMD5Password FromServer[*pgproto3.AuthenticationMD5Password]

func (*ServerAuthenticationMD5Password) Server()  {}
func (*ServerAuthenticationMD5Password) Startup() {}
func (m *ServerAuthenticationMD5Password) Parse() *pgproto3.AuthenticationMD5Password {
	return (*FromServer[*pgproto3.AuthenticationMD5Password])(m).Parse()
}
func (m *ServerAuthenticationMD5Password) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationMD5Password) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationMD5Password) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationMD5Password) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationMD5Password) Retain() ServerAuthenticationMD5Password {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationMD5Password])(&m).retainFields()
	return ServerAuthenticationMD5Password{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationOk wraps *pgproto3.AuthenticationOk from the server.
type ServerAuthenticationOk FromServer[*pgproto3.AuthenticationOk]

func (*ServerAuthenticationOk) Server()  {}
func (*ServerAuthenticationOk) Startup() {}
func (m *ServerAuthenticationOk) Parse() *pgproto3.AuthenticationOk {
	return (*FromServer[*pgproto3.AuthenticationOk])(m).Parse()
}
func (m *ServerAuthenticationOk) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationOk) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationOk) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationOk) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationOk) Retain() ServerAuthenticationOk {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationOk])(&m).retainFields()
	return ServerAuthenticationOk{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationSASL wraps *pgproto3.AuthenticationSASL from the server.
type ServerAuthenticationSASL FromServer[*pgproto3.AuthenticationSASL]

func (*ServerAuthenticationSASL) Server()  {}
func (*ServerAuthenticationSASL) Startup() {}
func (m *ServerAuthenticationSASL) Parse() *pgproto3.AuthenticationSASL {
	return (*FromServer[*pgproto3.AuthenticationSASL])(m).Parse()
}
func (m *ServerAuthenticationSASL) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationSASL) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationSASL) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationSASL) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationSASL) Retain() ServerAuthenticationSASL {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASL])(&m).retainFields()
	return ServerAuthenticationSASL{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationSASLContinue wraps *pgproto3.AuthenticationSASLContinue from the server.
type ServerAuthenticationSASLContinue FromServer[*pgproto3.AuthenticationSASLContinue]

func (*ServerAuthenticationSASLContinue) Server()  {}
func (*ServerAuthenticationSASLContinue) Startup() {}
func (m *ServerAuthenticationSASLContinue) Parse() *pgproto3.AuthenticationSASLContinue {
	return (*FromServer[*pgproto3.AuthenticationSASLContinue])(m).Parse()
}
func (m *ServerAuthenticationSASLContinue) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationSASLContinue) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationSASLContinue) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationSASLContinue) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationSASLContinue) Retain() ServerAuthenticationSASLContinue {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASLContinue])(&m).retainFields()
	return ServerAuthenticationSASLContinue{source: src, parsed: parsed, isParsed: isParsed}
}

// ServerAuthenticationSASLFinal wraps *pgproto3.AuthenticationSASLFinal from the server.
type ServerAuthenticationSASLFinal FromServer[*pgproto3.AuthenticationSASLFinal]

func (*ServerAuthenticationSASLFinal) Server()  {}
func (*ServerAuthenticationSASLFinal) Startup() {}
func (m *ServerAuthenticationSASLFinal) Parse() *pgproto3.AuthenticationSASLFinal {
	return (*FromServer[*pgproto3.AuthenticationSASLFinal])(m).Parse()
}
func (m *ServerAuthenticationSASLFinal) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerAuthenticationSASLFinal) Source() RawMessageSource              { return m.source }
func (m *ServerAuthenticationSASLFinal) IsParsed() bool                        { return m.isParsed }
func (m *ServerAuthenticationSASLFinal) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerAuthenticationSASLFinal) Retain() ServerAuthenticationSASLFinal {
	src, parsed, isParsed := (*FromServer[*pgproto3.AuthenticationSASLFinal])(&m).retainFields()
	return ServerAuthenticationSASLFinal{source: src, parsed: parsed, isParsed: isParsed}
}

// Secret key data for cancel requests.
// This should be already captured when we establish the connection.
type ServerBackendKeyData FromServer[*pgproto3.BackendKeyData]

func (*ServerBackendKeyData) Server()  {}
func (*ServerBackendKeyData) Startup() {}
func (m *ServerBackendKeyData) Parse() *pgproto3.BackendKeyData {
	return (*FromServer[*pgproto3.BackendKeyData])(m).Parse()
}
func (m *ServerBackendKeyData) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerBackendKeyData) Source() RawMessageSource              { return m.source }
func (m *ServerBackendKeyData) IsParsed() bool                        { return m.isParsed }
func (m *ServerBackendKeyData) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerBackendKeyData) Retain() ServerBackendKeyData {
	src, parsed, isParsed := (*FromServer[*pgproto3.BackendKeyData])(&m).retainFields()
	return ServerBackendKeyData{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerStartup converts a pgproto3.BackendMessage to a ServerStartup if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerStartup(msg pgproto3.BackendMessage) (ServerStartup, bool) {
	switch m := msg.(type) {
	case *pgproto3.AuthenticationCleartextPassword:
		return (*ServerAuthenticationCleartextPassword)(ServerParsed(m)), true
	case *pgproto3.AuthenticationGSS:
		return (*ServerAuthenticationGSS)(ServerParsed(m)), true
	case *pgproto3.AuthenticationGSSContinue:
		return (*ServerAuthenticationGSSContinue)(ServerParsed(m)), true
	case *pgproto3.AuthenticationMD5Password:
		return (*ServerAuthenticationMD5Password)(ServerParsed(m)), true
	case *pgproto3.AuthenticationOk:
		return (*ServerAuthenticationOk)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASL:
		return (*ServerAuthenticationSASL)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASLContinue:
		return (*ServerAuthenticationSASLContinue)(ServerParsed(m)), true
	case *pgproto3.AuthenticationSASLFinal:
		return (*ServerAuthenticationSASLFinal)(ServerParsed(m)), true
	case *pgproto3.BackendKeyData:
		return (*ServerBackendKeyData)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerStartupHandlers provides type-safe handlers for each ServerStartup variant.
type ServerStartupHandlers[T any] struct {
	Default                         func(msg ServerStartup) (T, error)
	AuthenticationCleartextPassword func(msg *ServerAuthenticationCleartextPassword) (T, error)
	AuthenticationGSS               func(msg *ServerAuthenticationGSS) (T, error)
	AuthenticationGSSContinue       func(msg *ServerAuthenticationGSSContinue) (T, error)
	AuthenticationMD5Password       func(msg *ServerAuthenticationMD5Password) (T, error)
	AuthenticationOk                func(msg *ServerAuthenticationOk) (T, error)
	AuthenticationSASL              func(msg *ServerAuthenticationSASL) (T, error)
	AuthenticationSASLContinue      func(msg *ServerAuthenticationSASLContinue) (T, error)
	AuthenticationSASLFinal         func(msg *ServerAuthenticationSASLFinal) (T, error)
	BackendKeyData                  func(msg *ServerBackendKeyData) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerStartupHandlers[T]) HandleDefault(msg ServerStartup, defaultHandler func(msg ServerStartup) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerStartup) (T, error) {
			panic(fmt.Sprintf("no handler defined for server startup message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(msg)
		}
		return defaultHandler(msg)
	case *ServerAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(msg)
		}
		return defaultHandler(msg)
	case *ServerBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server startup message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerStartupHandlers[T]) Handle(msg ServerStartup) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerStartupHandlersCtx provides type-safe handlers with context and an argument for each ServerStartup variant.
type ServerStartupHandlersCtx[Arg, Result any] struct {
	Default                         func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error)
	AuthenticationCleartextPassword func(ctx context.Context, msg *ServerAuthenticationCleartextPassword, arg Arg) (Result, error)
	AuthenticationGSS               func(ctx context.Context, msg *ServerAuthenticationGSS, arg Arg) (Result, error)
	AuthenticationGSSContinue       func(ctx context.Context, msg *ServerAuthenticationGSSContinue, arg Arg) (Result, error)
	AuthenticationMD5Password       func(ctx context.Context, msg *ServerAuthenticationMD5Password, arg Arg) (Result, error)
	AuthenticationOk                func(ctx context.Context, msg *ServerAuthenticationOk, arg Arg) (Result, error)
	AuthenticationSASL              func(ctx context.Context, msg *ServerAuthenticationSASL, arg Arg) (Result, error)
	AuthenticationSASLContinue      func(ctx context.Context, msg *ServerAuthenticationSASLContinue, arg Arg) (Result, error)
	AuthenticationSASLFinal         func(ctx context.Context, msg *ServerAuthenticationSASLFinal, arg Arg) (Result, error)
	BackendKeyData                  func(ctx context.Context, msg *ServerBackendKeyData, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerStartupHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerStartup, arg Arg, defaultHandler func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerStartup, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server startup message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server startup message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerStartupHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerStartup, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerExtendedQuery is implemented by all Server ExtendedQuery message wrapper types.
type ServerExtendedQuery interface {
	Server()
	ExtendedQuery()
	MsgType() MsgType
	ParseBackend() pgproto3.BackendMessage
	Source() RawMessageSource
	IsParsed() bool
	ParseAny() pgproto3.Message
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerExtendedQuery = (*ServerParseComplete)(nil)
	_ ServerExtendedQuery = (*ServerBindComplete)(nil)
	_ ServerExtendedQuery = (*ServerParameterDescription)(nil)
	_ ServerExtendedQuery = (*ServerRowDescription)(nil)
	_ ServerExtendedQuery = (*ServerNoData)(nil)
	_ ServerExtendedQuery = (*ServerPortalSuspended)(nil)
	_ ServerExtendedQuery = (*ServerCloseComplete)(nil)
)

// Response to Parse.
type ServerParseComplete FromServer[*pgproto3.ParseComplete]

func (*ServerParseComplete) Server()        {}
func (*ServerParseComplete) ExtendedQuery() {}
func (m *ServerParseComplete) Parse() *pgproto3.ParseComplete {
	return (*FromServer[*pgproto3.ParseComplete])(m).Parse()
}
func (m *ServerParseComplete) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerParseComplete) Source() RawMessageSource              { return m.source }
func (m *ServerParseComplete) IsParsed() bool                        { return m.isParsed }
func (m *ServerParseComplete) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerParseComplete) Retain() ServerParseComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParseComplete])(&m).retainFields()
	return ServerParseComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Bind.
type ServerBindComplete FromServer[*pgproto3.BindComplete]

func (*ServerBindComplete) Server()        {}
func (*ServerBindComplete) ExtendedQuery() {}
func (m *ServerBindComplete) Parse() *pgproto3.BindComplete {
	return (*FromServer[*pgproto3.BindComplete])(m).Parse()
}
func (m *ServerBindComplete) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerBindComplete) Source() RawMessageSource              { return m.source }
func (m *ServerBindComplete) IsParsed() bool                        { return m.isParsed }
func (m *ServerBindComplete) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerBindComplete) Retain() ServerBindComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.BindComplete])(&m).retainFields()
	return ServerBindComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of prepared statement.
type ServerParameterDescription FromServer[*pgproto3.ParameterDescription]

func (*ServerParameterDescription) Server()        {}
func (*ServerParameterDescription) ExtendedQuery() {}
func (m *ServerParameterDescription) Parse() *pgproto3.ParameterDescription {
	return (*FromServer[*pgproto3.ParameterDescription])(m).Parse()
}
func (m *ServerParameterDescription) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerParameterDescription) Source() RawMessageSource              { return m.source }
func (m *ServerParameterDescription) IsParsed() bool                        { return m.isParsed }
func (m *ServerParameterDescription) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerParameterDescription) Retain() ServerParameterDescription {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParameterDescription])(&m).retainFields()
	return ServerParameterDescription{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of portal or statement that returns data.
type ServerRowDescription FromServer[*pgproto3.RowDescription]

func (*ServerRowDescription) Server()        {}
func (*ServerRowDescription) ExtendedQuery() {}
func (m *ServerRowDescription) Parse() *pgproto3.RowDescription {
	return (*FromServer[*pgproto3.RowDescription])(m).Parse()
}
func (m *ServerRowDescription) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerRowDescription) Source() RawMessageSource              { return m.source }
func (m *ServerRowDescription) IsParsed() bool                        { return m.isParsed }
func (m *ServerRowDescription) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerRowDescription) Retain() ServerRowDescription {
	src, parsed, isParsed := (*FromServer[*pgproto3.RowDescription])(&m).retainFields()
	return ServerRowDescription{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Describe of portal or statement that doesn't return data.
type ServerNoData FromServer[*pgproto3.NoData]

func (*ServerNoData) Server()                                 {}
func (*ServerNoData) ExtendedQuery()                          {}
func (m *ServerNoData) Parse() *pgproto3.NoData               { return (*FromServer[*pgproto3.NoData])(m).Parse() }
func (m *ServerNoData) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerNoData) Source() RawMessageSource              { return m.source }
func (m *ServerNoData) IsParsed() bool                        { return m.isParsed }
func (m *ServerNoData) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerNoData) Retain() ServerNoData {
	src, parsed, isParsed := (*FromServer[*pgproto3.NoData])(&m).retainFields()
	return ServerNoData{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Execute if there are additional rows / the execute did not
// complete during the Execute call, the client should call Execute again.
type ServerPortalSuspended FromServer[*pgproto3.PortalSuspended]

func (*ServerPortalSuspended) Server()        {}
func (*ServerPortalSuspended) ExtendedQuery() {}
func (m *ServerPortalSuspended) Parse() *pgproto3.PortalSuspended {
	return (*FromServer[*pgproto3.PortalSuspended])(m).Parse()
}
func (m *ServerPortalSuspended) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerPortalSuspended) Source() RawMessageSource              { return m.source }
func (m *ServerPortalSuspended) IsParsed() bool                        { return m.isParsed }
func (m *ServerPortalSuspended) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerPortalSuspended) Retain() ServerPortalSuspended {
	src, parsed, isParsed := (*FromServer[*pgproto3.PortalSuspended])(&m).retainFields()
	return ServerPortalSuspended{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Close of prepared statement or portal.
type ServerCloseComplete FromServer[*pgproto3.CloseComplete]

func (*ServerCloseComplete) Server()        {}
func (*ServerCloseComplete) ExtendedQuery() {}
func (m *ServerCloseComplete) Parse() *pgproto3.CloseComplete {
	return (*FromServer[*pgproto3.CloseComplete])(m).Parse()
}
func (m *ServerCloseComplete) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerCloseComplete) Source() RawMessageSource              { return m.source }
func (m *ServerCloseComplete) IsParsed() bool                        { return m.isParsed }
func (m *ServerCloseComplete) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCloseComplete) Retain() ServerCloseComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.CloseComplete])(&m).retainFields()
	return ServerCloseComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerExtendedQuery converts a pgproto3.BackendMessage to a ServerExtendedQuery if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerExtendedQuery(msg pgproto3.BackendMessage) (ServerExtendedQuery, bool) {
	switch m := msg.(type) {
	case *pgproto3.ParseComplete:
		return (*ServerParseComplete)(ServerParsed(m)), true
	case *pgproto3.BindComplete:
		return (*ServerBindComplete)(ServerParsed(m)), true
	case *pgproto3.ParameterDescription:
		return (*ServerParameterDescription)(ServerParsed(m)), true
	case *pgproto3.RowDescription:
		return (*ServerRowDescription)(ServerParsed(m)), true
	case *pgproto3.NoData:
		return (*ServerNoData)(ServerParsed(m)), true
	case *pgproto3.PortalSuspended:
		return (*ServerPortalSuspended)(ServerParsed(m)), true
	case *pgproto3.CloseComplete:
		return (*ServerCloseComplete)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerExtendedQueryHandlers provides type-safe handlers for each ServerExtendedQuery variant.
type ServerExtendedQueryHandlers[T any] struct {
	Default              func(msg ServerExtendedQuery) (T, error)
	ParseComplete        func(msg *ServerParseComplete) (T, error)
	BindComplete         func(msg *ServerBindComplete) (T, error)
	ParameterDescription func(msg *ServerParameterDescription) (T, error)
	RowDescription       func(msg *ServerRowDescription) (T, error)
	NoData               func(msg *ServerNoData) (T, error)
	PortalSuspended      func(msg *ServerPortalSuspended) (T, error)
	CloseComplete        func(msg *ServerCloseComplete) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerExtendedQueryHandlers[T]) HandleDefault(msg ServerExtendedQuery, defaultHandler func(msg ServerExtendedQuery) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerExtendedQuery) (T, error) {
			panic(fmt.Sprintf("no handler defined for server extendedquery message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(msg)
		}
		return defaultHandler(msg)
	case *ServerRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(msg)
		}
		return defaultHandler(msg)
	case *ServerNoData:
		if h.NoData != nil {
			return h.NoData(msg)
		}
		return defaultHandler(msg)
	case *ServerPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(msg)
		}
		return defaultHandler(msg)
	case *ServerCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server extendedquery message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerExtendedQueryHandlers[T]) Handle(msg ServerExtendedQuery) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerExtendedQueryHandlersCtx provides type-safe handlers with context and an argument for each ServerExtendedQuery variant.
type ServerExtendedQueryHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error)
	ParseComplete        func(ctx context.Context, msg *ServerParseComplete, arg Arg) (Result, error)
	BindComplete         func(ctx context.Context, msg *ServerBindComplete, arg Arg) (Result, error)
	ParameterDescription func(ctx context.Context, msg *ServerParameterDescription, arg Arg) (Result, error)
	RowDescription       func(ctx context.Context, msg *ServerRowDescription, arg Arg) (Result, error)
	NoData               func(ctx context.Context, msg *ServerNoData, arg Arg) (Result, error)
	PortalSuspended      func(ctx context.Context, msg *ServerPortalSuspended, arg Arg) (Result, error)
	CloseComplete        func(ctx context.Context, msg *ServerCloseComplete, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerExtendedQueryHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerExtendedQuery, arg Arg, defaultHandler func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server extendedquery message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerNoData:
		if h.NoData != nil {
			return h.NoData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server extendedquery message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerExtendedQueryHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerExtendedQuery, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerCopy is implemented by all Server Copy message wrapper types.
type ServerCopy interface {
	Server()
	Copy()
	MsgType() MsgType
	ParseBackend() pgproto3.BackendMessage
	Source() RawMessageSource
	IsParsed() bool
	ParseAny() pgproto3.Message
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerCopy = (*ServerCopyInResponse)(nil)
	_ ServerCopy = (*ServerCopyOutResponse)(nil)
	_ ServerCopy = (*ServerCopyBothResponse)(nil)
	_ ServerCopy = (*OldServerCopyData)(nil)
	_ ServerCopy = (*OldServerCopyDone)(nil)
)

// Response to COPY FROM STDIN.
// Backend ready to copy data from client to server.
// Starts CopyIn mode.
type ServerCopyInResponse FromServer[*pgproto3.CopyInResponse]

func (*ServerCopyInResponse) Server() {}
func (*ServerCopyInResponse) Copy()   {}
func (m *ServerCopyInResponse) Parse() *pgproto3.CopyInResponse {
	return (*FromServer[*pgproto3.CopyInResponse])(m).Parse()
}
func (m *ServerCopyInResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerCopyInResponse) Source() RawMessageSource              { return m.source }
func (m *ServerCopyInResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerCopyInResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyInResponse) Retain() ServerCopyInResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyInResponse])(&m).retainFields()
	return ServerCopyInResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to COPY TO STDOUT.
// Backend ready to copy data from server to client.
// Starts CopyOut mode.
type ServerCopyOutResponse FromServer[*pgproto3.CopyOutResponse]

func (*ServerCopyOutResponse) Server() {}
func (*ServerCopyOutResponse) Copy()   {}
func (m *ServerCopyOutResponse) Parse() *pgproto3.CopyOutResponse {
	return (*FromServer[*pgproto3.CopyOutResponse])(m).Parse()
}
func (m *ServerCopyOutResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerCopyOutResponse) Source() RawMessageSource              { return m.source }
func (m *ServerCopyOutResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerCopyOutResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyOutResponse) Retain() ServerCopyOutResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyOutResponse])(&m).retainFields()
	return ServerCopyOutResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to Replication.
type ServerCopyBothResponse FromServer[*pgproto3.CopyBothResponse]

func (*ServerCopyBothResponse) Server() {}
func (*ServerCopyBothResponse) Copy()   {}
func (m *ServerCopyBothResponse) Parse() *pgproto3.CopyBothResponse {
	return (*FromServer[*pgproto3.CopyBothResponse])(m).Parse()
}
func (m *ServerCopyBothResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerCopyBothResponse) Source() RawMessageSource              { return m.source }
func (m *ServerCopyBothResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerCopyBothResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCopyBothResponse) Retain() ServerCopyBothResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyBothResponse])(&m).retainFields()
	return ServerCopyBothResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Copy Mode: data row.
type OldServerCopyData FromServer[*pgproto3.CopyData]

func (*OldServerCopyData) Server() {}
func (*OldServerCopyData) Copy()   {}
func (m *OldServerCopyData) Parse() *pgproto3.CopyData {
	return (*FromServer[*pgproto3.CopyData])(m).Parse()
}
func (m *OldServerCopyData) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *OldServerCopyData) Source() RawMessageSource              { return m.source }
func (m *OldServerCopyData) IsParsed() bool                        { return m.isParsed }
func (m *OldServerCopyData) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m OldServerCopyData) Retain() OldServerCopyData {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyData])(&m).retainFields()
	return OldServerCopyData{source: src, parsed: parsed, isParsed: isParsed}
}

// Copy Mode: copy completed.
type OldServerCopyDone FromServer[*pgproto3.CopyDone]

func (*OldServerCopyDone) Server() {}
func (*OldServerCopyDone) Copy()   {}
func (m *OldServerCopyDone) Parse() *pgproto3.CopyDone {
	return (*FromServer[*pgproto3.CopyDone])(m).Parse()
}
func (m *OldServerCopyDone) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *OldServerCopyDone) Source() RawMessageSource              { return m.source }
func (m *OldServerCopyDone) IsParsed() bool                        { return m.isParsed }
func (m *OldServerCopyDone) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m OldServerCopyDone) Retain() OldServerCopyDone {
	src, parsed, isParsed := (*FromServer[*pgproto3.CopyDone])(&m).retainFields()
	return OldServerCopyDone{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerCopy converts a pgproto3.BackendMessage to a ServerCopy if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerCopy(msg pgproto3.BackendMessage) (ServerCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyInResponse:
		return (*ServerCopyInResponse)(ServerParsed(m)), true
	case *pgproto3.CopyOutResponse:
		return (*ServerCopyOutResponse)(ServerParsed(m)), true
	case *pgproto3.CopyBothResponse:
		return (*ServerCopyBothResponse)(ServerParsed(m)), true
	case *pgproto3.CopyData:
		return (*OldServerCopyData)(ServerParsed(m)), true
	case *pgproto3.CopyDone:
		return (*OldServerCopyDone)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerCopyHandlers provides type-safe handlers for each ServerCopy variant.
type ServerCopyHandlers[T any] struct {
	Default          func(msg ServerCopy) (T, error)
	CopyInResponse   func(msg *ServerCopyInResponse) (T, error)
	CopyOutResponse  func(msg *ServerCopyOutResponse) (T, error)
	CopyBothResponse func(msg *ServerCopyBothResponse) (T, error)
	CopyData         func(msg *OldServerCopyData) (T, error)
	CopyDone         func(msg *OldServerCopyDone) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerCopyHandlers[T]) HandleDefault(msg ServerCopy, defaultHandler func(msg ServerCopy) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerCopy) (T, error) {
			panic(fmt.Sprintf("no handler defined for server copy message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(msg)
		}
		return defaultHandler(msg)
	case *OldServerCopyData:
		if h.CopyData != nil {
			return h.CopyData(msg)
		}
		return defaultHandler(msg)
	case *OldServerCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server copy message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerCopyHandlers[T]) Handle(msg ServerCopy) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerCopyHandlersCtx provides type-safe handlers with context and an argument for each ServerCopy variant.
type ServerCopyHandlersCtx[Arg, Result any] struct {
	Default          func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error)
	CopyInResponse   func(ctx context.Context, msg *ServerCopyInResponse, arg Arg) (Result, error)
	CopyOutResponse  func(ctx context.Context, msg *ServerCopyOutResponse, arg Arg) (Result, error)
	CopyBothResponse func(ctx context.Context, msg *ServerCopyBothResponse, arg Arg) (Result, error)
	CopyData         func(ctx context.Context, msg *OldServerCopyData, arg Arg) (Result, error)
	CopyDone         func(ctx context.Context, msg *OldServerCopyDone, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerCopyHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerCopy, arg Arg, defaultHandler func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerCopy, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server copy message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *OldServerCopyData:
		if h.CopyData != nil {
			return h.CopyData(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *OldServerCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server copy message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerCopyHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerCopy, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerResponse is implemented by all Server Response message wrapper types.
type ServerResponse interface {
	Server()
	Response()
	MsgType() MsgType
	ParseBackend() pgproto3.BackendMessage
	Source() RawMessageSource
	IsParsed() bool
	ParseAny() pgproto3.Message
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerResponse = (*ServerReadyForQuery)(nil)
	_ ServerResponse = (*ServerCommandComplete)(nil)
	_ ServerResponse = (*ServerDataRow)(nil)
	_ ServerResponse = (*ServerEmptyQueryResponse)(nil)
	_ ServerResponse = (*ServerErrorResponse)(nil)
	_ ServerResponse = (*ServerFunctionCallResponse)(nil)
)

// Start-up completed.
// Simple Query mode: ready for next query.
// Extended Query mode: response to Sync; backend no longer ignoring messages, ready for next command.
type ServerReadyForQuery FromServer[*pgproto3.ReadyForQuery]

func (*ServerReadyForQuery) Server()   {}
func (*ServerReadyForQuery) Response() {}
func (m *ServerReadyForQuery) Parse() *pgproto3.ReadyForQuery {
	return (*FromServer[*pgproto3.ReadyForQuery])(m).Parse()
}
func (m *ServerReadyForQuery) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerReadyForQuery) Source() RawMessageSource              { return m.source }
func (m *ServerReadyForQuery) IsParsed() bool                        { return m.isParsed }
func (m *ServerReadyForQuery) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerReadyForQuery) Retain() ServerReadyForQuery {
	src, parsed, isParsed := (*FromServer[*pgproto3.ReadyForQuery])(&m).retainFields()
	return ServerReadyForQuery{source: src, parsed: parsed, isParsed: isParsed}
}

// SQL command completed normally.
type ServerCommandComplete FromServer[*pgproto3.CommandComplete]

func (*ServerCommandComplete) Server()   {}
func (*ServerCommandComplete) Response() {}
func (m *ServerCommandComplete) Parse() *pgproto3.CommandComplete {
	return (*FromServer[*pgproto3.CommandComplete])(m).Parse()
}
func (m *ServerCommandComplete) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerCommandComplete) Source() RawMessageSource              { return m.source }
func (m *ServerCommandComplete) IsParsed() bool                        { return m.isParsed }
func (m *ServerCommandComplete) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerCommandComplete) Retain() ServerCommandComplete {
	src, parsed, isParsed := (*FromServer[*pgproto3.CommandComplete])(&m).retainFields()
	return ServerCommandComplete{source: src, parsed: parsed, isParsed: isParsed}
}

// Query results (both query modes)
type ServerDataRow FromServer[*pgproto3.DataRow]

func (*ServerDataRow) Server()                                 {}
func (*ServerDataRow) Response()                               {}
func (m *ServerDataRow) Parse() *pgproto3.DataRow              { return (*FromServer[*pgproto3.DataRow])(m).Parse() }
func (m *ServerDataRow) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerDataRow) Source() RawMessageSource              { return m.source }
func (m *ServerDataRow) IsParsed() bool                        { return m.isParsed }
func (m *ServerDataRow) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerDataRow) Retain() ServerDataRow {
	src, parsed, isParsed := (*FromServer[*pgproto3.DataRow])(&m).retainFields()
	return ServerDataRow{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to empty query.
type ServerEmptyQueryResponse FromServer[*pgproto3.EmptyQueryResponse]

func (*ServerEmptyQueryResponse) Server()   {}
func (*ServerEmptyQueryResponse) Response() {}
func (m *ServerEmptyQueryResponse) Parse() *pgproto3.EmptyQueryResponse {
	return (*FromServer[*pgproto3.EmptyQueryResponse])(m).Parse()
}
func (m *ServerEmptyQueryResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerEmptyQueryResponse) Source() RawMessageSource              { return m.source }
func (m *ServerEmptyQueryResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerEmptyQueryResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerEmptyQueryResponse) Retain() ServerEmptyQueryResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.EmptyQueryResponse])(&m).retainFields()
	return ServerEmptyQueryResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Error response.
type ServerErrorResponse FromServer[*pgproto3.ErrorResponse]

func (*ServerErrorResponse) Server()   {}
func (*ServerErrorResponse) Response() {}
func (m *ServerErrorResponse) Parse() *pgproto3.ErrorResponse {
	return (*FromServer[*pgproto3.ErrorResponse])(m).Parse()
}
func (m *ServerErrorResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerErrorResponse) Source() RawMessageSource              { return m.source }
func (m *ServerErrorResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerErrorResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerErrorResponse) Retain() ServerErrorResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.ErrorResponse])(&m).retainFields()
	return ServerErrorResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Response to function call.
type ServerFunctionCallResponse FromServer[*pgproto3.FunctionCallResponse]

func (*ServerFunctionCallResponse) Server()   {}
func (*ServerFunctionCallResponse) Response() {}
func (m *ServerFunctionCallResponse) Parse() *pgproto3.FunctionCallResponse {
	return (*FromServer[*pgproto3.FunctionCallResponse])(m).Parse()
}
func (m *ServerFunctionCallResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerFunctionCallResponse) Source() RawMessageSource              { return m.source }
func (m *ServerFunctionCallResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerFunctionCallResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerFunctionCallResponse) Retain() ServerFunctionCallResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.FunctionCallResponse])(&m).retainFields()
	return ServerFunctionCallResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerResponse converts a pgproto3.BackendMessage to a ServerResponse if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerResponse(msg pgproto3.BackendMessage) (ServerResponse, bool) {
	switch m := msg.(type) {
	case *pgproto3.ReadyForQuery:
		return (*ServerReadyForQuery)(ServerParsed(m)), true
	case *pgproto3.CommandComplete:
		return (*ServerCommandComplete)(ServerParsed(m)), true
	case *pgproto3.DataRow:
		return (*ServerDataRow)(ServerParsed(m)), true
	case *pgproto3.EmptyQueryResponse:
		return (*ServerEmptyQueryResponse)(ServerParsed(m)), true
	case *pgproto3.ErrorResponse:
		return (*ServerErrorResponse)(ServerParsed(m)), true
	case *pgproto3.FunctionCallResponse:
		return (*ServerFunctionCallResponse)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerResponseHandlers provides type-safe handlers for each ServerResponse variant.
type ServerResponseHandlers[T any] struct {
	Default              func(msg ServerResponse) (T, error)
	ReadyForQuery        func(msg *ServerReadyForQuery) (T, error)
	CommandComplete      func(msg *ServerCommandComplete) (T, error)
	DataRow              func(msg *ServerDataRow) (T, error)
	EmptyQueryResponse   func(msg *ServerEmptyQueryResponse) (T, error)
	ErrorResponse        func(msg *ServerErrorResponse) (T, error)
	FunctionCallResponse func(msg *ServerFunctionCallResponse) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerResponseHandlers[T]) HandleDefault(msg ServerResponse, defaultHandler func(msg ServerResponse) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerResponse) (T, error) {
			panic(fmt.Sprintf("no handler defined for server response message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(msg)
		}
		return defaultHandler(msg)
	case *ServerCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(msg)
		}
		return defaultHandler(msg)
	case *ServerDataRow:
		if h.DataRow != nil {
			return h.DataRow(msg)
		}
		return defaultHandler(msg)
	case *ServerEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server response message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerResponseHandlers[T]) Handle(msg ServerResponse) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerResponseHandlersCtx provides type-safe handlers with context and an argument for each ServerResponse variant.
type ServerResponseHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error)
	ReadyForQuery        func(ctx context.Context, msg *ServerReadyForQuery, arg Arg) (Result, error)
	CommandComplete      func(ctx context.Context, msg *ServerCommandComplete, arg Arg) (Result, error)
	DataRow              func(ctx context.Context, msg *ServerDataRow, arg Arg) (Result, error)
	EmptyQueryResponse   func(ctx context.Context, msg *ServerEmptyQueryResponse, arg Arg) (Result, error)
	ErrorResponse        func(ctx context.Context, msg *ServerErrorResponse, arg Arg) (Result, error)
	FunctionCallResponse func(ctx context.Context, msg *ServerFunctionCallResponse, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerResponseHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerResponse, arg Arg, defaultHandler func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerResponse, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server response message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerDataRow:
		if h.DataRow != nil {
			return h.DataRow(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server response message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerResponseHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerResponse, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerAsync is implemented by all Server Async message wrapper types.
type ServerAsync interface {
	Server()
	Async()
	MsgType() MsgType
	ParseBackend() pgproto3.BackendMessage
	Source() RawMessageSource
	IsParsed() bool
	ParseAny() pgproto3.Message
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerAsync = (*ServerNoticeResponse)(nil)
	_ ServerAsync = (*ServerNotificationResponse)(nil)
	_ ServerAsync = (*ServerParameterStatus)(nil)
)

// Warning message.
type ServerNoticeResponse FromServer[*pgproto3.NoticeResponse]

func (*ServerNoticeResponse) Server() {}
func (*ServerNoticeResponse) Async()  {}
func (m *ServerNoticeResponse) Parse() *pgproto3.NoticeResponse {
	return (*FromServer[*pgproto3.NoticeResponse])(m).Parse()
}
func (m *ServerNoticeResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerNoticeResponse) Source() RawMessageSource              { return m.source }
func (m *ServerNoticeResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerNoticeResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerNoticeResponse) Retain() ServerNoticeResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.NoticeResponse])(&m).retainFields()
	return ServerNoticeResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// LISTEN/NOTIFY notification.
type ServerNotificationResponse FromServer[*pgproto3.NotificationResponse]

func (*ServerNotificationResponse) Server() {}
func (*ServerNotificationResponse) Async()  {}
func (m *ServerNotificationResponse) Parse() *pgproto3.NotificationResponse {
	return (*FromServer[*pgproto3.NotificationResponse])(m).Parse()
}
func (m *ServerNotificationResponse) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerNotificationResponse) Source() RawMessageSource              { return m.source }
func (m *ServerNotificationResponse) IsParsed() bool                        { return m.isParsed }
func (m *ServerNotificationResponse) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerNotificationResponse) Retain() ServerNotificationResponse {
	src, parsed, isParsed := (*FromServer[*pgproto3.NotificationResponse])(&m).retainFields()
	return ServerNotificationResponse{source: src, parsed: parsed, isParsed: isParsed}
}

// Informs client that runtime parameter value changed.
type ServerParameterStatus FromServer[*pgproto3.ParameterStatus]

func (*ServerParameterStatus) Server() {}
func (*ServerParameterStatus) Async()  {}
func (m *ServerParameterStatus) Parse() *pgproto3.ParameterStatus {
	return (*FromServer[*pgproto3.ParameterStatus])(m).Parse()
}
func (m *ServerParameterStatus) ParseBackend() pgproto3.BackendMessage { return m.Parse() }
func (m *ServerParameterStatus) Source() RawMessageSource              { return m.source }
func (m *ServerParameterStatus) IsParsed() bool                        { return m.isParsed }
func (m *ServerParameterStatus) ParseAny() pgproto3.Message            { return m.Parse() }

// Retain returns a copy of this message with retained source bytes.
// Use this when the message must outlive the current iteration.
func (m ServerParameterStatus) Retain() ServerParameterStatus {
	src, parsed, isParsed := (*FromServer[*pgproto3.ParameterStatus])(&m).retainFields()
	return ServerParameterStatus{source: src, parsed: parsed, isParsed: isParsed}
}

// ToServerAsync converts a pgproto3.BackendMessage to a ServerAsync if it matches one of the known types.
// Note: This allocates. For zero-allocation iteration, use Cursor.AsServer().
func ToServerAsync(msg pgproto3.BackendMessage) (ServerAsync, bool) {
	switch m := msg.(type) {
	case *pgproto3.NoticeResponse:
		return (*ServerNoticeResponse)(ServerParsed(m)), true
	case *pgproto3.NotificationResponse:
		return (*ServerNotificationResponse)(ServerParsed(m)), true
	case *pgproto3.ParameterStatus:
		return (*ServerParameterStatus)(ServerParsed(m)), true
	}
	return nil, false
}

// ServerAsyncHandlers provides type-safe handlers for each ServerAsync variant.
type ServerAsyncHandlers[T any] struct {
	Default              func(msg ServerAsync) (T, error)
	NoticeResponse       func(msg *ServerNoticeResponse) (T, error)
	NotificationResponse func(msg *ServerNotificationResponse) (T, error)
	ParameterStatus      func(msg *ServerParameterStatus) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerAsyncHandlers[T]) HandleDefault(msg ServerAsync, defaultHandler func(msg ServerAsync) (T, error)) (r T, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(msg ServerAsync) (T, error) {
			panic(fmt.Sprintf("no handler defined for server async message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(msg)
		}
		return defaultHandler(msg)
	case *ServerParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(msg)
		}
		return defaultHandler(msg)
	}
	err = fmt.Errorf("unknown server async message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerAsyncHandlers[T]) Handle(msg ServerAsync) (T, error) {
	return h.HandleDefault(msg, nil)
}

// ServerAsyncHandlersCtx provides type-safe handlers with context and an argument for each ServerAsync variant.
type ServerAsyncHandlersCtx[Arg, Result any] struct {
	Default              func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error)
	NoticeResponse       func(ctx context.Context, msg *ServerNoticeResponse, arg Arg) (Result, error)
	NotificationResponse func(ctx context.Context, msg *ServerNotificationResponse, arg Arg) (Result, error)
	ParameterStatus      func(ctx context.Context, msg *ServerParameterStatus, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerAsyncHandlersCtx[Arg, Result]) HandleDefault(ctx context.Context, msg ServerAsync, arg Arg, defaultHandler func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerAsync, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server async message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server async message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerAsyncHandlersCtx[Arg, Result]) Handle(ctx context.Context, msg ServerAsync, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}

// ServerHandlers provides type-safe dispatch for all Server variants.
type ServerHandlers[Arg, Result any] struct {
	Default func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error)
	// Startup
	Startup                         *ServerStartupHandlersCtx[Arg, Result]
	AuthenticationCleartextPassword func(ctx context.Context, msg *ServerAuthenticationCleartextPassword, arg Arg) (Result, error)
	AuthenticationGSS               func(ctx context.Context, msg *ServerAuthenticationGSS, arg Arg) (Result, error)
	AuthenticationGSSContinue       func(ctx context.Context, msg *ServerAuthenticationGSSContinue, arg Arg) (Result, error)
	AuthenticationMD5Password       func(ctx context.Context, msg *ServerAuthenticationMD5Password, arg Arg) (Result, error)
	AuthenticationOk                func(ctx context.Context, msg *ServerAuthenticationOk, arg Arg) (Result, error)
	AuthenticationSASL              func(ctx context.Context, msg *ServerAuthenticationSASL, arg Arg) (Result, error)
	AuthenticationSASLContinue      func(ctx context.Context, msg *ServerAuthenticationSASLContinue, arg Arg) (Result, error)
	AuthenticationSASLFinal         func(ctx context.Context, msg *ServerAuthenticationSASLFinal, arg Arg) (Result, error)
	BackendKeyData                  func(ctx context.Context, msg *ServerBackendKeyData, arg Arg) (Result, error)

	// ExtendedQuery
	ExtendedQuery        *ServerExtendedQueryHandlersCtx[Arg, Result]
	ParseComplete        func(ctx context.Context, msg *ServerParseComplete, arg Arg) (Result, error)
	BindComplete         func(ctx context.Context, msg *ServerBindComplete, arg Arg) (Result, error)
	ParameterDescription func(ctx context.Context, msg *ServerParameterDescription, arg Arg) (Result, error)
	RowDescription       func(ctx context.Context, msg *ServerRowDescription, arg Arg) (Result, error)
	NoData               func(ctx context.Context, msg *ServerNoData, arg Arg) (Result, error)
	PortalSuspended      func(ctx context.Context, msg *ServerPortalSuspended, arg Arg) (Result, error)
	CloseComplete        func(ctx context.Context, msg *ServerCloseComplete, arg Arg) (Result, error)

	// Copy
	Copy             *ServerCopyHandlersCtx[Arg, Result]
	CopyInResponse   func(ctx context.Context, msg *ServerCopyInResponse, arg Arg) (Result, error)
	CopyOutResponse  func(ctx context.Context, msg *ServerCopyOutResponse, arg Arg) (Result, error)
	CopyBothResponse func(ctx context.Context, msg *ServerCopyBothResponse, arg Arg) (Result, error)
	CopyData         func(ctx context.Context, msg *OldServerCopyData, arg Arg) (Result, error)
	CopyDone         func(ctx context.Context, msg *OldServerCopyDone, arg Arg) (Result, error)

	// Response
	Response             *ServerResponseHandlersCtx[Arg, Result]
	ReadyForQuery        func(ctx context.Context, msg *ServerReadyForQuery, arg Arg) (Result, error)
	CommandComplete      func(ctx context.Context, msg *ServerCommandComplete, arg Arg) (Result, error)
	DataRow              func(ctx context.Context, msg *ServerDataRow, arg Arg) (Result, error)
	EmptyQueryResponse   func(ctx context.Context, msg *ServerEmptyQueryResponse, arg Arg) (Result, error)
	ErrorResponse        func(ctx context.Context, msg *ServerErrorResponse, arg Arg) (Result, error)
	FunctionCallResponse func(ctx context.Context, msg *ServerFunctionCallResponse, arg Arg) (Result, error)

	// Async
	Async                *ServerAsyncHandlersCtx[Arg, Result]
	NoticeResponse       func(ctx context.Context, msg *ServerNoticeResponse, arg Arg) (Result, error)
	NotificationResponse func(ctx context.Context, msg *ServerNotificationResponse, arg Arg) (Result, error)
	ParameterStatus      func(ctx context.Context, msg *ServerParameterStatus, arg Arg) (Result, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerHandlers[Arg, Result]) HandleDefault(ctx context.Context, msg ServerMessage, arg Arg, defaultHandler func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error)) (r Result, err error) {
	if h.Default != nil {
		defaultHandler = h.Default
	} else if defaultHandler == nil {
		defaultHandler = func(ctx context.Context, msg ServerMessage, arg Arg) (Result, error) {
			panic(fmt.Sprintf("no handler defined for server message: %T", msg))
		}
	}
	switch msg := msg.(type) {
	case *ServerAuthenticationCleartextPassword:
		if h.AuthenticationCleartextPassword != nil {
			return h.AuthenticationCleartextPassword(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationCleartextPassword != nil {
			return h.Startup.AuthenticationCleartextPassword(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationGSS:
		if h.AuthenticationGSS != nil {
			return h.AuthenticationGSS(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationGSS != nil {
			return h.Startup.AuthenticationGSS(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationGSSContinue:
		if h.AuthenticationGSSContinue != nil {
			return h.AuthenticationGSSContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationGSSContinue != nil {
			return h.Startup.AuthenticationGSSContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationMD5Password:
		if h.AuthenticationMD5Password != nil {
			return h.AuthenticationMD5Password(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationMD5Password != nil {
			return h.Startup.AuthenticationMD5Password(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationOk:
		if h.AuthenticationOk != nil {
			return h.AuthenticationOk(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationOk != nil {
			return h.Startup.AuthenticationOk(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASL:
		if h.AuthenticationSASL != nil {
			return h.AuthenticationSASL(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASL != nil {
			return h.Startup.AuthenticationSASL(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASLContinue:
		if h.AuthenticationSASLContinue != nil {
			return h.AuthenticationSASLContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASLContinue != nil {
			return h.Startup.AuthenticationSASLContinue(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerAuthenticationSASLFinal:
		if h.AuthenticationSASLFinal != nil {
			return h.AuthenticationSASLFinal(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.AuthenticationSASLFinal != nil {
			return h.Startup.AuthenticationSASLFinal(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerBackendKeyData:
		if h.BackendKeyData != nil {
			return h.BackendKeyData(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.BackendKeyData != nil {
			return h.Startup.BackendKeyData(ctx, msg, arg)
		} else if h.Startup != nil && h.Startup.Default != nil {
			return h.Startup.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerParseComplete:
		if h.ParseComplete != nil {
			return h.ParseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.ParseComplete != nil {
			return h.ExtendedQuery.ParseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerBindComplete:
		if h.BindComplete != nil {
			return h.BindComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.BindComplete != nil {
			return h.ExtendedQuery.BindComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerParameterDescription:
		if h.ParameterDescription != nil {
			return h.ParameterDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.ParameterDescription != nil {
			return h.ExtendedQuery.ParameterDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerRowDescription:
		if h.RowDescription != nil {
			return h.RowDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.RowDescription != nil {
			return h.ExtendedQuery.RowDescription(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerNoData:
		if h.NoData != nil {
			return h.NoData(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.NoData != nil {
			return h.ExtendedQuery.NoData(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerPortalSuspended:
		if h.PortalSuspended != nil {
			return h.PortalSuspended(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.PortalSuspended != nil {
			return h.ExtendedQuery.PortalSuspended(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCloseComplete:
		if h.CloseComplete != nil {
			return h.CloseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.CloseComplete != nil {
			return h.ExtendedQuery.CloseComplete(ctx, msg, arg)
		} else if h.ExtendedQuery != nil && h.ExtendedQuery.Default != nil {
			return h.ExtendedQuery.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyInResponse != nil {
			return h.Copy.CopyInResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyOutResponse != nil {
			return h.Copy.CopyOutResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyBothResponse != nil {
			return h.Copy.CopyBothResponse(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *OldServerCopyData:
		if h.CopyData != nil {
			return h.CopyData(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyData != nil {
			return h.Copy.CopyData(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *OldServerCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.CopyDone != nil {
			return h.Copy.CopyDone(ctx, msg, arg)
		} else if h.Copy != nil && h.Copy.Default != nil {
			return h.Copy.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerReadyForQuery:
		if h.ReadyForQuery != nil {
			return h.ReadyForQuery(ctx, msg, arg)
		} else if h.Response != nil && h.Response.ReadyForQuery != nil {
			return h.Response.ReadyForQuery(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerCommandComplete:
		if h.CommandComplete != nil {
			return h.CommandComplete(ctx, msg, arg)
		} else if h.Response != nil && h.Response.CommandComplete != nil {
			return h.Response.CommandComplete(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerDataRow:
		if h.DataRow != nil {
			return h.DataRow(ctx, msg, arg)
		} else if h.Response != nil && h.Response.DataRow != nil {
			return h.Response.DataRow(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerEmptyQueryResponse:
		if h.EmptyQueryResponse != nil {
			return h.EmptyQueryResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.EmptyQueryResponse != nil {
			return h.Response.EmptyQueryResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerErrorResponse:
		if h.ErrorResponse != nil {
			return h.ErrorResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.ErrorResponse != nil {
			return h.Response.ErrorResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerFunctionCallResponse:
		if h.FunctionCallResponse != nil {
			return h.FunctionCallResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.FunctionCallResponse != nil {
			return h.Response.FunctionCallResponse(ctx, msg, arg)
		} else if h.Response != nil && h.Response.Default != nil {
			return h.Response.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerNoticeResponse:
		if h.NoticeResponse != nil {
			return h.NoticeResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.NoticeResponse != nil {
			return h.Async.NoticeResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerNotificationResponse:
		if h.NotificationResponse != nil {
			return h.NotificationResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.NotificationResponse != nil {
			return h.Async.NotificationResponse(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	case *ServerParameterStatus:
		if h.ParameterStatus != nil {
			return h.ParameterStatus(ctx, msg, arg)
		} else if h.Async != nil && h.Async.ParameterStatus != nil {
			return h.Async.ParameterStatus(ctx, msg, arg)
		} else if h.Async != nil && h.Async.Default != nil {
			return h.Async.Default(ctx, msg, arg)
		}
		return defaultHandler(ctx, msg, arg)
	}
	err = fmt.Errorf("unknown server message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerHandlers[Arg, Result]) Handle(ctx context.Context, msg ServerMessage, arg Arg) (Result, error) {
	return h.HandleDefault(ctx, msg, arg, nil)
}
