// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"fmt"

	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerCopy is implemented by all Server Copy message wrapper types.
type ServerCopy interface {
	Copy()
	PgwireMessage() pgproto3.Message
	Server() pgproto3.BackendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerCopy = ServerCopyCopyInResponse{}
	_ ServerCopy = ServerCopyCopyOutResponse{}
	_ ServerCopy = ServerCopyCopyBothResponse{}
	_ ServerCopy = ServerCopyCopyData{}
	_ ServerCopy = ServerCopyCopyDone{}
)

// Response to COPY FROM STDIN.
// Backend ready to copy data from client to server.
// Starts CopyIn mode.
type ServerCopyCopyInResponse FromServer[*pgproto3.CopyInResponse]

func (ServerCopyCopyInResponse) Copy()                             {}
func (t ServerCopyCopyInResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyInResponse) Server() pgproto3.BackendMessage { return t.T }

// Response to COPY TO STDOUT.
// Backend ready to copy data from server to client.
// Starts CopyOut mode.
type ServerCopyCopyOutResponse FromServer[*pgproto3.CopyOutResponse]

func (ServerCopyCopyOutResponse) Copy()                             {}
func (t ServerCopyCopyOutResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyOutResponse) Server() pgproto3.BackendMessage { return t.T }

// Response to Replication.
type ServerCopyCopyBothResponse FromServer[*pgproto3.CopyBothResponse]

func (ServerCopyCopyBothResponse) Copy()                             {}
func (t ServerCopyCopyBothResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyBothResponse) Server() pgproto3.BackendMessage { return t.T }

// Copy Mode: data row.
type ServerCopyCopyData FromServer[*pgproto3.CopyData]

func (ServerCopyCopyData) Copy()                             {}
func (t ServerCopyCopyData) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyData) Server() pgproto3.BackendMessage { return t.T }

// Copy Mode: copy completed.
type ServerCopyCopyDone FromServer[*pgproto3.CopyDone]

func (ServerCopyCopyDone) Copy()                             {}
func (t ServerCopyCopyDone) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyDone) Server() pgproto3.BackendMessage { return t.T }

// ToServerCopy converts a pgproto3.BackendMessage to a ServerCopy if it matches one of the known types.
func ToServerCopy(msg pgproto3.BackendMessage) (ServerCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyInResponse:
		return ServerCopyCopyInResponse{m}, true
	case *pgproto3.CopyOutResponse:
		return ServerCopyCopyOutResponse{m}, true
	case *pgproto3.CopyBothResponse:
		return ServerCopyCopyBothResponse{m}, true
	case *pgproto3.CopyData:
		return ServerCopyCopyData{m}, true
	case *pgproto3.CopyDone:
		return ServerCopyCopyDone{m}, true
	}
	return nil, false
}

// ServerCopyHandlers provides type-safe handlers for each ServerCopy variant.
type ServerCopyHandlers[T any] struct {
	CopyInResponse   func(msg ServerCopyCopyInResponse) (T, error)
	CopyOutResponse  func(msg ServerCopyCopyOutResponse) (T, error)
	CopyBothResponse func(msg ServerCopyCopyBothResponse) (T, error)
	CopyData         func(msg ServerCopyCopyData) (T, error)
	CopyDone         func(msg ServerCopyCopyDone) (T, error)
}

// HandleDefault dispatches to the appropriate handler, or calls defaultHandler if the handler is nil.
func (h ServerCopyHandlers[T]) HandleDefault(msg ServerCopy, defaultHandler func(msg ServerCopy) (T, error)) (r T, err error) {
	switch msg := msg.(type) {
	case ServerCopyCopyInResponse:
		if h.CopyInResponse != nil {
			return h.CopyInResponse(msg)
		} else {
			return defaultHandler(msg)
		}
	case ServerCopyCopyOutResponse:
		if h.CopyOutResponse != nil {
			return h.CopyOutResponse(msg)
		} else {
			return defaultHandler(msg)
		}
	case ServerCopyCopyBothResponse:
		if h.CopyBothResponse != nil {
			return h.CopyBothResponse(msg)
		} else {
			return defaultHandler(msg)
		}
	case ServerCopyCopyData:
		if h.CopyData != nil {
			return h.CopyData(msg)
		} else {
			return defaultHandler(msg)
		}
	case ServerCopyCopyDone:
		if h.CopyDone != nil {
			return h.CopyDone(msg)
		} else {
			return defaultHandler(msg)
		}
	}
	err = fmt.Errorf("unknown server copy message: %T", msg)
	return
}

// Handle dispatches to the appropriate handler, or panics if the handler is nil.
func (h ServerCopyHandlers[T]) Handle(msg ServerCopy) (T, error) {
	return h.HandleDefault(msg, func(msg ServerCopy) (T, error) {
		panic(fmt.Sprintf("no handler defined for server copy message: %T", msg))
	})
}
