// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerCopy is implemented by all Server Copy message wrapper types.
type ServerCopy interface {
	Copy()
	PgwireMessage() pgproto3.Message
	Server() pgproto3.BackendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerCopy = ServerCopyCopyInResponse{}
	_ ServerCopy = ServerCopyCopyOutResponse{}
	_ ServerCopy = ServerCopyCopyBothResponse{}
	_ ServerCopy = ServerCopyCopyData{}
	_ ServerCopy = ServerCopyCopyDone{}
)

// Response to COPY FROM STDIN.
// Backend ready to copy data from client to server.
// Starts CopyIn mode.
type ServerCopyCopyInResponse FromServer[*pgproto3.CopyInResponse]

func (ServerCopyCopyInResponse) Copy()                             {}
func (t ServerCopyCopyInResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyInResponse) Server() pgproto3.BackendMessage { return t.T }

// Response to COPY TO STDOUT.
// Backend ready to copy data from server to client.
// Starts CopyOut mode.
type ServerCopyCopyOutResponse FromServer[*pgproto3.CopyOutResponse]

func (ServerCopyCopyOutResponse) Copy()                             {}
func (t ServerCopyCopyOutResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyOutResponse) Server() pgproto3.BackendMessage { return t.T }

// Response to Replication.
type ServerCopyCopyBothResponse FromServer[*pgproto3.CopyBothResponse]

func (ServerCopyCopyBothResponse) Copy()                             {}
func (t ServerCopyCopyBothResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyBothResponse) Server() pgproto3.BackendMessage { return t.T }

// Copy Mode: data row.
type ServerCopyCopyData FromServer[*pgproto3.CopyData]

func (ServerCopyCopyData) Copy()                             {}
func (t ServerCopyCopyData) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyData) Server() pgproto3.BackendMessage { return t.T }

// Copy Mode: copy completed.
type ServerCopyCopyDone FromServer[*pgproto3.CopyDone]

func (ServerCopyCopyDone) Copy()                             {}
func (t ServerCopyCopyDone) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerCopyCopyDone) Server() pgproto3.BackendMessage { return t.T }

// ToServerCopy converts a pgproto3.BackendMessage to a ServerCopy if it matches one of the known types.
func ToServerCopy(msg pgproto3.BackendMessage) (ServerCopy, bool) {
	switch m := msg.(type) {
	case *pgproto3.CopyInResponse:
		return ServerCopyCopyInResponse{m}, true
	case *pgproto3.CopyOutResponse:
		return ServerCopyCopyOutResponse{m}, true
	case *pgproto3.CopyBothResponse:
		return ServerCopyCopyBothResponse{m}, true
	case *pgproto3.CopyData:
		return ServerCopyCopyData{m}, true
	case *pgproto3.CopyDone:
		return ServerCopyCopyDone{m}, true
	}
	return nil, false
}
