// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerAsync is implemented by all Server Async message wrapper types.
type ServerAsync interface {
	Async()
	PgwireMessage() pgproto3.Message
	Server() pgproto3.BackendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerAsync = ServerAsyncNoticeResponse{}
	_ ServerAsync = ServerAsyncNotificationResponse{}
	_ ServerAsync = ServerAsyncParameterStatus{}
)

// Warning message.
type ServerAsyncNoticeResponse FromServer[*pgproto3.NoticeResponse]

func (ServerAsyncNoticeResponse) Async()                            {}
func (t ServerAsyncNoticeResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerAsyncNoticeResponse) Server() pgproto3.BackendMessage { return t.T }

// LISTEN/NOTIFY notification.
type ServerAsyncNotificationResponse FromServer[*pgproto3.NotificationResponse]

func (ServerAsyncNotificationResponse) Async()                            {}
func (t ServerAsyncNotificationResponse) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerAsyncNotificationResponse) Server() pgproto3.BackendMessage { return t.T }

// Informs client that runtime parameter value changed.
type ServerAsyncParameterStatus FromServer[*pgproto3.ParameterStatus]

func (ServerAsyncParameterStatus) Async()                            {}
func (t ServerAsyncParameterStatus) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerAsyncParameterStatus) Server() pgproto3.BackendMessage { return t.T }

// ToServerAsync converts a pgproto3.BackendMessage to a ServerAsync if it matches one of the known types.
func ToServerAsync(msg pgproto3.BackendMessage) (ServerAsync, bool) {
	switch m := msg.(type) {
	case *pgproto3.NoticeResponse:
		return ServerAsyncNoticeResponse{m}, true
	case *pgproto3.NotificationResponse:
		return ServerAsyncNotificationResponse{m}, true
	case *pgproto3.ParameterStatus:
		return ServerAsyncParameterStatus{m}, true
	}
	return nil, false
}
