// Code generated by generate.go; DO NOT EDIT.

package pgwire

import (
	"github.com/jackc/pgx/v5/pgproto3"
)

// ServerExtendedQuery is implemented by all Server ExtendedQuery message wrapper types.
type ServerExtendedQuery interface {
	ExtendedQuery()
	PgwireMessage() pgproto3.Message
	Server() pgproto3.BackendMessage
}

// Compile-time checks that all wrapper types implement the interface.
var (
	_ ServerExtendedQuery = ServerExtendedQueryParseComplete{}
	_ ServerExtendedQuery = ServerExtendedQueryBindComplete{}
	_ ServerExtendedQuery = ServerExtendedQueryParameterDescription{}
	_ ServerExtendedQuery = ServerExtendedQueryRowDescription{}
	_ ServerExtendedQuery = ServerExtendedQueryNoData{}
	_ ServerExtendedQuery = ServerExtendedQueryPortalSuspended{}
	_ ServerExtendedQuery = ServerExtendedQueryCloseComplete{}
)

// Response to Parse.
type ServerExtendedQueryParseComplete FromServer[*pgproto3.ParseComplete]

func (ServerExtendedQueryParseComplete) ExtendedQuery()                    {}
func (t ServerExtendedQueryParseComplete) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryParseComplete) Server() pgproto3.BackendMessage { return t.T }

// Response to Bind.
type ServerExtendedQueryBindComplete FromServer[*pgproto3.BindComplete]

func (ServerExtendedQueryBindComplete) ExtendedQuery()                    {}
func (t ServerExtendedQueryBindComplete) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryBindComplete) Server() pgproto3.BackendMessage { return t.T }

// Response to Describe of prepared statemnt
type ServerExtendedQueryParameterDescription FromServer[*pgproto3.ParameterDescription]

func (ServerExtendedQueryParameterDescription) ExtendedQuery()                    {}
func (t ServerExtendedQueryParameterDescription) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryParameterDescription) Server() pgproto3.BackendMessage { return t.T }

// Response to Describe of portal or statement that returns data.
type ServerExtendedQueryRowDescription FromServer[*pgproto3.RowDescription]

func (ServerExtendedQueryRowDescription) ExtendedQuery()                    {}
func (t ServerExtendedQueryRowDescription) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryRowDescription) Server() pgproto3.BackendMessage { return t.T }

// Response to Describe of portal or statement that doesn't return data.
type ServerExtendedQueryNoData FromServer[*pgproto3.NoData]

func (ServerExtendedQueryNoData) ExtendedQuery()                    {}
func (t ServerExtendedQueryNoData) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryNoData) Server() pgproto3.BackendMessage { return t.T }

// Response to Execute if there are additional rows / the execute did not
// complete during the Execute call, the client should call Execute again.
type ServerExtendedQueryPortalSuspended FromServer[*pgproto3.PortalSuspended]

func (ServerExtendedQueryPortalSuspended) ExtendedQuery()                    {}
func (t ServerExtendedQueryPortalSuspended) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryPortalSuspended) Server() pgproto3.BackendMessage { return t.T }

// Response to Close of prepared statement or portal.
type ServerExtendedQueryCloseComplete FromServer[*pgproto3.CloseComplete]

func (ServerExtendedQueryCloseComplete) ExtendedQuery()                    {}
func (t ServerExtendedQueryCloseComplete) PgwireMessage() pgproto3.Message { return t.T }
func (t ServerExtendedQueryCloseComplete) Server() pgproto3.BackendMessage { return t.T }

// ToServerExtendedQuery converts a pgproto3.BackendMessage to a ServerExtendedQuery if it matches one of the known types.
func ToServerExtendedQuery(msg pgproto3.BackendMessage) (ServerExtendedQuery, bool) {
	switch m := msg.(type) {
	case *pgproto3.ParseComplete:
		return ServerExtendedQueryParseComplete{m}, true
	case *pgproto3.BindComplete:
		return ServerExtendedQueryBindComplete{m}, true
	case *pgproto3.ParameterDescription:
		return ServerExtendedQueryParameterDescription{m}, true
	case *pgproto3.RowDescription:
		return ServerExtendedQueryRowDescription{m}, true
	case *pgproto3.NoData:
		return ServerExtendedQueryNoData{m}, true
	case *pgproto3.PortalSuspended:
		return ServerExtendedQueryPortalSuspended{m}, true
	case *pgproto3.CloseComplete:
		return ServerExtendedQueryCloseComplete{m}, true
	}
	return nil, false
}
