// Code generated by generate_msg.go; DO NOT EDIT.
//go:generate go run generate_msg.go

package pgwire

import (
	"fmt"
	"io"

	"github.com/jackc/pgx/v5/pgproto3"
)

// Bind is a client request message.
// Responses: [BindComplete], [ErrorResponse].
type Bind Msg

func (m Bind) String() string        { return fmt.Sprintf("Bind(%v)", Msg(m)) }
func (m Bind) ExpectedType() MsgType { return MsgClientBind }
func (m Bind) CopyTyped() Bind       { return Bind(m.Msg().Copy()) }
func (m Bind) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Bind) ExpectedFrom() Sender        { return SenderClient }
func (m Bind) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Bind) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Bind) From() Sender   { return Msg(m).Sender }
func (m Bind) Msg() Msg       { return Msg(m) }
func (m Bind) Copy() TypedMsg { return m.CopyTyped() }
func (m Bind) Parse() (out pgproto3.Bind, err error) {
	return DecodeMsg[pgproto3.Bind](m.Msg())
}
func (m Bind) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Bind) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Bind) Len() int                            { return Msg(m).Len() }
func (m Bind) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Bind) Body() []byte                        { return Msg(m).Body() }
func (m Bind) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Bind) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Bind) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Bind) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Bind{}

// CancelRequest is a client startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type CancelRequest Msg

func (m CancelRequest) String() string           { return fmt.Sprintf("CancelRequest(%v)", Msg(m)) }
func (m CancelRequest) ExpectedType() MsgType    { return MsgCancelRequest }
func (m CancelRequest) CopyTyped() CancelRequest { return CancelRequest(m.Msg().Copy()) }
func (m CancelRequest) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CancelRequest) ExpectedFrom() Sender        { return SenderClient }
func (m CancelRequest) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m CancelRequest) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m CancelRequest) From() Sender   { return Msg(m).Sender }
func (m CancelRequest) Msg() Msg       { return Msg(m) }
func (m CancelRequest) Copy() TypedMsg { return m.CopyTyped() }
func (m CancelRequest) Parse() (out pgproto3.CancelRequest, err error) {
	return DecodeMsg[pgproto3.CancelRequest](m.Msg())
}
func (m CancelRequest) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CancelRequest) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CancelRequest) Len() int                            { return Msg(m).Len() }
func (m CancelRequest) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CancelRequest) Body() []byte                        { return Msg(m).Body() }
func (m CancelRequest) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CancelRequest) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CancelRequest) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CancelRequest) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = CancelRequest{}

// Close is a client request message.
// Responses: [CloseComplete], [ErrorResponse].
type Close Msg

func (m Close) String() string        { return fmt.Sprintf("Close(%v)", Msg(m)) }
func (m Close) ExpectedType() MsgType { return MsgClientClose }
func (m Close) CopyTyped() Close      { return Close(m.Msg().Copy()) }
func (m Close) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Close) ExpectedFrom() Sender        { return SenderClient }
func (m Close) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Close) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Close) From() Sender   { return Msg(m).Sender }
func (m Close) Msg() Msg       { return Msg(m) }
func (m Close) Copy() TypedMsg { return m.CopyTyped() }
func (m Close) Parse() (out pgproto3.Close, err error) {
	return DecodeMsg[pgproto3.Close](m.Msg())
}
func (m Close) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Close) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Close) Len() int                            { return Msg(m).Len() }
func (m Close) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Close) Body() []byte                        { return Msg(m).Body() }
func (m Close) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Close) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Close) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Close) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Close{}

// ClientCopyData is a client message.
type ClientCopyData Msg

func (m ClientCopyData) String() string            { return fmt.Sprintf("ClientCopyData(%v)", Msg(m)) }
func (m ClientCopyData) ExpectedType() MsgType     { return MsgClientCopyData }
func (m ClientCopyData) CopyTyped() ClientCopyData { return ClientCopyData(m.Msg().Copy()) }
func (m ClientCopyData) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ClientCopyData) ExpectedFrom() Sender        { return SenderClient }
func (m ClientCopyData) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m ClientCopyData) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m ClientCopyData) From() Sender   { return Msg(m).Sender }
func (m ClientCopyData) Msg() Msg       { return Msg(m) }
func (m ClientCopyData) Copy() TypedMsg { return m.CopyTyped() }
func (m ClientCopyData) Parse() (out pgproto3.CopyData, err error) {
	return DecodeMsg[pgproto3.CopyData](m.Msg())
}
func (m ClientCopyData) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ClientCopyData) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ClientCopyData) Len() int                            { return Msg(m).Len() }
func (m ClientCopyData) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ClientCopyData) Body() []byte                        { return Msg(m).Body() }
func (m ClientCopyData) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ClientCopyData) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ClientCopyData) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ClientCopyData) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = ClientCopyData{}

// ClientCopyDone is a client message.
type ClientCopyDone Msg

func (m ClientCopyDone) String() string            { return fmt.Sprintf("ClientCopyDone(%v)", Msg(m)) }
func (m ClientCopyDone) ExpectedType() MsgType     { return MsgClientCopyDone }
func (m ClientCopyDone) CopyTyped() ClientCopyDone { return ClientCopyDone(m.Msg().Copy()) }
func (m ClientCopyDone) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ClientCopyDone) ExpectedFrom() Sender        { return SenderClient }
func (m ClientCopyDone) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m ClientCopyDone) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m ClientCopyDone) From() Sender   { return Msg(m).Sender }
func (m ClientCopyDone) Msg() Msg       { return Msg(m) }
func (m ClientCopyDone) Copy() TypedMsg { return m.CopyTyped() }
func (m ClientCopyDone) Parse() (out pgproto3.CopyDone, err error) {
	return DecodeMsg[pgproto3.CopyDone](m.Msg())
}
func (m ClientCopyDone) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ClientCopyDone) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ClientCopyDone) Len() int                            { return Msg(m).Len() }
func (m ClientCopyDone) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ClientCopyDone) Body() []byte                        { return Msg(m).Body() }
func (m ClientCopyDone) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ClientCopyDone) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ClientCopyDone) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ClientCopyDone) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = ClientCopyDone{}

// CopyFail is a client message.
type CopyFail Msg

func (m CopyFail) String() string        { return fmt.Sprintf("CopyFail(%v)", Msg(m)) }
func (m CopyFail) ExpectedType() MsgType { return MsgClientCopyFail }
func (m CopyFail) CopyTyped() CopyFail   { return CopyFail(m.Msg().Copy()) }
func (m CopyFail) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CopyFail) ExpectedFrom() Sender        { return SenderClient }
func (m CopyFail) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m CopyFail) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m CopyFail) From() Sender   { return Msg(m).Sender }
func (m CopyFail) Msg() Msg       { return Msg(m) }
func (m CopyFail) Copy() TypedMsg { return m.CopyTyped() }
func (m CopyFail) Parse() (out pgproto3.CopyFail, err error) {
	return DecodeMsg[pgproto3.CopyFail](m.Msg())
}
func (m CopyFail) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CopyFail) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CopyFail) Len() int                            { return Msg(m).Len() }
func (m CopyFail) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CopyFail) Body() []byte                        { return Msg(m).Body() }
func (m CopyFail) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CopyFail) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CopyFail) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CopyFail) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = CopyFail{}

// Describe is a client request message.
// Responses: [RowDescription], [NoData], [ErrorResponse], [ParameterDescription].
type Describe Msg

func (m Describe) String() string        { return fmt.Sprintf("Describe(%v)", Msg(m)) }
func (m Describe) ExpectedType() MsgType { return MsgClientDescribe }
func (m Describe) CopyTyped() Describe   { return Describe(m.Msg().Copy()) }
func (m Describe) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Describe) ExpectedFrom() Sender        { return SenderClient }
func (m Describe) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Describe) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Describe) From() Sender   { return Msg(m).Sender }
func (m Describe) Msg() Msg       { return Msg(m) }
func (m Describe) Copy() TypedMsg { return m.CopyTyped() }
func (m Describe) Parse() (out pgproto3.Describe, err error) {
	return DecodeMsg[pgproto3.Describe](m.Msg())
}
func (m Describe) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Describe) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Describe) Len() int                            { return Msg(m).Len() }
func (m Describe) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Describe) Body() []byte                        { return Msg(m).Body() }
func (m Describe) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Describe) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Describe) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Describe) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Describe{}

// Execute is a client request message.
// Responses: [CommandComplete], [EmptyQueryResponse], [ErrorResponse], [PortalSuspended], [CopyInResponse], [CopyOutResponse], [CopyBothResponse].
type Execute Msg

func (m Execute) String() string        { return fmt.Sprintf("Execute(%v)", Msg(m)) }
func (m Execute) ExpectedType() MsgType { return MsgClientExecute }
func (m Execute) CopyTyped() Execute    { return Execute(m.Msg().Copy()) }
func (m Execute) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Execute) ExpectedFrom() Sender        { return SenderClient }
func (m Execute) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Execute) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Execute) From() Sender   { return Msg(m).Sender }
func (m Execute) Msg() Msg       { return Msg(m) }
func (m Execute) Copy() TypedMsg { return m.CopyTyped() }
func (m Execute) Parse() (out pgproto3.Execute, err error) {
	return DecodeMsg[pgproto3.Execute](m.Msg())
}
func (m Execute) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Execute) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Execute) Len() int                            { return Msg(m).Len() }
func (m Execute) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Execute) Body() []byte                        { return Msg(m).Body() }
func (m Execute) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Execute) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Execute) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Execute) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Execute{}

// Flush is a client message.
type Flush Msg

func (m Flush) String() string        { return fmt.Sprintf("Flush(%v)", Msg(m)) }
func (m Flush) ExpectedType() MsgType { return MsgClientFlush }
func (m Flush) CopyTyped() Flush      { return Flush(m.Msg().Copy()) }
func (m Flush) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Flush) ExpectedFrom() Sender        { return SenderClient }
func (m Flush) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Flush) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Flush) From() Sender   { return Msg(m).Sender }
func (m Flush) Msg() Msg       { return Msg(m) }
func (m Flush) Copy() TypedMsg { return m.CopyTyped() }
func (m Flush) Parse() (out pgproto3.Flush, err error) {
	return DecodeMsg[pgproto3.Flush](m.Msg())
}
func (m Flush) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Flush) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Flush) Len() int                            { return Msg(m).Len() }
func (m Flush) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Flush) Body() []byte                        { return Msg(m).Body() }
func (m Flush) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Flush) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Flush) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Flush) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Flush{}

// FunctionCall is a client request message.
// Responses: [ReadyForQuery], [FunctionCallResponse], [ErrorResponse], [NoticeResponse], [CopyInResponse], [CopyOutResponse], [CopyBothResponse].
type FunctionCall Msg

func (m FunctionCall) String() string          { return fmt.Sprintf("FunctionCall(%v)", Msg(m)) }
func (m FunctionCall) ExpectedType() MsgType   { return MsgClientFunc }
func (m FunctionCall) CopyTyped() FunctionCall { return FunctionCall(m.Msg().Copy()) }
func (m FunctionCall) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m FunctionCall) ExpectedFrom() Sender        { return SenderClient }
func (m FunctionCall) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m FunctionCall) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m FunctionCall) From() Sender   { return Msg(m).Sender }
func (m FunctionCall) Msg() Msg       { return Msg(m) }
func (m FunctionCall) Copy() TypedMsg { return m.CopyTyped() }
func (m FunctionCall) Parse() (out pgproto3.FunctionCall, err error) {
	return DecodeMsg[pgproto3.FunctionCall](m.Msg())
}
func (m FunctionCall) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m FunctionCall) MessageType() MsgType                { return Msg(m).MessageType() }
func (m FunctionCall) Len() int                            { return Msg(m).Len() }
func (m FunctionCall) Bytes() []byte                       { return Msg(m).Bytes() }
func (m FunctionCall) Body() []byte                        { return Msg(m).Body() }
func (m FunctionCall) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m FunctionCall) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m FunctionCall) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m FunctionCall) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = FunctionCall{}

// GSSEncRequest is a client startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type GSSEncRequest Msg

func (m GSSEncRequest) String() string           { return fmt.Sprintf("GSSEncRequest(%v)", Msg(m)) }
func (m GSSEncRequest) ExpectedType() MsgType    { return MsgGSSEncRequest }
func (m GSSEncRequest) CopyTyped() GSSEncRequest { return GSSEncRequest(m.Msg().Copy()) }
func (m GSSEncRequest) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m GSSEncRequest) ExpectedFrom() Sender        { return SenderClient }
func (m GSSEncRequest) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m GSSEncRequest) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m GSSEncRequest) From() Sender   { return Msg(m).Sender }
func (m GSSEncRequest) Msg() Msg       { return Msg(m) }
func (m GSSEncRequest) Copy() TypedMsg { return m.CopyTyped() }
func (m GSSEncRequest) Parse() (out pgproto3.GSSEncRequest, err error) {
	return DecodeMsg[pgproto3.GSSEncRequest](m.Msg())
}
func (m GSSEncRequest) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m GSSEncRequest) MessageType() MsgType                { return Msg(m).MessageType() }
func (m GSSEncRequest) Len() int                            { return Msg(m).Len() }
func (m GSSEncRequest) Bytes() []byte                       { return Msg(m).Bytes() }
func (m GSSEncRequest) Body() []byte                        { return Msg(m).Body() }
func (m GSSEncRequest) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m GSSEncRequest) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m GSSEncRequest) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m GSSEncRequest) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = GSSEncRequest{}

// Parse is a client request message.
// Responses: [ParseComplete], [ErrorResponse].
type Parse Msg

func (m Parse) String() string        { return fmt.Sprintf("Parse(%v)", Msg(m)) }
func (m Parse) ExpectedType() MsgType { return MsgClientParse }
func (m Parse) CopyTyped() Parse      { return Parse(m.Msg().Copy()) }
func (m Parse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Parse) ExpectedFrom() Sender        { return SenderClient }
func (m Parse) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Parse) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Parse) From() Sender   { return Msg(m).Sender }
func (m Parse) Msg() Msg       { return Msg(m) }
func (m Parse) Copy() TypedMsg { return m.CopyTyped() }
func (m Parse) Parse() (out pgproto3.Parse, err error) {
	return DecodeMsg[pgproto3.Parse](m.Msg())
}
func (m Parse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Parse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Parse) Len() int                            { return Msg(m).Len() }
func (m Parse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Parse) Body() []byte                        { return Msg(m).Body() }
func (m Parse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Parse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Parse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Parse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Parse{}

// PasswordMessage is a client startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type PasswordMessage Msg

func (m PasswordMessage) String() string             { return fmt.Sprintf("PasswordMessage(%v)", Msg(m)) }
func (m PasswordMessage) ExpectedType() MsgType      { return MsgClientPassword }
func (m PasswordMessage) CopyTyped() PasswordMessage { return PasswordMessage(m.Msg().Copy()) }
func (m PasswordMessage) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m PasswordMessage) ExpectedFrom() Sender        { return SenderClient }
func (m PasswordMessage) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m PasswordMessage) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m PasswordMessage) From() Sender   { return Msg(m).Sender }
func (m PasswordMessage) Msg() Msg       { return Msg(m) }
func (m PasswordMessage) Copy() TypedMsg { return m.CopyTyped() }
func (m PasswordMessage) Parse() (out pgproto3.PasswordMessage, err error) {
	return DecodeMsg[pgproto3.PasswordMessage](m.Msg())
}
func (m PasswordMessage) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m PasswordMessage) MessageType() MsgType                { return Msg(m).MessageType() }
func (m PasswordMessage) Len() int                            { return Msg(m).Len() }
func (m PasswordMessage) Bytes() []byte                       { return Msg(m).Bytes() }
func (m PasswordMessage) Body() []byte                        { return Msg(m).Body() }
func (m PasswordMessage) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m PasswordMessage) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m PasswordMessage) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m PasswordMessage) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = PasswordMessage{}

// Query is a client request message.
// Responses: [ReadyForQuery], [CommandComplete], [CopyInResponse], [CopyOutResponse], [CopyBothResponse], [RowDescription], [DataRow], [EmptyQueryResponse], [ErrorResponse], [NoticeResponse].
type Query Msg

func (m Query) String() string        { return fmt.Sprintf("Query(%v)", Msg(m)) }
func (m Query) ExpectedType() MsgType { return MsgClientQuery }
func (m Query) CopyTyped() Query      { return Query(m.Msg().Copy()) }
func (m Query) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Query) ExpectedFrom() Sender        { return SenderClient }
func (m Query) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Query) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Query) From() Sender   { return Msg(m).Sender }
func (m Query) Msg() Msg       { return Msg(m) }
func (m Query) Copy() TypedMsg { return m.CopyTyped() }
func (m Query) Parse() (out pgproto3.Query, err error) {
	return DecodeMsg[pgproto3.Query](m.Msg())
}
func (m Query) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Query) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Query) Len() int                            { return Msg(m).Len() }
func (m Query) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Query) Body() []byte                        { return Msg(m).Body() }
func (m Query) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Query) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Query) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Query) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Query{}

// SSLRequest is a client startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type SSLRequest Msg

func (m SSLRequest) String() string        { return fmt.Sprintf("SSLRequest(%v)", Msg(m)) }
func (m SSLRequest) ExpectedType() MsgType { return MsgSSLRequest }
func (m SSLRequest) CopyTyped() SSLRequest { return SSLRequest(m.Msg().Copy()) }
func (m SSLRequest) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m SSLRequest) ExpectedFrom() Sender        { return SenderClient }
func (m SSLRequest) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m SSLRequest) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m SSLRequest) From() Sender   { return Msg(m).Sender }
func (m SSLRequest) Msg() Msg       { return Msg(m) }
func (m SSLRequest) Copy() TypedMsg { return m.CopyTyped() }
func (m SSLRequest) Parse() (out pgproto3.SSLRequest, err error) {
	return DecodeMsg[pgproto3.SSLRequest](m.Msg())
}
func (m SSLRequest) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m SSLRequest) MessageType() MsgType                { return Msg(m).MessageType() }
func (m SSLRequest) Len() int                            { return Msg(m).Len() }
func (m SSLRequest) Bytes() []byte                       { return Msg(m).Bytes() }
func (m SSLRequest) Body() []byte                        { return Msg(m).Body() }
func (m SSLRequest) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m SSLRequest) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m SSLRequest) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m SSLRequest) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = SSLRequest{}

// StartupMessage is a client startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type StartupMessage Msg

func (m StartupMessage) String() string            { return fmt.Sprintf("StartupMessage(%v)", Msg(m)) }
func (m StartupMessage) ExpectedType() MsgType     { return MsgStartup }
func (m StartupMessage) CopyTyped() StartupMessage { return StartupMessage(m.Msg().Copy()) }
func (m StartupMessage) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m StartupMessage) ExpectedFrom() Sender        { return SenderClient }
func (m StartupMessage) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m StartupMessage) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m StartupMessage) From() Sender   { return Msg(m).Sender }
func (m StartupMessage) Msg() Msg       { return Msg(m) }
func (m StartupMessage) Copy() TypedMsg { return m.CopyTyped() }
func (m StartupMessage) Parse() (out pgproto3.StartupMessage, err error) {
	return DecodeMsg[pgproto3.StartupMessage](m.Msg())
}
func (m StartupMessage) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m StartupMessage) MessageType() MsgType                { return Msg(m).MessageType() }
func (m StartupMessage) Len() int                            { return Msg(m).Len() }
func (m StartupMessage) Bytes() []byte                       { return Msg(m).Bytes() }
func (m StartupMessage) Body() []byte                        { return Msg(m).Body() }
func (m StartupMessage) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m StartupMessage) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m StartupMessage) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m StartupMessage) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = StartupMessage{}

// Sync is a client request message.
// Responses: [ReadyForQuery].
type Sync Msg

func (m Sync) String() string        { return fmt.Sprintf("Sync(%v)", Msg(m)) }
func (m Sync) ExpectedType() MsgType { return MsgClientSync }
func (m Sync) CopyTyped() Sync       { return Sync(m.Msg().Copy()) }
func (m Sync) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Sync) ExpectedFrom() Sender        { return SenderClient }
func (m Sync) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Sync) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Sync) From() Sender   { return Msg(m).Sender }
func (m Sync) Msg() Msg       { return Msg(m) }
func (m Sync) Copy() TypedMsg { return m.CopyTyped() }
func (m Sync) Parse() (out pgproto3.Sync, err error) {
	return DecodeMsg[pgproto3.Sync](m.Msg())
}
func (m Sync) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Sync) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Sync) Len() int                            { return Msg(m).Len() }
func (m Sync) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Sync) Body() []byte                        { return Msg(m).Body() }
func (m Sync) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Sync) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Sync) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Sync) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Sync{}

// Terminate is a client message.
type Terminate Msg

func (m Terminate) String() string        { return fmt.Sprintf("Terminate(%v)", Msg(m)) }
func (m Terminate) ExpectedType() MsgType { return MsgClientTerminate }
func (m Terminate) CopyTyped() Terminate  { return Terminate(m.Msg().Copy()) }
func (m Terminate) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Terminate) ExpectedFrom() Sender        { return SenderClient }
func (m Terminate) ExpectedClientType() MsgType { return m.ExpectedType() }
func (m Terminate) CopyClient() ClientMsg       { return m.CopyTyped() }

func (m Terminate) From() Sender   { return Msg(m).Sender }
func (m Terminate) Msg() Msg       { return Msg(m) }
func (m Terminate) Copy() TypedMsg { return m.CopyTyped() }
func (m Terminate) Parse() (out pgproto3.Terminate, err error) {
	return DecodeMsg[pgproto3.Terminate](m.Msg())
}
func (m Terminate) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m Terminate) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Terminate) Len() int                            { return Msg(m).Len() }
func (m Terminate) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Terminate) Body() []byte                        { return Msg(m).Body() }
func (m Terminate) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Terminate) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Terminate) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Terminate) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ClientMsg = Terminate{}

// Authentication is a server startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type Authentication Msg

func (m Authentication) String() string            { return fmt.Sprintf("Authentication(%v)", Msg(m)) }
func (m Authentication) ExpectedType() MsgType     { return MsgServerAuth }
func (m Authentication) CopyTyped() Authentication { return Authentication(m.Msg().Copy()) }
func (m Authentication) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m Authentication) ExpectedFrom() Sender        { return SenderServer }
func (m Authentication) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m Authentication) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m Authentication) From() Sender   { return Msg(m).Sender }
func (m Authentication) Msg() Msg       { return Msg(m) }
func (m Authentication) Copy() TypedMsg { return m.CopyTyped() }
func (m Authentication) ParseAny() (pgproto3.Message, error) {
	return nil, fmt.Errorf("Authentication has no single pgproto3 equivalent")
}

func (m Authentication) MessageType() MsgType                { return Msg(m).MessageType() }
func (m Authentication) Len() int                            { return Msg(m).Len() }
func (m Authentication) Bytes() []byte                       { return Msg(m).Bytes() }
func (m Authentication) Body() []byte                        { return Msg(m).Body() }
func (m Authentication) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m Authentication) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m Authentication) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m Authentication) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = Authentication{}

// BackendKeyData is a server startup message.
// Startup messages only appear before the first [ReadyForQuery] response.
type BackendKeyData Msg

func (m BackendKeyData) String() string            { return fmt.Sprintf("BackendKeyData(%v)", Msg(m)) }
func (m BackendKeyData) ExpectedType() MsgType     { return MsgServerBackendKeyData }
func (m BackendKeyData) CopyTyped() BackendKeyData { return BackendKeyData(m.Msg().Copy()) }
func (m BackendKeyData) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m BackendKeyData) ExpectedFrom() Sender        { return SenderServer }
func (m BackendKeyData) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m BackendKeyData) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m BackendKeyData) From() Sender   { return Msg(m).Sender }
func (m BackendKeyData) Msg() Msg       { return Msg(m) }
func (m BackendKeyData) Copy() TypedMsg { return m.CopyTyped() }
func (m BackendKeyData) Parse() (out pgproto3.BackendKeyData, err error) {
	return DecodeMsg[pgproto3.BackendKeyData](m.Msg())
}
func (m BackendKeyData) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m BackendKeyData) MessageType() MsgType                { return Msg(m).MessageType() }
func (m BackendKeyData) Len() int                            { return Msg(m).Len() }
func (m BackendKeyData) Bytes() []byte                       { return Msg(m).Bytes() }
func (m BackendKeyData) Body() []byte                        { return Msg(m).Body() }
func (m BackendKeyData) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m BackendKeyData) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m BackendKeyData) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m BackendKeyData) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = BackendKeyData{}

// BindComplete is a server response message.
// Response to [Bind].
type BindComplete Msg

func (m BindComplete) String() string          { return fmt.Sprintf("BindComplete(%v)", Msg(m)) }
func (m BindComplete) ExpectedType() MsgType   { return MsgServerBindComplete }
func (m BindComplete) CopyTyped() BindComplete { return BindComplete(m.Msg().Copy()) }
func (m BindComplete) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m BindComplete) ExpectedFrom() Sender        { return SenderServer }
func (m BindComplete) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m BindComplete) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m BindComplete) From() Sender   { return Msg(m).Sender }
func (m BindComplete) Msg() Msg       { return Msg(m) }
func (m BindComplete) Copy() TypedMsg { return m.CopyTyped() }
func (m BindComplete) Parse() (out pgproto3.BindComplete, err error) {
	return DecodeMsg[pgproto3.BindComplete](m.Msg())
}
func (m BindComplete) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m BindComplete) MessageType() MsgType                { return Msg(m).MessageType() }
func (m BindComplete) Len() int                            { return Msg(m).Len() }
func (m BindComplete) Bytes() []byte                       { return Msg(m).Bytes() }
func (m BindComplete) Body() []byte                        { return Msg(m).Body() }
func (m BindComplete) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m BindComplete) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m BindComplete) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m BindComplete) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = BindComplete{}

// CloseComplete is a server response message.
// Response to [CommandComplete].
type CloseComplete Msg

func (m CloseComplete) String() string           { return fmt.Sprintf("CloseComplete(%v)", Msg(m)) }
func (m CloseComplete) ExpectedType() MsgType    { return MsgServerCloseComplete }
func (m CloseComplete) CopyTyped() CloseComplete { return CloseComplete(m.Msg().Copy()) }
func (m CloseComplete) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CloseComplete) ExpectedFrom() Sender        { return SenderServer }
func (m CloseComplete) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m CloseComplete) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m CloseComplete) From() Sender   { return Msg(m).Sender }
func (m CloseComplete) Msg() Msg       { return Msg(m) }
func (m CloseComplete) Copy() TypedMsg { return m.CopyTyped() }
func (m CloseComplete) Parse() (out pgproto3.CloseComplete, err error) {
	return DecodeMsg[pgproto3.CloseComplete](m.Msg())
}
func (m CloseComplete) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CloseComplete) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CloseComplete) Len() int                            { return Msg(m).Len() }
func (m CloseComplete) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CloseComplete) Body() []byte                        { return Msg(m).Body() }
func (m CloseComplete) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CloseComplete) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CloseComplete) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CloseComplete) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = CloseComplete{}

// CommandComplete is a server response message.
// Response to [ErrorResponse], [Query].
type CommandComplete Msg

func (m CommandComplete) String() string             { return fmt.Sprintf("CommandComplete(%v)", Msg(m)) }
func (m CommandComplete) ExpectedType() MsgType      { return MsgServerCommandComplete }
func (m CommandComplete) CopyTyped() CommandComplete { return CommandComplete(m.Msg().Copy()) }
func (m CommandComplete) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CommandComplete) ExpectedFrom() Sender        { return SenderServer }
func (m CommandComplete) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m CommandComplete) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m CommandComplete) From() Sender   { return Msg(m).Sender }
func (m CommandComplete) Msg() Msg       { return Msg(m) }
func (m CommandComplete) Copy() TypedMsg { return m.CopyTyped() }
func (m CommandComplete) Parse() (out pgproto3.CommandComplete, err error) {
	return DecodeMsg[pgproto3.CommandComplete](m.Msg())
}
func (m CommandComplete) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CommandComplete) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CommandComplete) Len() int                            { return Msg(m).Len() }
func (m CommandComplete) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CommandComplete) Body() []byte                        { return Msg(m).Body() }
func (m CommandComplete) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CommandComplete) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CommandComplete) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CommandComplete) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = CommandComplete{}

// CopyBothResponse is a server response message.
// Response to [ErrorResponse], [FunctionCall], [Query].
type CopyBothResponse Msg

func (m CopyBothResponse) String() string              { return fmt.Sprintf("CopyBothResponse(%v)", Msg(m)) }
func (m CopyBothResponse) ExpectedType() MsgType       { return MsgServerCopyBothResponse }
func (m CopyBothResponse) CopyTyped() CopyBothResponse { return CopyBothResponse(m.Msg().Copy()) }
func (m CopyBothResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CopyBothResponse) ExpectedFrom() Sender        { return SenderServer }
func (m CopyBothResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m CopyBothResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m CopyBothResponse) From() Sender   { return Msg(m).Sender }
func (m CopyBothResponse) Msg() Msg       { return Msg(m) }
func (m CopyBothResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m CopyBothResponse) Parse() (out pgproto3.CopyBothResponse, err error) {
	return DecodeMsg[pgproto3.CopyBothResponse](m.Msg())
}
func (m CopyBothResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CopyBothResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CopyBothResponse) Len() int                            { return Msg(m).Len() }
func (m CopyBothResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CopyBothResponse) Body() []byte                        { return Msg(m).Body() }
func (m CopyBothResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CopyBothResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CopyBothResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CopyBothResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = CopyBothResponse{}

// ServerCopyData is a server message.
type ServerCopyData Msg

func (m ServerCopyData) String() string            { return fmt.Sprintf("ServerCopyData(%v)", Msg(m)) }
func (m ServerCopyData) ExpectedType() MsgType     { return MsgServerCopyData }
func (m ServerCopyData) CopyTyped() ServerCopyData { return ServerCopyData(m.Msg().Copy()) }
func (m ServerCopyData) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ServerCopyData) ExpectedFrom() Sender        { return SenderServer }
func (m ServerCopyData) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ServerCopyData) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ServerCopyData) From() Sender   { return Msg(m).Sender }
func (m ServerCopyData) Msg() Msg       { return Msg(m) }
func (m ServerCopyData) Copy() TypedMsg { return m.CopyTyped() }
func (m ServerCopyData) Parse() (out pgproto3.CopyData, err error) {
	return DecodeMsg[pgproto3.CopyData](m.Msg())
}
func (m ServerCopyData) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ServerCopyData) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ServerCopyData) Len() int                            { return Msg(m).Len() }
func (m ServerCopyData) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ServerCopyData) Body() []byte                        { return Msg(m).Body() }
func (m ServerCopyData) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ServerCopyData) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ServerCopyData) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ServerCopyData) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ServerCopyData{}

// ServerCopyDone is a server message.
type ServerCopyDone Msg

func (m ServerCopyDone) String() string            { return fmt.Sprintf("ServerCopyDone(%v)", Msg(m)) }
func (m ServerCopyDone) ExpectedType() MsgType     { return MsgServerCopyDone }
func (m ServerCopyDone) CopyTyped() ServerCopyDone { return ServerCopyDone(m.Msg().Copy()) }
func (m ServerCopyDone) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ServerCopyDone) ExpectedFrom() Sender        { return SenderServer }
func (m ServerCopyDone) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ServerCopyDone) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ServerCopyDone) From() Sender   { return Msg(m).Sender }
func (m ServerCopyDone) Msg() Msg       { return Msg(m) }
func (m ServerCopyDone) Copy() TypedMsg { return m.CopyTyped() }
func (m ServerCopyDone) Parse() (out pgproto3.CopyDone, err error) {
	return DecodeMsg[pgproto3.CopyDone](m.Msg())
}
func (m ServerCopyDone) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ServerCopyDone) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ServerCopyDone) Len() int                            { return Msg(m).Len() }
func (m ServerCopyDone) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ServerCopyDone) Body() []byte                        { return Msg(m).Body() }
func (m ServerCopyDone) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ServerCopyDone) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ServerCopyDone) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ServerCopyDone) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ServerCopyDone{}

// CopyInResponse is a server response message.
// Response to [ErrorResponse], [FunctionCall], [Query].
type CopyInResponse Msg

func (m CopyInResponse) String() string            { return fmt.Sprintf("CopyInResponse(%v)", Msg(m)) }
func (m CopyInResponse) ExpectedType() MsgType     { return MsgServerCopyInResponse }
func (m CopyInResponse) CopyTyped() CopyInResponse { return CopyInResponse(m.Msg().Copy()) }
func (m CopyInResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CopyInResponse) ExpectedFrom() Sender        { return SenderServer }
func (m CopyInResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m CopyInResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m CopyInResponse) From() Sender   { return Msg(m).Sender }
func (m CopyInResponse) Msg() Msg       { return Msg(m) }
func (m CopyInResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m CopyInResponse) Parse() (out pgproto3.CopyInResponse, err error) {
	return DecodeMsg[pgproto3.CopyInResponse](m.Msg())
}
func (m CopyInResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CopyInResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CopyInResponse) Len() int                            { return Msg(m).Len() }
func (m CopyInResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CopyInResponse) Body() []byte                        { return Msg(m).Body() }
func (m CopyInResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CopyInResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CopyInResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CopyInResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = CopyInResponse{}

// CopyOutResponse is a server response message.
// Response to [ErrorResponse], [FunctionCall], [Query].
type CopyOutResponse Msg

func (m CopyOutResponse) String() string             { return fmt.Sprintf("CopyOutResponse(%v)", Msg(m)) }
func (m CopyOutResponse) ExpectedType() MsgType      { return MsgServerCopyOutResponse }
func (m CopyOutResponse) CopyTyped() CopyOutResponse { return CopyOutResponse(m.Msg().Copy()) }
func (m CopyOutResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m CopyOutResponse) ExpectedFrom() Sender        { return SenderServer }
func (m CopyOutResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m CopyOutResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m CopyOutResponse) From() Sender   { return Msg(m).Sender }
func (m CopyOutResponse) Msg() Msg       { return Msg(m) }
func (m CopyOutResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m CopyOutResponse) Parse() (out pgproto3.CopyOutResponse, err error) {
	return DecodeMsg[pgproto3.CopyOutResponse](m.Msg())
}
func (m CopyOutResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m CopyOutResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m CopyOutResponse) Len() int                            { return Msg(m).Len() }
func (m CopyOutResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m CopyOutResponse) Body() []byte                        { return Msg(m).Body() }
func (m CopyOutResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m CopyOutResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m CopyOutResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m CopyOutResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = CopyOutResponse{}

// DataRow is a server response message.
// Response to [Query].
type DataRow Msg

func (m DataRow) String() string        { return fmt.Sprintf("DataRow(%v)", Msg(m)) }
func (m DataRow) ExpectedType() MsgType { return MsgServerDataRow }
func (m DataRow) CopyTyped() DataRow    { return DataRow(m.Msg().Copy()) }
func (m DataRow) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m DataRow) ExpectedFrom() Sender        { return SenderServer }
func (m DataRow) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m DataRow) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m DataRow) From() Sender   { return Msg(m).Sender }
func (m DataRow) Msg() Msg       { return Msg(m) }
func (m DataRow) Copy() TypedMsg { return m.CopyTyped() }
func (m DataRow) Parse() (out pgproto3.DataRow, err error) {
	return DecodeMsg[pgproto3.DataRow](m.Msg())
}
func (m DataRow) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m DataRow) MessageType() MsgType                { return Msg(m).MessageType() }
func (m DataRow) Len() int                            { return Msg(m).Len() }
func (m DataRow) Bytes() []byte                       { return Msg(m).Bytes() }
func (m DataRow) Body() []byte                        { return Msg(m).Body() }
func (m DataRow) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m DataRow) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m DataRow) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m DataRow) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = DataRow{}

// EmptyQueryResponse is a server response message.
// Response to [ErrorResponse], [Query].
type EmptyQueryResponse Msg

func (m EmptyQueryResponse) String() string                { return fmt.Sprintf("EmptyQueryResponse(%v)", Msg(m)) }
func (m EmptyQueryResponse) ExpectedType() MsgType         { return MsgServerEmptyQueryResponse }
func (m EmptyQueryResponse) CopyTyped() EmptyQueryResponse { return EmptyQueryResponse(m.Msg().Copy()) }
func (m EmptyQueryResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m EmptyQueryResponse) ExpectedFrom() Sender        { return SenderServer }
func (m EmptyQueryResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m EmptyQueryResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m EmptyQueryResponse) From() Sender   { return Msg(m).Sender }
func (m EmptyQueryResponse) Msg() Msg       { return Msg(m) }
func (m EmptyQueryResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m EmptyQueryResponse) Parse() (out pgproto3.EmptyQueryResponse, err error) {
	return DecodeMsg[pgproto3.EmptyQueryResponse](m.Msg())
}
func (m EmptyQueryResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m EmptyQueryResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m EmptyQueryResponse) Len() int                            { return Msg(m).Len() }
func (m EmptyQueryResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m EmptyQueryResponse) Body() []byte                        { return Msg(m).Body() }
func (m EmptyQueryResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m EmptyQueryResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m EmptyQueryResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m EmptyQueryResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = EmptyQueryResponse{}

// ErrorResponse is a server response message.
// Response to [Bind], [CommandComplete], [DataRow], [ErrorResponse], [Parse], [FunctionCall], [Query].
type ErrorResponse Msg

func (m ErrorResponse) String() string           { return fmt.Sprintf("ErrorResponse(%v)", Msg(m)) }
func (m ErrorResponse) ExpectedType() MsgType    { return MsgServerErrorResponse }
func (m ErrorResponse) CopyTyped() ErrorResponse { return ErrorResponse(m.Msg().Copy()) }
func (m ErrorResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ErrorResponse) ExpectedFrom() Sender        { return SenderServer }
func (m ErrorResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ErrorResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ErrorResponse) From() Sender   { return Msg(m).Sender }
func (m ErrorResponse) Msg() Msg       { return Msg(m) }
func (m ErrorResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m ErrorResponse) Parse() (out pgproto3.ErrorResponse, err error) {
	return DecodeMsg[pgproto3.ErrorResponse](m.Msg())
}
func (m ErrorResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ErrorResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ErrorResponse) Len() int                            { return Msg(m).Len() }
func (m ErrorResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ErrorResponse) Body() []byte                        { return Msg(m).Body() }
func (m ErrorResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ErrorResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ErrorResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ErrorResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ErrorResponse{}

// FunctionCallResponse is a server response message.
// Response to [FunctionCall].
type FunctionCallResponse Msg

func (m FunctionCallResponse) String() string        { return fmt.Sprintf("FunctionCallResponse(%v)", Msg(m)) }
func (m FunctionCallResponse) ExpectedType() MsgType { return MsgServerFuncCallResponse }
func (m FunctionCallResponse) CopyTyped() FunctionCallResponse {
	return FunctionCallResponse(m.Msg().Copy())
}
func (m FunctionCallResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m FunctionCallResponse) ExpectedFrom() Sender        { return SenderServer }
func (m FunctionCallResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m FunctionCallResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m FunctionCallResponse) From() Sender   { return Msg(m).Sender }
func (m FunctionCallResponse) Msg() Msg       { return Msg(m) }
func (m FunctionCallResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m FunctionCallResponse) Parse() (out pgproto3.FunctionCallResponse, err error) {
	return DecodeMsg[pgproto3.FunctionCallResponse](m.Msg())
}
func (m FunctionCallResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m FunctionCallResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m FunctionCallResponse) Len() int                            { return Msg(m).Len() }
func (m FunctionCallResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m FunctionCallResponse) Body() []byte                        { return Msg(m).Body() }
func (m FunctionCallResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m FunctionCallResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m FunctionCallResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m FunctionCallResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = FunctionCallResponse{}

// NoData is a server response message.
// Response to [DataRow].
type NoData Msg

func (m NoData) String() string        { return fmt.Sprintf("NoData(%v)", Msg(m)) }
func (m NoData) ExpectedType() MsgType { return MsgServerNoData }
func (m NoData) CopyTyped() NoData     { return NoData(m.Msg().Copy()) }
func (m NoData) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m NoData) ExpectedFrom() Sender        { return SenderServer }
func (m NoData) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m NoData) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m NoData) From() Sender   { return Msg(m).Sender }
func (m NoData) Msg() Msg       { return Msg(m) }
func (m NoData) Copy() TypedMsg { return m.CopyTyped() }
func (m NoData) Parse() (out pgproto3.NoData, err error) {
	return DecodeMsg[pgproto3.NoData](m.Msg())
}
func (m NoData) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m NoData) MessageType() MsgType                { return Msg(m).MessageType() }
func (m NoData) Len() int                            { return Msg(m).Len() }
func (m NoData) Bytes() []byte                       { return Msg(m).Bytes() }
func (m NoData) Body() []byte                        { return Msg(m).Body() }
func (m NoData) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m NoData) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m NoData) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m NoData) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = NoData{}

// NoticeResponse is a server response message.
// Response to [FunctionCall], [Query].
type NoticeResponse Msg

func (m NoticeResponse) String() string            { return fmt.Sprintf("NoticeResponse(%v)", Msg(m)) }
func (m NoticeResponse) ExpectedType() MsgType     { return MsgServerNoticeResponse }
func (m NoticeResponse) CopyTyped() NoticeResponse { return NoticeResponse(m.Msg().Copy()) }
func (m NoticeResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m NoticeResponse) ExpectedFrom() Sender        { return SenderServer }
func (m NoticeResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m NoticeResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m NoticeResponse) From() Sender   { return Msg(m).Sender }
func (m NoticeResponse) Msg() Msg       { return Msg(m) }
func (m NoticeResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m NoticeResponse) Parse() (out pgproto3.NoticeResponse, err error) {
	return DecodeMsg[pgproto3.NoticeResponse](m.Msg())
}
func (m NoticeResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m NoticeResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m NoticeResponse) Len() int                            { return Msg(m).Len() }
func (m NoticeResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m NoticeResponse) Body() []byte                        { return Msg(m).Body() }
func (m NoticeResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m NoticeResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m NoticeResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m NoticeResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = NoticeResponse{}

// NotificationResponse is a server message.
type NotificationResponse Msg

func (m NotificationResponse) String() string        { return fmt.Sprintf("NotificationResponse(%v)", Msg(m)) }
func (m NotificationResponse) ExpectedType() MsgType { return MsgServerNotificationResponse }
func (m NotificationResponse) CopyTyped() NotificationResponse {
	return NotificationResponse(m.Msg().Copy())
}
func (m NotificationResponse) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m NotificationResponse) ExpectedFrom() Sender        { return SenderServer }
func (m NotificationResponse) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m NotificationResponse) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m NotificationResponse) From() Sender   { return Msg(m).Sender }
func (m NotificationResponse) Msg() Msg       { return Msg(m) }
func (m NotificationResponse) Copy() TypedMsg { return m.CopyTyped() }
func (m NotificationResponse) Parse() (out pgproto3.NotificationResponse, err error) {
	return DecodeMsg[pgproto3.NotificationResponse](m.Msg())
}
func (m NotificationResponse) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m NotificationResponse) MessageType() MsgType                { return Msg(m).MessageType() }
func (m NotificationResponse) Len() int                            { return Msg(m).Len() }
func (m NotificationResponse) Bytes() []byte                       { return Msg(m).Bytes() }
func (m NotificationResponse) Body() []byte                        { return Msg(m).Body() }
func (m NotificationResponse) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m NotificationResponse) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m NotificationResponse) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m NotificationResponse) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = NotificationResponse{}

// ParameterDescription is a server response message.
// Response to [DataRow].
type ParameterDescription Msg

func (m ParameterDescription) String() string        { return fmt.Sprintf("ParameterDescription(%v)", Msg(m)) }
func (m ParameterDescription) ExpectedType() MsgType { return MsgServerParameterDescription }
func (m ParameterDescription) CopyTyped() ParameterDescription {
	return ParameterDescription(m.Msg().Copy())
}
func (m ParameterDescription) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ParameterDescription) ExpectedFrom() Sender        { return SenderServer }
func (m ParameterDescription) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ParameterDescription) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ParameterDescription) From() Sender   { return Msg(m).Sender }
func (m ParameterDescription) Msg() Msg       { return Msg(m) }
func (m ParameterDescription) Copy() TypedMsg { return m.CopyTyped() }
func (m ParameterDescription) Parse() (out pgproto3.ParameterDescription, err error) {
	return DecodeMsg[pgproto3.ParameterDescription](m.Msg())
}
func (m ParameterDescription) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ParameterDescription) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ParameterDescription) Len() int                            { return Msg(m).Len() }
func (m ParameterDescription) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ParameterDescription) Body() []byte                        { return Msg(m).Body() }
func (m ParameterDescription) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ParameterDescription) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ParameterDescription) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ParameterDescription) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ParameterDescription{}

// ParameterStatus is a server message.
type ParameterStatus Msg

func (m ParameterStatus) String() string             { return fmt.Sprintf("ParameterStatus(%v)", Msg(m)) }
func (m ParameterStatus) ExpectedType() MsgType      { return MsgServerParameterStatus }
func (m ParameterStatus) CopyTyped() ParameterStatus { return ParameterStatus(m.Msg().Copy()) }
func (m ParameterStatus) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ParameterStatus) ExpectedFrom() Sender        { return SenderServer }
func (m ParameterStatus) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ParameterStatus) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ParameterStatus) From() Sender   { return Msg(m).Sender }
func (m ParameterStatus) Msg() Msg       { return Msg(m) }
func (m ParameterStatus) Copy() TypedMsg { return m.CopyTyped() }
func (m ParameterStatus) Parse() (out pgproto3.ParameterStatus, err error) {
	return DecodeMsg[pgproto3.ParameterStatus](m.Msg())
}
func (m ParameterStatus) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ParameterStatus) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ParameterStatus) Len() int                            { return Msg(m).Len() }
func (m ParameterStatus) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ParameterStatus) Body() []byte                        { return Msg(m).Body() }
func (m ParameterStatus) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ParameterStatus) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ParameterStatus) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ParameterStatus) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ParameterStatus{}

// ParseComplete is a server response message.
// Response to [Parse].
type ParseComplete Msg

func (m ParseComplete) String() string           { return fmt.Sprintf("ParseComplete(%v)", Msg(m)) }
func (m ParseComplete) ExpectedType() MsgType    { return MsgServerParseComplete }
func (m ParseComplete) CopyTyped() ParseComplete { return ParseComplete(m.Msg().Copy()) }
func (m ParseComplete) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ParseComplete) ExpectedFrom() Sender        { return SenderServer }
func (m ParseComplete) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ParseComplete) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ParseComplete) From() Sender   { return Msg(m).Sender }
func (m ParseComplete) Msg() Msg       { return Msg(m) }
func (m ParseComplete) Copy() TypedMsg { return m.CopyTyped() }
func (m ParseComplete) Parse() (out pgproto3.ParseComplete, err error) {
	return DecodeMsg[pgproto3.ParseComplete](m.Msg())
}
func (m ParseComplete) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ParseComplete) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ParseComplete) Len() int                            { return Msg(m).Len() }
func (m ParseComplete) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ParseComplete) Body() []byte                        { return Msg(m).Body() }
func (m ParseComplete) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ParseComplete) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ParseComplete) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ParseComplete) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ParseComplete{}

// PortalSuspended is a server response message.
// Response to [ErrorResponse].
type PortalSuspended Msg

func (m PortalSuspended) String() string             { return fmt.Sprintf("PortalSuspended(%v)", Msg(m)) }
func (m PortalSuspended) ExpectedType() MsgType      { return MsgServerPortalSuspended }
func (m PortalSuspended) CopyTyped() PortalSuspended { return PortalSuspended(m.Msg().Copy()) }
func (m PortalSuspended) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m PortalSuspended) ExpectedFrom() Sender        { return SenderServer }
func (m PortalSuspended) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m PortalSuspended) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m PortalSuspended) From() Sender   { return Msg(m).Sender }
func (m PortalSuspended) Msg() Msg       { return Msg(m) }
func (m PortalSuspended) Copy() TypedMsg { return m.CopyTyped() }
func (m PortalSuspended) Parse() (out pgproto3.PortalSuspended, err error) {
	return DecodeMsg[pgproto3.PortalSuspended](m.Msg())
}
func (m PortalSuspended) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m PortalSuspended) MessageType() MsgType                { return Msg(m).MessageType() }
func (m PortalSuspended) Len() int                            { return Msg(m).Len() }
func (m PortalSuspended) Bytes() []byte                       { return Msg(m).Bytes() }
func (m PortalSuspended) Body() []byte                        { return Msg(m).Body() }
func (m PortalSuspended) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m PortalSuspended) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m PortalSuspended) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m PortalSuspended) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = PortalSuspended{}

// ReadyForQuery is a server response message.
// Response to [FunctionCall], [Query], [ParameterStatus].
type ReadyForQuery Msg

func (m ReadyForQuery) String() string           { return fmt.Sprintf("ReadyForQuery(%v)", Msg(m)) }
func (m ReadyForQuery) ExpectedType() MsgType    { return MsgServerReadyForQuery }
func (m ReadyForQuery) CopyTyped() ReadyForQuery { return ReadyForQuery(m.Msg().Copy()) }
func (m ReadyForQuery) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m ReadyForQuery) ExpectedFrom() Sender        { return SenderServer }
func (m ReadyForQuery) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m ReadyForQuery) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m ReadyForQuery) From() Sender   { return Msg(m).Sender }
func (m ReadyForQuery) Msg() Msg       { return Msg(m) }
func (m ReadyForQuery) Copy() TypedMsg { return m.CopyTyped() }
func (m ReadyForQuery) Parse() (out pgproto3.ReadyForQuery, err error) {
	return DecodeMsg[pgproto3.ReadyForQuery](m.Msg())
}
func (m ReadyForQuery) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m ReadyForQuery) MessageType() MsgType                { return Msg(m).MessageType() }
func (m ReadyForQuery) Len() int                            { return Msg(m).Len() }
func (m ReadyForQuery) Bytes() []byte                       { return Msg(m).Bytes() }
func (m ReadyForQuery) Body() []byte                        { return Msg(m).Body() }
func (m ReadyForQuery) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m ReadyForQuery) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m ReadyForQuery) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m ReadyForQuery) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = ReadyForQuery{}

// RowDescription is a server response message.
// Response to [DataRow], [Query].
type RowDescription Msg

func (m RowDescription) String() string            { return fmt.Sprintf("RowDescription(%v)", Msg(m)) }
func (m RowDescription) ExpectedType() MsgType     { return MsgServerRowDescription }
func (m RowDescription) CopyTyped() RowDescription { return RowDescription(m.Msg().Copy()) }
func (m RowDescription) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	if m.MessageType() != m.ExpectedType() {
		return ErrMsgGoTypeMismatch
	}
	if m.From() != m.ExpectedFrom() {
		return ErrMsgSenderMismatch
	}
	return nil
}
func (m RowDescription) ExpectedFrom() Sender        { return SenderServer }
func (m RowDescription) ExpectedServerType() MsgType { return m.ExpectedType() }
func (m RowDescription) CopyServer() ServerMsg       { return m.CopyTyped() }

func (m RowDescription) From() Sender   { return Msg(m).Sender }
func (m RowDescription) Msg() Msg       { return Msg(m) }
func (m RowDescription) Copy() TypedMsg { return m.CopyTyped() }
func (m RowDescription) Parse() (out pgproto3.RowDescription, err error) {
	return DecodeMsg[pgproto3.RowDescription](m.Msg())
}
func (m RowDescription) ParseAny() (pgproto3.Message, error) {
	return DecodeTypedMsg(m)
}

func (m RowDescription) MessageType() MsgType                { return Msg(m).MessageType() }
func (m RowDescription) Len() int                            { return Msg(m).Len() }
func (m RowDescription) Bytes() []byte                       { return Msg(m).Bytes() }
func (m RowDescription) Body() []byte                        { return Msg(m).Body() }
func (m RowDescription) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m RowDescription) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m RowDescription) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m RowDescription) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ ServerMsg = RowDescription{}

// UnknownMsg wraps a message with an unrecognized type byte.
type UnknownMsg Msg

func (m UnknownMsg) String() string        { return fmt.Sprintf("UnknownMsg(%v)", Msg(m)) }
func (m UnknownMsg) ExpectedType() MsgType { return 0 }
func (m UnknownMsg) CopyTyped() UnknownMsg { return UnknownMsg(m.Msg().Copy()) }
func (m UnknownMsg) Validate() error {
	if err := Msg(m).Validate(); err != nil {
		return err
	}
	return ErrMsgGoTypeMismatch
}

func (m UnknownMsg) From() Sender   { return Msg(m).Sender }
func (m UnknownMsg) Msg() Msg       { return Msg(m) }
func (m UnknownMsg) Copy() TypedMsg { return m.CopyTyped() }
func (m UnknownMsg) ParseAny() (pgproto3.Message, error) {
	return nil, fmt.Errorf("UnknownMsg cannot be parsed")
}

func (m UnknownMsg) MessageType() MsgType                { return Msg(m).MessageType() }
func (m UnknownMsg) Len() int                            { return Msg(m).Len() }
func (m UnknownMsg) Bytes() []byte                       { return Msg(m).Bytes() }
func (m UnknownMsg) Body() []byte                        { return Msg(m).Body() }
func (m UnknownMsg) NewReader() io.Reader                { return Msg(m).NewReader() }
func (m UnknownMsg) WriteTo(w io.Writer) (int64, error)  { return Msg(m).WriteTo(w) }
func (m UnknownMsg) AppendTo(buf []byte) ([]byte, error) { return Msg(m).AppendTo(buf) }
func (m UnknownMsg) Retain() RawMessageSource            { return Msg(m).Retain() }

var _ TypedMsg = UnknownMsg{}

// Typed converts a Msg to its specific TypedMsg wrapper based on Sender and MessageType.
// Returns the concrete type (e.g., Bind, Query, DataRow) based on the wire type byte.
// Returns UnknownMsg if the type byte is not recognized for the sender.
//
// The switch is ordered by MsgParsePriority for hot-path optimization:
// most frequent message types are checked first, and unambiguous types
// (unique to client or server) return immediately without checking Sender.
func Typed(m Msg) TypedMsg {
	switch m.MessageType() {
	case MsgClientDescribe: // Describe (client) / DataRow (server)
		if m.Sender == SenderClient {
			return Describe(m)
		}
		return DataRow(m)
	case MsgClientCopyData: // ClientCopyData (client) / ServerCopyData (server)
		if m.Sender == SenderClient {
			return ClientCopyData(m)
		}
		return ServerCopyData(m)
	case MsgServerReadyForQuery:
		return ReadyForQuery(m)
	case MsgClientClose: // Close (client) / CommandComplete (server)
		if m.Sender == SenderClient {
			return Close(m)
		}
		return CommandComplete(m)
	case MsgClientQuery:
		return Query(m)
	case MsgClientParse:
		return Parse(m)
	case MsgClientBind:
		return Bind(m)
	case MsgClientExecute: // Execute (client) / ErrorResponse (server)
		if m.Sender == SenderClient {
			return Execute(m)
		}
		return ErrorResponse(m)
	case MsgClientSync: // Sync (client) / ParameterStatus (server)
		if m.Sender == SenderClient {
			return Sync(m)
		}
		return ParameterStatus(m)
	case MsgServerBindComplete:
		return BindComplete(m)
	case MsgServerParseComplete:
		return ParseComplete(m)
	case MsgServerCloseComplete:
		return CloseComplete(m)
	case MsgServerRowDescription:
		return RowDescription(m)
	case MsgServerParameterDescription:
		return ParameterDescription(m)
	case MsgServerNoData:
		return NoData(m)
	case MsgServerCopyInResponse:
		return CopyInResponse(m)
	case MsgClientFlush: // Flush (client) / CopyOutResponse (server)
		if m.Sender == SenderClient {
			return Flush(m)
		}
		return CopyOutResponse(m)
	case MsgServerCopyBothResponse:
		return CopyBothResponse(m)
	case MsgClientCopyDone: // ClientCopyDone (client) / ServerCopyDone (server)
		if m.Sender == SenderClient {
			return ClientCopyDone(m)
		}
		return ServerCopyDone(m)
	case MsgClientCopyFail:
		return CopyFail(m)
	case MsgServerNoticeResponse:
		return NoticeResponse(m)
	case MsgServerAuth:
		return Authentication(m)
	case MsgServerBackendKeyData:
		return BackendKeyData(m)
	case MsgClientTerminate:
		return Terminate(m)
	case MsgClientFunc:
		return FunctionCall(m)
	case MsgClientPassword:
		return PasswordMessage(m)
	case MsgServerEmptyQueryResponse:
		return EmptyQueryResponse(m)
	case MsgServerPortalSuspended:
		return PortalSuspended(m)
	case MsgServerFuncCallResponse:
		return FunctionCallResponse(m)
	case MsgServerNotificationResponse:
		return NotificationResponse(m)
	case MsgStartup:
		return StartupMessage(m)
	case MsgSSLRequest:
		return SSLRequest(m)
	case MsgCancelRequest:
		return CancelRequest(m)
	case MsgGSSEncRequest:
		return GSSEncRequest(m)
	}
	return UnknownMsg(m)
}
